import { call } from './api.js?v=3';

const S={ctx:null,items:[],admin:false,allowed:false};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const statusList=[['planejada','Planejada'],['em_analise','Em análise'],['em_desenvolvimento','Em desenvolvimento'],['testando','Testando'],['concluida','Concluída'],['cancelada','Cancelada']];
const priList=[['baixa','Baixa'],['media','Média'],['alta','Alta'],['critica','Crítica']];
const label=(arr,v)=>(arr.find(x=>x[0]===v)||[v,v])[1];
const badgeStatus=v=>({concluida:'ok',cancelada:'bad',testando:'warn',em_analise:'warn',em_desenvolvimento:'info'}[v]||'');
const badgePri=v=>({critica:'bad',alta:'warn',baixa:'ok'}[v]||'');
function msg(t,c=''){const el=$('backlogMsg');if(el){el.textContent=t;el.className='msg show '+c;}}
function css(){if($('backlogCss'))return;const s=document.createElement('style');s.id='backlogCss';s.textContent=`.backlog-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.backlog-kpi{border:1px solid #e5e7eb;border-radius:16px;background:#fff;padding:12px}.backlog-kpi small{display:block;color:#64748b;font-weight:800}.backlog-kpi b{font-size:22px}.backlog-grid{display:grid;grid-template-columns:360px 1fr;gap:12px}.backlog-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.backlog-card{border:1px solid #e5e7eb;border-radius:16px;background:#fff;padding:12px;margin-bottom:10px}.backlog-card h3{margin:0 0 6px;font-size:16px}.backlog-card p{margin:6px 0;color:#475569}.backlog-muted{color:#64748b;font-size:12px}.badge.ok{background:#dcfce7;color:#166534}.badge.bad{background:#fee2e2;color:#991b1b}.badge.warn{background:#fef3c7;color:#92400e}.badge.info{background:#dbeafe;color:#1d4ed8}.backlog-admin{display:none}.backlog-admin-on .backlog-admin{display:block}@media(max-width:1050px){.backlog-grid{grid-template-columns:1fr}.backlog-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.backlog-kpis{grid-template-columns:1fr}.backlog-actions{display:grid;grid-template-columns:1fr}.backlog-actions>*{width:100%}}`;document.head.appendChild(s);}
function canView(ctx){const p=ctx?.permissoes||{};return !!(ctx?.is_admin||p.relatorios||p.painel_producao);}
function removeUi(){const n=$('navBacklogClean'),p=$('page-backlog-clean');const active=n?.classList.contains('active')||p?.classList.contains('active');n?.remove();p?.remove();if(active)document.querySelector('[data-page="dashboard"]')?.click();}
async function ensureAccess(){try{const ctx=await call('rpc_usuario_contexto_6c',{});S.ctx=ctx;S.admin=!!ctx?.is_admin;S.allowed=canView(ctx);if(S.allowed)inject();else removeUi();return S.allowed;}catch(e){S.allowed=false;S.admin=false;removeUi();return false;}}
function moveNavToGestao(){const nav=$('navBacklogClean');const group=$('sideGroupItems-gestao');if(nav&&group&&!nav.closest('#sideGroupItems-gestao'))group.appendChild(nav);const g=$('sideGroup-gestao');if(g&&nav?.classList.contains('active'))g.classList.remove('collapsed');}
function inject(){css();if(!$('navBacklogClean')){const ref=$('navRelatoriosClean')||$('navAuditoriaClean')||document.querySelector('[data-page="dashboard"]');const b=document.createElement('button');b.id='navBacklogClean';b.className='nav';b.textContent='Melhorias';b.onclick=show;ref?ref.insertAdjacentElement('afterend',b):document.querySelector('.sidebar')?.appendChild(b);}if(!$('page-backlog-clean')){const sec=document.createElement('section');sec.id='page-backlog-clean';sec.className='page';sec.innerHTML=`<div class="card"><div class="table-head"><div><h2>Melhorias do sistema</h2><p>Backlog controlado da fase 7A em diante.</p></div><button id="backlogReload" class="secondary">Recarregar</button></div><div id="backlogMsg" class="msg show warn">Carregando...</div></div><div id="backlogKpis" class="backlog-kpis"></div><div class="backlog-grid"><form id="backlogForm" class="card form-card backlog-admin"><h2>Novo / editar item</h2><input id="backlogCodigo" placeholder="Código. Ex: 7A.6"><input id="backlogTitulo" placeholder="Título"><textarea id="backlogDescricao" placeholder="Descrição"></textarea><div class="form-grid two"><input id="backlogCategoria" placeholder="Categoria"><select id="backlogPrioridade">${priList.map(p=>`<option value="${p[0]}">${p[1]}</option>`).join('')}</select></div><input id="backlogImpacto" placeholder="Impacto"><input id="backlogRisco" placeholder="Risco"><input id="backlogDependencia" placeholder="Dependência"><div class="actions"><button class="primary" type="submit">Salvar</button><button class="secondary" type="button" id="backlogLimpar">Limpar</button></div></form><div class="card"><div class="table-head"><h2>Backlog</h2><div class="backlog-actions"><input id="backlogBusca" placeholder="Buscar"><select id="backlogFiltroStatus"><option value="">Todos status</option>${statusList.map(s=>`<option value="${s[0]}">${s[1]}</option>`).join('')}</select><select id="backlogFiltroPrioridade"><option value="">Todas prioridades</option>${priList.map(p=>`<option value="${p[0]}">${p[1]}</option>`).join('')}</select></div></div><div id="backlogLista"></div></div></div>`;document.querySelector('.main')?.appendChild(sec);}document.body.classList.toggle('backlog-admin-on',S.admin);$('backlogReload').onclick=loadAll;$('backlogForm').onsubmit=salvar;$('backlogLimpar').onclick=limpar;['backlogBusca','backlogFiltroStatus','backlogFiltroPrioridade'].forEach(id=>$(id).oninput=render);window.permissoes6DRefresh?.();setTimeout(moveNavToGestao,200);setTimeout(moveNavToGestao,900);}
async function show(){const ok=S.allowed||await ensureAccess();if(!ok){alert('Acesso restrito.');return;}inject();document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.id==='navBacklogClean'));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-backlog-clean'));moveNavToGestao();if($('pageTitle'))$('pageTitle').textContent='Melhorias';await loadAll();}
function kpi(l,v){return `<div class="backlog-kpi"><small>${esc(l)}</small><b>${esc(v)}</b></div>`;}
function resumo(){const items=S.items||[];return{total:items.length,abertas:items.filter(i=>!['concluida','cancelada'].includes(i.status)).length,concluidas:items.filter(i=>i.status==='concluida').length,altas:items.filter(i=>['alta','critica'].includes(i.prioridade)).length,testando:items.filter(i=>i.status==='testando').length};}
async function loadAll(){try{msg('Carregando melhorias...','warn');const res=await call('rpc_listar_backlog_7a',{});S.items=res.items||[];render();msg('Backlog carregado.','ok');}catch(e){msg(e.message||String(e),'bad');}}
function filtrados(){const q=norm($('backlogBusca')?.value),st=$('backlogFiltroStatus')?.value,pr=$('backlogFiltroPrioridade')?.value;return(S.items||[]).filter(i=>(!st||i.status===st)&&(!pr||i.prioridade===pr)&&(!q||norm([i.codigo,i.titulo,i.descricao,i.categoria].join(' ')).includes(q)));}
function render(){if(!$('backlogKpis'))return;const r=resumo();$('backlogKpis').innerHTML=[kpi('Total',r.total),kpi('Abertas',r.abertas),kpi('Concluídas',r.concluidas),kpi('Alta/crítica',r.altas),kpi('Testando',r.testando)].join('');const arr=filtrados();$('backlogLista').innerHTML=arr.map(card).join('')||'<div class="backlog-card"><b>Nenhum item encontrado.</b></div>';document.querySelectorAll('[data-bl-edit]').forEach(b=>b.onclick=()=>editar(b.dataset.blEdit));document.querySelectorAll('[data-bl-status]').forEach(s=>s.onchange=()=>atualizarStatus(s.dataset.blStatus,s.value));}
function card(i){return `<div class="backlog-card"><div class="table-head"><div><h3>${esc(i.codigo)} — ${esc(i.titulo)}</h3><div class="backlog-muted">${esc(i.categoria||'melhoria')}</div></div><div class="backlog-actions backlog-admin"><button class="secondary" data-bl-edit="${esc(i.codigo)}">Editar</button></div></div><div class="backlog-actions"><span class="badge ${badgeStatus(i.status)}">${esc(label(statusList,i.status))}</span><span class="badge ${badgePri(i.prioridade)}">${esc(label(priList,i.prioridade))}</span></div>${i.descricao?`<p>${esc(i.descricao)}</p>`:''}${i.impacto?`<p><b>Impacto:</b> ${esc(i.impacto)}</p>`:''}${i.risco?`<p><b>Risco:</b> ${esc(i.risco)}</p>`:''}<div class="backlog-admin"><select data-bl-status="${esc(i.codigo)}">${statusList.map(s=>`<option value="${s[0]}" ${s[0]===i.status?'selected':''}>${s[1]}</option>`).join('')}</select></div></div>`;}
function limpar(){['backlogCodigo','backlogTitulo','backlogDescricao','backlogCategoria','backlogImpacto','backlogRisco','backlogDependencia'].forEach(id=>$(id).value='');$('backlogPrioridade').value='media';}
function editar(c){const i=S.items.find(x=>x.codigo===c);if(!i)return;$('backlogCodigo').value=i.codigo||'';$('backlogTitulo').value=i.titulo||'';$('backlogDescricao').value=i.descricao||'';$('backlogCategoria').value=i.categoria||'';$('backlogPrioridade').value=i.prioridade||'media';$('backlogImpacto').value=i.impacto||'';$('backlogRisco').value=i.risco||'';$('backlogDependencia').value=i.dependencia||'';msg('Item carregado.','ok');}
async function salvar(ev){ev.preventDefault();try{if(!S.admin)throw new Error('Apenas admin pode salvar.');await call('rpc_criar_item_backlog_7a',{p_codigo:$('backlogCodigo').value.trim().toUpperCase(),p_titulo:$('backlogTitulo').value.trim(),p_descricao:$('backlogDescricao').value.trim()||null,p_categoria:$('backlogCategoria').value.trim()||'melhoria',p_prioridade:$('backlogPrioridade').value,p_impacto:$('backlogImpacto').value.trim()||null,p_risco:$('backlogRisco').value.trim()||null,p_dependencia:$('backlogDependencia').value.trim()||null});limpar();await loadAll();msg('Melhoria salva.','ok');}catch(e){msg(e.message||String(e),'bad');}}
async function atualizarStatus(c,s){try{if(!S.admin)throw new Error('Apenas admin pode alterar status.');await call('rpc_atualizar_status_backlog_7a',{p_codigo:c,p_status:s,p_observacao:'Painel 7A.1'});await loadAll();msg('Status atualizado.','ok');}catch(e){msg(e.message||String(e),'bad');}}
function boot(){document.addEventListener('like:session',ev=>{if(ev.detail?.user)ensureAccess();else removeUi();});setTimeout(ensureAccess,1600);setTimeout(ensureAccess,4200);}
boot();
