import { call } from './api.js?v=3';

const S={allowed:false,inventarios:[],termo:null,ativoId:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dt=v=>{try{return v?new Date(v).toLocaleString('pt-BR'):'-'}catch(e){return'-'}};
const statusLabel=v=>({aprovado:'Aprovado',aprovado_com_ressalva:'Aprovado com ressalva',reprovado:'Reprovado'}[v]||'Sem termo');
function msg(t,c=''){const el=$('termoInvMsg');if(el){el.textContent=t;el.className='msg show '+c;}}
function canView(ctx){const p=ctx?.permissoes||{};return !!(ctx?.is_admin||p.auditoria);}
function css(){if($('termoInvCss'))return;const s=document.createElement('style');s.id='termoInvCss';s.textContent=`.termo-box{border:1px solid #dbeafe;background:#f8fbff}.termo-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.termo-hash{font-family:monospace;font-size:11px;word-break:break-all;background:#f1f5f9;border-radius:10px;padding:8px}.termo-actions{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:760px){.termo-grid{grid-template-columns:1fr}.termo-actions{display:grid;grid-template-columns:1fr}.termo-actions>*{width:100%}}`;document.head.appendChild(s);}
async function ensureAccess(){try{const ctx=await call('rpc_usuario_contexto_6c',{});S.allowed=canView(ctx);if(S.allowed)inject();return S.allowed;}catch(e){S.allowed=false;return false;}}
function page(){return $('page-invrel-clean');}
function selectedFromRel(){return document.querySelector('.invrel-active [data-invrel-id]')?.dataset?.invrelId || null;}
function inject(){css();const p=page();if(!p||$('termoInvCard'))return false;const right=p.querySelector('.invrel-grid > div:last-child')||p;const card=document.createElement('div');card.id='termoInvCard';card.className='card termo-box';card.innerHTML=`<div class="table-head"><div><h2>Termo de fechamento</h2><p>Formaliza o resultado do inventário com aprovação, ressalva ou reprovação.</p></div><button id="termoInvReload" class="secondary">Atualizar</button></div><div id="termoInvMsg" class="msg show warn">Selecione um inventário para registrar o termo.</div><div class="termo-grid"><div><label>Inventário</label><select id="termoInvSelect"></select></div><div><label>Status final</label><select id="termoInvStatus"><option value="aprovado">Aprovado</option><option value="aprovado_com_ressalva">Aprovado com ressalva</option><option value="reprovado">Reprovado</option></select></div><div><label>Responsável pelo inventário</label><input id="termoInvResponsavel" placeholder="Nome do responsável"></div><div><label>Gestor / auditoria</label><input id="termoInvAuditor" placeholder="Nome do gestor ou auditor"></div></div><label>Observações / ressalvas</label><textarea id="termoInvObs" placeholder="Informe ressalvas, decisões ou justificativas"></textarea><div class="termo-actions"><button id="termoInvSalvar" class="primary">Registrar termo</button><button id="termoInvPdf" class="secondary">PDF do termo</button></div><div id="termoInvResumo" style="margin-top:10px"></div>`;right.insertBefore(card,right.children[1]||null);bind();loadInventarios();return true;}
function bind(){if($('termoInvSalvar').dataset.bound)return;$('termoInvSalvar').dataset.bound='1';$('termoInvReload').onclick=()=>{loadInventarios();carregarTermo();};$('termoInvSelect').onchange=carregarTermo;$('termoInvSalvar').onclick=salvar;$('termoInvPdf').onclick=pdf;}
async function loadInventarios(){if(!S.allowed)return;try{const res=await call('rpc_listar_inventarios_7a5',{p_status:null,p_limite:100});S.inventarios=res.inventarios||[];const selected=selectedFromRel()||S.ativoId||S.inventarios[0]?.id||'';$('termoInvSelect').innerHTML=S.inventarios.map(i=>`<option value="${esc(i.id)}" ${i.id===selected?'selected':''}>${esc(i.codigo)} — ${esc(i.titulo)} (${esc(i.status)})</option>`).join('');S.ativoId=$('termoInvSelect').value||selected;if(S.ativoId)await carregarTermo();}catch(e){msg(e.message||String(e),'bad');}}
async function carregarTermo(){try{S.ativoId=$('termoInvSelect')?.value||selectedFromRel();if(!S.ativoId){msg('Nenhum inventário selecionado.','warn');return;}S.termo=await call('rpc_termo_inventario_7a5_3',{p_inventario_id:S.ativoId});const t=S.termo.termo||{},inv=S.termo.inventario||{},r=S.termo.resumo||{};$('termoInvStatus').value=t.status||'aprovado';$('termoInvResponsavel').value=t.responsavel||'';$('termoInvAuditor').value=t.auditor||'';$('termoInvObs').value=t.observacoes||'';$('termoInvResumo').innerHTML=`<div class="invrel-card"><h3>${esc(inv.codigo)} — ${esc(statusLabel(t.status))}</h3><p>Local: ${esc(inv.local_alvo)} • Inventário: ${esc(inv.status)}</p><p>Bipados: ${esc(r.total_bipado||0)} • OK: ${esc(r.ok||0)} • Divergentes: ${esc(r.divergente||0)} • Faltantes: ${esc(r.faltantes||0)}</p><p>Gerado em: ${esc(dt(t.gerado_em))}</p>${t.hash?`<div class="termo-hash">Hash: ${esc(t.hash)}</div>`:'<p class="msg show warn">Termo ainda não registrado.</p>'}</div>`;msg(t.hash?'Termo carregado.':'Inventário carregado, termo ainda não registrado.',t.hash?'ok':'warn');}catch(e){msg(e.message||String(e),'bad');}}
async function salvar(){try{const id=$('termoInvSelect').value;if(!id)throw new Error('Selecione um inventário.');const responsavel=$('termoInvResponsavel').value.trim();const auditor=$('termoInvAuditor').value.trim();if(responsavel.length<3)throw new Error('Informe o responsável.');if(auditor.length<3)throw new Error('Informe o gestor/auditor.');await call('rpc_registrar_termo_inventario_7a5_3',{p_inventario_id:id,p_termo_status:$('termoInvStatus').value,p_responsavel:responsavel,p_auditor:auditor,p_observacoes:$('termoInvObs').value.trim()||null});await carregarTermo();msg('Termo registrado com sucesso.','ok');}catch(e){msg(e.message||String(e),'bad');}}
function pdf(){if(!S.termo){msg('Carregue ou registre um termo primeiro.','bad');return;}const js=window.jspdf?.jsPDF;if(!js){msg('jsPDF não carregado.','bad');return;}const doc=new js({orientation:'portrait',unit:'mm',format:'a4'});const inv=S.termo.inventario||{},r=S.termo.resumo||{},t=S.termo.termo||{};let y=12;const W=210,M=14;const line=(l,v)=>{doc.setFontSize(9);doc.setFont(undefined,'bold');doc.text(`${l}:`,M,y);doc.setFont(undefined,'normal');doc.text(String(v||'-'),M+42,y);y+=7;};doc.setFillColor(15,76,129);doc.rect(0,0,W,22,'F');doc.setTextColor(255,255,255);doc.setFontSize(15);doc.setFont(undefined,'bold');doc.text('Termo de Fechamento de Inventário',M,14);doc.setTextColor(20,30,45);y=32;doc.setFontSize(12);doc.setFont(undefined,'bold');doc.text('1. Identificação',M,y);y+=9;line('Inventário',inv.codigo);line('Título',inv.titulo);line('Local',inv.local_alvo);line('Status inventário',inv.status);line('Gerado em',dt(t.gerado_em)||dt(new Date()));y+=4;doc.setFontSize(12);doc.setFont(undefined,'bold');doc.text('2. Resultado da conferência',M,y);y+=9;line('Status final',statusLabel(t.status));line('Bipados',r.total_bipado||0);line('OK',r.ok||0);line('Divergentes',r.divergente||0);line('Não encontrados',r.nao_encontrado||0);line('Inativos',r.inativo||0);line('Faltantes',r.faltantes||0);y+=4;doc.setFontSize(12);doc.setFont(undefined,'bold');doc.text('3. Observações e ressalvas',M,y);y+=8;doc.setFontSize(9);doc.setFont(undefined,'normal');doc.text(doc.splitTextToSize(t.observacoes||'Sem observações registradas.',W-(M*2)),M,y);y+=28;doc.setFontSize(12);doc.setFont(undefined,'bold');doc.text('4. Declaração',M,y);y+=8;doc.setFontSize(9);doc.setFont(undefined,'normal');const txt='Declaro que o inventário informado foi conferido conforme os registros de bipagem e divergências apresentados no relatório. Este termo não altera estoque automaticamente; qualquer correção deve ser auditada e registrada no sistema.';doc.text(doc.splitTextToSize(txt,W-(M*2)),M,y);y+=28;doc.setFontSize(9);doc.text('Responsável pelo inventário',M,y+12);doc.line(M,y+8,92,y+8);doc.text(t.responsavel||'',M,y+18);doc.text('Gestor / Auditoria',118,y+12);doc.line(118,y+8,196,y+8);doc.text(t.auditor||'',118,y+18);y+=34;doc.setFontSize(8);doc.setTextColor(100,116,139);doc.text('Hash de validação:',M,y);y+=5;doc.text(doc.splitTextToSize(t.hash||'-',W-(M*2)),M,y);doc.text(`Página 1 de 1`,W-M,290,{align:'right'});doc.save(`termo_inventario_${inv.codigo||'relatorio'}.pdf`);}
function tryInject(){ensureAccess().then(ok=>{if(ok){inject();}});}
function boot(){document.addEventListener('like:session',ev=>{if(ev.detail?.user)tryInject();});document.addEventListener('click',ev=>{if(ev.target?.id==='navInvRelClean'||ev.target?.matches?.('[data-invrel-id]'))setTimeout(tryInject,500);});setTimeout(tryInject,2500);setTimeout(tryInject,6000);}
boot();
