import { table } from './api.js';

const S={eq:[],mat:[],equipamentos:[],saldos:[],tecnicos:[],tipo:'todos',busca:'',ini:'',fim:''};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=v=>{try{return v?new Date(v).toLocaleString('pt-BR'):'-'}catch(e){return String(v||'-')}};
const br=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const qtd=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:3});
const ativo=e=>e&&e.ativo!==false&&!['Baixado','Inutilizado','Perdido'].includes(e.status||'');
function nomeEq(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function nomeMat(m){return [m.tipo,m.marca,m.modelo].filter(Boolean).join(' ')}
function msg(t,c=''){let e=$('relCleanMsg');if(e){e.textContent=t;e.className='msg show '+c}}
function inject(){
 if(!$('navRelatoriosClean')){let ref=$('navTecnicosClean')||$('navMateriaisClean')||$('navEquipamentosClean')||document.querySelector('[data-page="cadastros"]');let b=document.createElement('button');b.id='navRelatoriosClean';b.className='nav';b.textContent='Histórico/Relatórios';b.onclick=show;ref?ref.insertAdjacentElement('afterend',b):document.querySelector('.sidebar').appendChild(b)}
 if(!$('page-relatorios-clean')){let s=document.createElement('section');s.id='page-relatorios-clean';s.className='page';s.innerHTML=`<div class="card"><div class="table-head"><div><h2>Histórico e Relatórios</h2><p>Consulta limpa de movimentações, estoque, técnicos, materiais e baixas.</p></div><button id="relReload" class="secondary">Recarregar</button></div><div class="form-grid two"><input id="relBusca" placeholder="Buscar técnico, MAC, SN, código, cliente, OS, material"><select id="relTipo"><option value="todos">Histórico geral</option><option value="equipamentos">Somente equipamentos</option><option value="materiais">Somente materiais</option><option value="estoque">Relatório estoque central</option><option value="tecnicos">Relatório por técnico</option><option value="materiais-saldo">Relatório de materiais</option><option value="baixas">Baixas/Inutilizados/Perdidos</option></select></div><div class="form-grid two"><input id="relIni" type="date"><input id="relFim" type="date"></div><div class="actions"><button id="relCopiar" class="warn">Copiar resumo</button><button id="relImprimir" class="primary">Imprimir / PDF</button></div><div id="relCleanMsg" class="msg"></div></div><div class="kpis"><div class="kpi"><small>Mov. equipamentos</small><b id="relKEq">0</b></div><div class="kpi"><small>Mov. materiais</small><b id="relKMat">0</b></div><div class="kpi"><small>Equip. ativos</small><b id="relKAtivos">0</b></div><div class="kpi"><small>Saldos materiais</small><b id="relKSaldos">0</b></div></div><div class="card" id="relPrintArea"><h2 id="relTitulo">Resultado</h2><div id="relOut"></div></div>`;document.querySelector('.main').appendChild(s)}
 $('relReload').onclick=()=>load().catch(e=>msg(e.message,'bad'));$('relBusca').oninput=()=>{S.busca=$('relBusca').value||'';render()};$('relTipo').onchange=()=>{S.tipo=$('relTipo').value;render()};$('relIni').onchange=()=>{S.ini=$('relIni').value;render()};$('relFim').onchange=()=>{S.fim=$('relFim').value;render()};$('relCopiar').onclick=copiar;$('relImprimir').onclick=()=>window.print();
}
function show(){inject();document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.id==='navRelatoriosClean'));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='page-relatorios-clean'));if($('pageTitle'))$('pageTitle').textContent='Histórico/Relatórios';load().catch(e=>msg(e.message,'bad'))}
async function load(){msg('Carregando relatórios...','warn');S.eq=await table('movimentos','created_at',false);S.mat=await table('materiais_movimentos','created_at',false);S.equipamentos=await table('equipamentos','created_at',false);S.saldos=await table('materiais_saldos','tipo',true);S.tecnicos=await table('tecnicos','nome',true);render();msg('Relatórios carregados.','ok')}
function periodoOk(d){if(!d)return true;let x=String(d).slice(0,10);if(S.ini&&x<S.ini)return false;if(S.fim&&x>S.fim)return false;return true}
function buscaOk(o){let f=(S.busca||'').toLowerCase();return !f||JSON.stringify(o).toLowerCase().includes(f)}
function movs(){let a=S.eq.filter(m=>periodoOk(m.created_at||m.data)&&buscaOk(m)).map(m=>({data:m.created_at||m.data,origem:'Equipamento',tipo:m.tipo||'',item:m.codigo||m.mac||m.serial||'',tecnico:m.tecnico||'',cliente:m.cliente||'',os:m.os||'',qtd:'',obs:m.obs||m.motivo||''}));let b=S.mat.filter(m=>periodoOk(m.created_at||m.data)&&buscaOk(m)).map(m=>({data:m.created_at||m.data,origem:'Material',tipo:m.motivo||'Material',item:nomeMat(m),tecnico:m.tecnico||'',cliente:'',os:'',qtd:qtd(m.quantidade),obs:m.obs||''}));if(S.tipo==='equipamentos')return a;if(S.tipo==='materiais')return b;return [...a,...b].sort((x,y)=>new Date(y.data||0)-new Date(x.data||0))}
function render(){if(!$('relOut'))return;$('relKEq').textContent=S.eq.length;$('relKMat').textContent=S.mat.length;$('relKAtivos').textContent=S.equipamentos.filter(ativo).length;$('relKSaldos').textContent=S.saldos.length;let t=S.tipo;if(t==='estoque')return renderEstoque();if(t==='tecnicos')return renderTecnicos();if(t==='materiais-saldo')return renderMateriais();if(t==='baixas')return renderBaixas();renderHistorico()}
function renderHistorico(){let rows=movs().slice(0,300);$('relTitulo').textContent='Histórico geral';$('relOut').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Origem</th><th>Tipo</th><th>Item</th><th>Técnico</th><th>Cliente/OS</th><th>Qtd</th><th>Obs</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(fmt(x.data))}</td><td>${esc(x.origem)}</td><td>${esc(x.tipo)}</td><td>${esc(x.item)}</td><td>${esc(x.tecnico)}</td><td>${esc(x.cliente)}<br><small>${esc(x.os)}</small></td><td>${esc(x.qtd)}</td><td>${esc(x.obs)}</td></tr>`).join('')||'<tr><td colspan="8">Sem histórico no filtro.</td></tr>'}</tbody></table></div>`}
function renderEstoque(){let rows=S.equipamentos.filter(e=>ativo(e)&&e.status==='Em estoque'&&buscaOk(e));$('relTitulo').textContent='Relatório de estoque central';$('relOut').innerHTML=tbl(['Código','Equipamento','MAC/SN','Local','Custo'],rows.map(e=>[e.codigo,nomeEq(e),e.mac||e.serial||'-',e.local||'-',br(e.custo)]))}
function renderTecnicos(){let nomes=new Set();S.tecnicos.filter(x=>x.ativo!==false).forEach(t=>t.nome&&nomes.add(t.nome));S.equipamentos.forEach(e=>e.tecnico_atual&&nomes.add(e.tecnico_atual));S.saldos.forEach(s=>s.tecnico&&nomes.add(s.tecnico));let rows=[...nomes].filter(n=>!S.busca||n.toLowerCase().includes(S.busca.toLowerCase())).map(n=>{let eq=S.equipamentos.filter(e=>ativo(e)&&e.tecnico_atual===n&&!['Em estoque','Instalado cliente','Instalado no cliente'].includes(e.status||''));let mat=S.saldos.filter(s=>s.tecnico===n&&Number(s.quantidade||0)>0);let val=eq.reduce((a,e)=>a+Number(e.custo||0),0);return [n,eq.length,mat.length,br(val)]});$('relTitulo').textContent='Relatório por técnico';$('relOut').innerHTML=tbl(['Técnico','Equipamentos','Materiais','Valor patrimônio'],rows)}
function renderMateriais(){let rows=S.saldos.filter(buscaOk).map(s=>[s.categoria||'',nomeMat(s),s.unidade_saida||'',s.local||'-',s.tecnico||'-',qtd(s.quantidade)]);$('relTitulo').textContent='Relatório de materiais';$('relOut').innerHTML=tbl(['Categoria','Material','Unidade','Local','Técnico','Quantidade'],rows)}
function renderBaixas(){let rows=S.equipamentos.filter(e=>['Baixado','Inutilizado','Perdido'].includes(e.status||'')&&buscaOk(e)).map(e=>[e.codigo,nomeEq(e),e.mac||e.serial||'-',e.status||'',e.motivo_atual||e.motivo_baixa||'',br(e.custo)]);$('relTitulo').textContent='Relatório de baixas/inutilizados/perdidos';$('relOut').innerHTML=tbl(['Código','Equipamento','MAC/SN','Status','Motivo','Custo'],rows)}
function tbl(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${head.length}">Sem dados.</td></tr>`}</tbody></table></div>`}
function texto(){let title=$('relTitulo')?.textContent||'Relatório';let lines=[title,'Gerado em: '+new Date().toLocaleString('pt-BR'),''];let cells=[...document.querySelectorAll('#relOut tr')].slice(0,80).map(tr=>[...tr.children].map(td=>td.textContent.trim()).join(' | '));return lines.concat(cells).join('\n')}
async function copiar(){try{await navigator.clipboard.writeText(texto());msg('Resumo copiado.','ok')}catch(e){prompt('Copie o relatório:',texto())}}
inject();window.relatoriosCleanLoad=load;
