(function(){
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function norm(v){try{return N(v)}catch(e){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}}
function txtModelo(m){return ((m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||'')).toLowerCase()}
function catModelo(m){let c=String(m.categoria_estoque||m.categoria||m.controle||'').toLowerCase(),t=txtModelo(m);if(/drop|bobina|cabo de rede|cat5|cat6|internet/.test(t)||c.includes('fechado')||c.includes('pacote'))return 'Material fechado';if(/rj45|rj 45|conector|conectores|adaptador|abraçadeira|abracadeira|bucha|parafuso|fita|cordão|cordao|patch cord|pigtail|pig tail/.test(t)||c.includes('quant')||c.includes('consumo'))return 'Consumo';if(c.includes('patrim')||c.includes('unit'))return 'Patrimônio';return 'Patrimônio'}
function modelosPat(){return (D.modelos||[]).filter(m=>catModelo(m)==='Patrimônio')}
function modeloSel(){let t=E('tipo')&&E('tipo').value,m=E('marca')&&E('marca').value,mo=E('modelo')&&E('modelo').value;return (D.modelos||[]).find(x=>x.tipo===t&&x.marca===m&&x.modelo===mo)}
function css(){if(E('entradaPatCss'))return;let s=document.createElement('style');s.id='entradaPatCss';s.textContent='.entradaPatInfo{background:#eef6ff;border:1px solid #bfdbfe;color:#0f4c81;border-radius:14px;padding:12px;margin:8px 0;font-weight:800}.entradaPatOnlyMaterialWarn{background:#fef3c7;border-color:#fde68a;color:#92400e}.entradaLegacyMaterialHidden{display:none!important}';document.head.appendChild(s)}
function setTitle(){let nav=document.querySelector('[data-p="entrada"]');if(nav)nav.textContent='Entrada patrimonial';let sec=E('p-entrada');if(!sec)return;let h=sec.querySelector('.card h2');if(h)h.textContent='Entrada patrimonial';if(!E('entradaPatInfo')){let card=sec.querySelector('.card');if(card&&h)h.insertAdjacentHTML('afterend','<div id="entradaPatInfo" class="entradaPatInfo">Use esta tela somente para equipamentos com controle individual: ONT, ONU, roteador, câmera e similares. RJ45, conectores, bobinas, cabos e materiais por quantidade devem ser lançados na aba Materiais.</div>')}}
function fillPatSelects(){let mods=modelosPat(),old={tipo:E('tipo')&&E('tipo').value,marca:E('marca')&&E('marca').value,modelo:E('modelo')&&E('modelo').value};let tipos=[...new Set(mods.map(m=>m.tipo).filter(Boolean))].sort();let marcas=[...new Set(mods.filter(m=>!old.tipo||m.tipo===old.tipo).map(m=>m.marca).filter(Boolean))].sort();if(E('tipo'))E('tipo').innerHTML='<option value="">Tipo patrimonial</option>'+tipos.map(x=>'<option>'+H(x)+'</option>').join('');if(E('tipo')&&tipos.includes(old.tipo))E('tipo').value=old.tipo;if(E('marca')){let t=E('tipo').value;marcas=[...new Set(mods.filter(m=>!t||m.tipo===t).map(m=>m.marca).filter(Boolean))].sort();E('marca').innerHTML='<option value="">Marca</option>'+marcas.map(x=>'<option>'+H(x)+'</option>').join('');if(marcas.includes(old.marca))E('marca').value=old.marca}if(E('modelo')){let t=E('tipo').value,ma=E('marca').value;let list=mods.filter(m=>(!t||m.tipo===t)&&(!ma||m.marca===ma));E('modelo').innerHTML='<option value="">Modelo</option>'+list.map(m=>'<option>'+H(m.modelo)+'</option>').join('');if(list.some(m=>m.modelo===old.modelo))E('modelo').value=old.modelo}}
function updateVisibility(){let m=modeloSel(),info=E('entradaPatInfo');let isMat=m&&catModelo(m)!=='Patrimônio';['mac','serial','pat'].forEach(id=>{let el=E(id);if(el)el.classList.toggle('entradaLegacyMaterialHidden',!!isMat)});if(info){if(isMat){info.className='entradaPatInfo entradaPatOnlyMaterialWarn';info.innerHTML='Este produto é material de '+H(catModelo(m))+'. Não registre nesta tela. Use a aba <b>Materiais</b> para entrada por quantidade.'}else{info.className='entradaPatInfo';info.textContent='Use esta tela somente para equipamentos com controle individual: ONT, ONU, roteador, câmera e similares. RJ45, conectores, bobinas, cabos e materiais por quantidade devem ser lançados na aba Materiais.'}}
}
function bind(){['tipo','marca'].forEach(id=>{let el=E(id);if(el&&!el.dataset.patBind){el.dataset.patBind='1';el.addEventListener('change',()=>{fillPatSelects();updateVisibility()})}});let mo=E('modelo');if(mo&&!mo.dataset.patBind){mo.dataset.patBind='1';mo.addEventListener('change',updateVisibility)}let btn=E('entrada');if(btn&&!btn.dataset.patBtn){btn.dataset.patBtn='1';btn.textContent='Registrar entrada patrimonial'}}
function patchEntrada(){if(window.__entradaPatched||typeof window.entrada!=='function')return;window.__entradaPatched=true;let original=window.entrada;window.entrada=async function(){let m=modeloSel();if(m&&catModelo(m)!=='Patrimônio'){msg('entMsg','Este item é material de '+catModelo(m)+'. Use a aba Materiais para lançar quantidade.','bad');return}return original()}}
function run(){css();setTitle();fillPatSelects();updateVisibility();bind();patchEntrada()}
const oldPg=window.pg;if(!window.__entradaPatPg&&typeof oldPg==='function'){window.__entradaPatPg=true;window.pg=function(p){oldPg(p);if(p==='entrada')setTimeout(run,100)}}
const oldRender=window.render;if(!window.__entradaPatRender&&typeof oldRender==='function'){window.__entradaPatRender=true;window.render=function(){oldRender();if(E('p-entrada'))setTimeout(run,50)}}
document.addEventListener('DOMContentLoaded',()=>{[600,1800,4000,8000,14000].forEach(t=>setTimeout(run,t))});window.entradaPatrimonialGuardRun=run;
})();