(function(){
let matSaldos=[],matMovs=[];
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function num(v){return Number(String(v||'').replace(',','.'))||0}
function catModelo(m){let c=String(m.categoria_estoque||m.categoria||m.controle||'').toLowerCase();let txt=((m.tipo||'')+' '+(m.modelo||'')).toLowerCase();if(c.includes('patrim')||c.includes('unit'))return 'Patrimônio';if(c.includes('fechado')||c.includes('pacote')||/drop|bobina|cabo de rede|cat5|cat6|internet/.test(txt))return 'Material fechado';if(/rj45|rj 45|conector|adaptador|abraçadeira|abracadeira|bucha|parafuso|fita/.test(txt))return 'Consumo';return 'Consumo'}
function unidadeModelo(m){return m.unidade_saida||m.unidade||(catModelo(m)==='Material fechado'?'Bobina':'Unidade')}
function isMaterial(m){return catModelo(m)!=='Patrimônio'}
function modelosMat(){return (D.modelos||[]).filter(isMaterial)}
async function carregarMat(){try{matSaldos=await loadTable('materiais_saldos','tipo',true)}catch(e){matSaldos=[];msg('matMainMsg','Erro ao carregar saldos: '+e.message,'bad')}try{matMovs=await loadTable('materiais_movimentos','created_at',false)}catch(e){matMovs=[]}}
function optProduto(){let html='<option value="">Selecione material</option>'+modelosMat().map(m=>'<option value="'+H(m.id)+'">'+H(catModelo(m)+' • '+m.tipo+' '+(m.marca||'')+' '+m.modelo+' • '+unidadeModelo(m))+'</option>').join('');['matMainProduto','matMainProdutoS'].forEach(id=>{if(E(id))E(id).innerHTML=html});if(E('matMainTec'))E('matMainTec').innerHTML='<option value="">Técnico</option>'+(D.tecnicos||[]).map(t=>'<option>'+H(t.nome)+'</option>').join('')}
function getM(id){let v=E(id)&&E(id).value;return modelosMat().find(m=>String(m.id)===String(v))}
function findSaldo(m,local,tec){let c=catModelo(m),u=unidadeModelo(m);return matSaldos.find(s=>s.tipo===m.tipo&&(s.marca||'')===(m.marca||'')&&s.modelo===m.modelo&&s.categoria===c&&s.unidade_saida===u&&s.local===local&&((s.tecnico||'')===(tec||'')))}
async function salvarSaldo(m,local,tec,delta){let s=findSaldo(m,local,tec);if(s){let novo=num(s.quantidade)+delta;let r=await db().from('materiais_saldos').update({quantidade:novo,updated_at:new Date().toISOString()}).eq('id',s.id).select().single();if(r.error)throw r.error;Object.assign(s,r.data);return s}let row={modelo_id:m.id,tipo:m.tipo,marca:m.marca||null,modelo:m.modelo,categoria:catModelo(m),unidade_saida:unidadeModelo(m),local:local,tecnico:tec||null,quantidade:delta,qtd_interna:num(m.qtd_interna)||1};let r=await db().from('materiais_saldos').insert(row).select().single();if(r.error)throw r.error;matSaldos.push(r.data);return r.data}
async function salvarMov(m,qtd,origem,destino,tec,obs){let row={modelo_id:m.id,tipo:m.tipo,marca:m.marca||null,modelo:m.modelo,categoria:catModelo(m),unidade_saida:unidadeModelo(m),quantidade:qtd,origem:origem,destino:destino,tecnico:tec||null,motivo:'Movimentação de material',obs:obs||'',responsavel:''};let r=await db().from('materiais_movimentos').insert(row).select().single();if(r.error)throw r.error;matMovs.unshift(r.data)}
async function entradaMat(){try{let m=getM('matMainProduto'),q=num(E('matMainQtd').value);if(!m){msg('matMainMsg','Selecione o material.','bad');return}if(!q||q<=0){msg('matMainMsg','Informe a quantidade.','bad');return}if(catModelo(m)==='Material fechado'&&!Number.isInteger(q)){msg('matMainMsg','Material fechado sai/entra somente em quantidade inteira.','bad');return}await salvarSaldo(m,'Estoque central','',q);await salvarMov(m,q,'Entrada','Estoque central','',E('matMainObs').value);E('matMainQtd').value='';E('matMainObs').value='';renderMateriais();msg('matMainMsg','Entrada registrada: '+q+' '+unidadeModelo(m)+'.','ok')}catch(e){msg('matMainMsg','Erro: '+e.message,'bad')}}
async function saidaMat(){try{let m=getM('matMainProdutoS'),q=num(E('matMainQtdS').value),tec=E('matMainTec').value;if(!m){msg('matMainMsgS','Selecione o material.','bad');return}if(!tec){msg('matMainMsgS','Selecione o técnico.','bad');return}if(!q||q<=0){msg('matMainMsgS','Informe a quantidade.','bad');return}if(catModelo(m)==='Material fechado'&&!Number.isInteger(q)){msg('matMainMsgS','Material fechado sai somente em quantidade inteira.','bad');return}let central=findSaldo(m,'Estoque central','');if(!central||num(central.quantidade)<q){msg('matMainMsgS','Saldo insuficiente no estoque central.','bad');return}await salvarSaldo(m,'Estoque central','',-q);await salvarSaldo(m,'Técnico',tec,q);await salvarMov(m,q,'Estoque central','Técnico',tec,E('matMainObsS').value);E('matMainQtdS').value='';E('matMainObsS').value='';renderMateriais();msg('matMainMsgS','Saída registrada para '+tec+': '+q+' '+unidadeModelo(m)+'.','ok')}catch(e){msg('matMainMsgS','Erro: '+e.message,'bad')}}
function renderMateriais(){if(!E('matMainSaldoT'))return;optProduto();let f=(E('matMainBusca')&&E('matMainBusca').value||'').toLowerCase();let saldos=matSaldos.filter(s=>!f||Object.values(s).join(' ').toLowerCase().includes(f));E('matMainKpis').innerHTML='<div class="kpi"><small>Registros</small><b>'+saldos.length+'</b></div><div class="kpi"><small>Consumo</small><b>'+saldos.filter(s=>s.categoria==='Consumo').length+'</b></div><div class="kpi"><small>Fechados</small><b>'+saldos.filter(s=>s.categoria==='Material fechado').length+'</b></div><div class="kpi"><small>Com técnicos</small><b>'+saldos.filter(s=>s.tecnico).length+'</b></div>';E('matMainSaldoT').innerHTML=saldos.map(s=>'<tr><td>'+H(s.categoria)+'</td><td>'+H(s.tipo+' '+(s.marca||'')+' '+s.modelo)+'</td><td>'+H(s.unidade_saida)+'</td><td>'+H(s.local)+'</td><td>'+H(s.tecnico||'-')+'</td><td><b>'+H(s.quantidade)+'</b></td><td>'+H(s.categoria==='Material fechado'?'Sai somente fechado':'Pode sair por quantidade')+'</td></tr>').join('')||'<tr><td colspan="7">Sem saldo.</td></tr>';E('matMainMovT').innerHTML=matMovs.slice(0,120).map(m=>'<tr><td>'+H(m.created_at?new Date(m.created_at).toLocaleString('pt-BR'):'')+'</td><td>'+H(m.tipo+' '+(m.marca||'')+' '+m.modelo)+'</td><td>'+H(m.quantidade+' '+m.unidade_saida)+'</td><td>'+H(m.origem||'-')+'</td><td>'+H(m.destino||'-')+'</td><td>'+H(m.tecnico||'-')+'</td><td>'+H(m.obs||'')+'</td></tr>').join('')||'<tr><td colspan="7">Sem histórico.</td></tr>'}
function bindMat(){if(E('matMainEntrada'))E('matMainEntrada').onclick=entradaMat;if(E('matMainSaida'))E('matMainSaida').onclick=saidaMat;if(E('matMainBusca'))E('matMainBusca').oninput=renderMateriais;optProduto()}
async function abrirMat(){bindMat();await carregarMat();renderMateriais()}
const pgOld=window.pg;window.pg=function(p){pgOld(p);if(p==='materiaisMain')setTimeout(abrirMat,100)};
const renderOld=window.render;window.render=function(){renderOld();bindMat();if(E('p-materiaisMain')&&E('p-materiaisMain').classList.contains('on'))renderMateriais()};
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{bindMat();carregarMat().then(renderMateriais)},1200));
})();