(function(){
let matSaldos=[],matMovs=[];
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function num(v){return Number(String(v||'').replace(',','.'))||0}
function msg(id,t,c){let el=E(id);if(el){el.textContent=t;el.className='msg '+(c||'')}}
function textoModelo(m){return ((m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||'')).toLowerCase()}
function catModelo(m){let c=String(m.categoria_estoque||m.categoria||m.controle||'').toLowerCase();let txt=textoModelo(m);if(/drop|bobina|cabo de rede|cat5|cat6|internet/.test(txt)||c.includes('fechado')||c.includes('pacote'))return 'Material fechado';if(/rj45|rj 45|conector|conectores|adaptador|abraçadeira|abracadeira|bucha|parafuso|fita|cordão|cordao|patch cord|pigtail|pig tail/.test(txt)||c.includes('quant')||c.includes('consumo'))return 'Consumo';if(c.includes('patrim')||c.includes('unit'))return 'Patrimônio';return 'Consumo'}
function unidadeModelo(m){let txt=textoModelo(m);if(m.unidade_saida)return m.unidade_saida;if(m.unidade)return m.unidade;if(catModelo(m)==='Material fechado'){if(/cabo de rede|cat5|cat6|internet/.test(txt))return 'Caixa';return 'Bobina'}return 'Unidade'}
function isMaterial(m){return catModelo(m)!=='Patrimônio'}
function modelosMat(){return (D.modelos||[]).filter(isMaterial)}
function localOpId(){try{return typeof opId==='function'?opId():crypto.randomUUID()}catch(e){return String(Date.now())+'-'+Math.random().toString(16).slice(2)}}
async function rpcMat(name,params){const r=await db().rpc(name,params);if(r.error)throw r.error;return Array.isArray(r.data)?r.data[0]:r.data}
async function carregarMat(){try{matSaldos=await loadTable('materiais_saldos','tipo',true)}catch(e){matSaldos=[];msg('matMainMsg','Erro ao carregar saldos: '+e.message,'bad')}try{matMovs=await loadTable('materiais_movimentos','created_at',false)}catch(e){matMovs=[]}}
function optProduto(){let html='<option value="">Selecione material</option>'+modelosMat().map(m=>'<option value="'+H(m.id)+'">'+H(catModelo(m)+' • '+m.tipo+' '+(m.marca||'')+' '+m.modelo+' • '+unidadeModelo(m))+'</option>').join('');['matMainProduto','matMainProdutoS','matMainProdutoC'].forEach(id=>{if(E(id))E(id).innerHTML=html});let tecHtml='<option value="">Técnico</option>'+(D.tecnicos||[]).map(t=>'<option>'+H(t.nome)+'</option>').join('');['matMainTec','matMainTecC'].forEach(id=>{if(E(id))E(id).innerHTML=tecHtml})}
function getM(id){let v=E(id)&&E(id).value;return modelosMat().find(m=>String(m.id)===String(v))}
function findSaldo(m,local,tec){let c=catModelo(m),u=unidadeModelo(m);return matSaldos.find(s=>s.tipo===m.tipo&&(s.marca||'')===(m.marca||'')&&s.modelo===m.modelo&&s.categoria===c&&s.unidade_saida===u&&s.local===local&&((s.tecnico||'')===(tec||'')))}
function regraInteira(m,q,id){if(catModelo(m)==='Material fechado'&&!Number.isInteger(q)){msg(id,'Material fechado sai/entra somente em quantidade inteira.','bad');return false}return true}
async function entradaMat(){try{let m=getM('matMainProduto'),q=num(E('matMainQtd').value);if(!m){msg('matMainMsg','Selecione o material.','bad');return}if(!q||q<=0){msg('matMainMsg','Informe a quantidade.','bad');return}if(!regraInteira(m,q,'matMainMsg'))return;await rpcMat('rpc_entrada_material',{p_modelo_id:m.id,p_quantidade:q,p_observacao:E('matMainObs').value,p_client_operation_id:localOpId()});E('matMainQtd').value='';E('matMainObs').value='';await carregarMat();renderMateriais();msg('matMainMsg','Entrada registrada: '+q+' '+unidadeModelo(m)+'.','ok')}catch(e){msg('matMainMsg','Erro: '+e.message,'bad')}}
async function saidaMat(){try{let m=getM('matMainProdutoS'),q=num(E('matMainQtdS').value),tec=E('matMainTec').value;if(!m){msg('matMainMsgS','Selecione o material.','bad');return}if(!tec){msg('matMainMsgS','Selecione o técnico.','bad');return}if(!q||q<=0){msg('matMainMsgS','Informe a quantidade.','bad');return}if(!regraInteira(m,q,'matMainMsgS'))return;let central=findSaldo(m,'Estoque central','');if(!central||num(central.quantidade)<q){msg('matMainMsgS','Saldo insuficiente no estoque central.','bad');return}await rpcMat('rpc_saida_material_tecnico',{p_modelo_id:m.id,p_quantidade:q,p_tecnico:tec,p_observacao:E('matMainObsS').value,p_client_operation_id:localOpId()});E('matMainQtdS').value='';E('matMainObsS').value='';await carregarMat();renderMateriais();msg('matMainMsgS','Saída registrada para '+tec+': '+q+' '+unidadeModelo(m)+'.','ok')}catch(e){msg('matMainMsgS','Erro: '+e.message,'bad')}}
async function consumoMat(){try{let m=getM('matMainProdutoC'),q=num(E('matMainQtdC').value),tec=E('matMainTecC').value,obs=(E('matMainObsC').value||'').trim(),ref=(E('matMainRefC')&&E('matMainRefC').value||'').trim();if(!m){msg('matMainMsgC','Selecione o material.','bad');return}if(!tec){msg('matMainMsgC','Selecione o técnico.','bad');return}if(!q||q<=0){msg('matMainMsgC','Informe a quantidade usada.','bad');return}if(!regraInteira(m,q,'matMainMsgC'))return;let saldoTec=findSaldo(m,'Técnico',tec);if(!saldoTec||num(saldoTec.quantidade)<q){msg('matMainMsgC','Saldo insuficiente com o técnico. Ele possui '+(saldoTec?saldoTec.quantidade:0)+' '+unidadeModelo(m)+'.','bad');return}let obsFinal=[ref?('Ref: '+ref):'',obs].filter(Boolean).join(' | ');await rpcMat('rpc_consumo_material_tecnico',{p_modelo_id:m.id,p_quantidade:q,p_tecnico:tec,p_observacao:obsFinal,p_client_operation_id:localOpId()});E('matMainQtdC').value='';E('matMainObsC').value='';if(E('matMainRefC'))E('matMainRefC').value='';await carregarMat();renderMateriais();msg('matMainMsgC','Baixa registrada: '+q+' '+unidadeModelo(m)+' usado(s) por '+tec+'.','ok')}catch(e){msg('matMainMsgC','Erro: '+e.message,'bad')}}
function ensureConsumoBox(){if(E('matConsumoBox')||!E('p-materiaisMain'))return;let grid=document.querySelector('#p-materiaisMain .grid');if(!grid)return;grid.insertAdjacentHTML('afterend','<div class="card" id="matConsumoBox"><h2>Baixa por uso do técnico</h2><p class="small">Use quando o técnico consumiu material em instalação/suporte. Exemplo: usou 10 conectores no dia.</p><div class="grid4"><select id="matMainProdutoC"></select><select id="matMainTecC"></select><input id="matMainQtdC" type="number" min="1" placeholder="Quantidade usada"><input id="matMainRefC" placeholder="Cliente/OS opcional"></div><textarea id="matMainObsC" placeholder="Observação. Ex: usado em 3 instalações no dia"></textarea><button id="matMainConsumo" class="bad">Dar baixa por uso</button><div id="matMainMsgC" class="msg"></div></div>')}
function renderMateriais(){if(!E('matMainSaldoT'))return;ensureConsumoBox();optProduto();let f=(E('matMainBusca')&&E('matMainBusca').value||'').toLowerCase();let saldos=matSaldos.filter(s=>!f||Object.values(s).join(' ').toLowerCase().includes(f));E('matMainKpis').innerHTML='<div class="kpi"><small>Registros</small><b>'+saldos.length+'</b></div><div class="kpi"><small>Consumo</small><b>'+saldos.filter(s=>s.categoria==='Consumo').length+'</b></div><div class="kpi"><small>Fechados</small><b>'+saldos.filter(s=>s.categoria==='Material fechado').length+'</b></div><div class="kpi"><small>Com técnicos</small><b>'+saldos.filter(s=>s.tecnico&&num(s.quantidade)>0).length+'</b></div>';E('matMainSaldoT').innerHTML=saldos.map(s=>'<tr><td>'+H(s.categoria)+'</td><td>'+H(s.tipo+' '+(s.marca||'')+' '+s.modelo)+'</td><td>'+H(s.unidade_saida)+'</td><td>'+H(s.local)+'</td><td>'+H(s.tecnico||'-')+'</td><td><b>'+H(s.quantidade)+'</b></td><td>'+H(s.categoria==='Material fechado'?'Sai somente fechado':'Pode sair por quantidade')+'</td></tr>').join('')||'<tr><td colspan="7">Sem saldo.</td></tr>';E('matMainMovT').innerHTML=matMovs.slice(0,120).map(m=>'<tr><td>'+H(m.created_at?new Date(m.created_at).toLocaleString('pt-BR'):'')+'</td><td>'+H(m.tipo+' '+(m.marca||'')+' '+m.modelo)+'</td><td>'+H(m.quantidade+' '+m.unidade_saida)+'</td><td>'+H(m.origem||'-')+'</td><td>'+H(m.destino||'-')+'</td><td>'+H(m.tecnico||'-')+'</td><td>'+H((m.motivo?m.motivo+' | ':'')+(m.obs||''))+'</td></tr>').join('')||'<tr><td colspan="7">Sem histórico.</td></tr>';bindMat()}
function bindMat(){ensureConsumoBox();if(E('matMainEntrada'))E('matMainEntrada').onclick=entradaMat;if(E('matMainSaida'))E('matMainSaida').onclick=saidaMat;if(E('matMainConsumo'))E('matMainConsumo').onclick=consumoMat;if(E('matMainBusca'))E('matMainBusca').oninput=renderMateriais;optProduto()}
async function abrirMat(){bindMat();await carregarMat();renderMateriais()}
const pgOld=window.pg;window.pg=function(p){pgOld(p);if(p==='materiaisMain')setTimeout(abrirMat,100)};
const renderOld=window.render;window.render=function(){renderOld();bindMat();if(E('p-materiaisMain')&&E('p-materiaisMain').classList.contains('on'))renderMateriais()};
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{bindMat();carregarMat().then(renderMateriais)},1200));
})();