(function(){
let matsRapida=[], movsRapida=[];
function E(id){return document.getElementById(id)}
function X(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function normal(v){try{return N(v)}catch(e){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}}
function hojeISO(){return new Date().toISOString().slice(0,10)}
function tecEq(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function cliEq(e){return e.clienteAtual||e.cliente_atual||''}
function osEq(e){return e.osAtual||e.os_atual||''}
function nomeEq(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function money(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
async function loadExtra(){try{matsRapida=await loadTable('materiais_saldos','tipo',true)}catch(e){matsRapida=[]}try{movsRapida=await loadTable('movimentos','data',false)}catch(e){movsRapida=[]}}
function ensureCss(){if(E('opRapidaCss'))return;let s=document.createElement('style');s.id='opRapidaCss';s.textContent='.orHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:#fff;border-radius:22px;padding:20px;margin-bottom:14px}.orSearch{font-size:18px;padding:15px;border:2px solid #0f4c81}.orGrid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.orActions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.orActions button,.orShortcuts button{width:100%;min-height:48px;text-align:left}.orShortcuts{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.orKpis{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.orKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.orResult{border:1px solid #e5e7eb;border-radius:16px;padding:14px;margin:10px 0;background:#fff}.orWarn{border-left:5px solid #f59e0b}.orDanger{border-left:5px solid #dc2626}@media(max-width:950px){.orGrid,.orShortcuts,.orKpis,.orActions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function ensurePage(){ensureCss();let side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="operacaoRapida"]')){let ref=document.querySelector('[data-p="dash"]')||document.querySelector('[data-p="entrada"]')||side.querySelector('.nav');(ref||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="operacaoRapida">Operação rápida</button>')}let main=document.querySelector('.main');if(main&&!E('p-operacaoRapida')){let ref=E('p-dash')||E('p-entrada');let html='<section id="p-operacaoRapida" class="page"><div class="orHero"><h2>Operação rápida</h2><p>Busca universal, ações automáticas, atalhos, resumo do dia e alertas críticos.</p></div><div class="card"><h2>Busca universal</h2><input id="orBusca" class="orSearch" placeholder="Bipe ou digite MAC, SN, código, patrimônio, técnico, cliente, OS, modelo ou material"><div id="orBuscaMsg" class="msg">Digite para pesquisar.</div><div id="orResultado"></div></div><div class="card"><h2>Atalhos dos 10 fluxos mais usados</h2><div class="orShortcuts" id="orAtalhos"></div></div><div class="orGrid"><div class="card"><h2>Resumo do dia</h2><div class="orKpis" id="orResumo"></div></div><div class="card"><h2>Alertas críticos</h2><div id="orAlertas"></div></div></div></section>';if(ref)ref.insertAdjacentHTML('afterend',html);else main.insertAdjacentHTML('beforeend',html)}bindNav();bindBusca();renderAtalhos();}
function bindNav(){document.querySelectorAll('.nav').forEach(b=>{if(b.dataset.p==='operacaoRapida')b.onclick=function(){pg('operacaoRapida')}})}
function txtEq(e){return [e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tecEq(e),cliEq(e),osEq(e),e.motivoAtual,e.motivo_atual].join(' ')}
function txtMat(m){return [m.tipo,m.marca,m.modelo,m.categoria,m.unidade_saida,m.local,m.tecnico,m.quantidade].join(' ')}
function match(q,text){return normal(text).includes(normal(q))}
function histEq(id){return (D.movs||movsRapida||[]).filter(m=>m.equipamentoId===id||m.equipamento_id===id).slice(0,5)}
function statusClass(s){s=String(s||'').toLowerCase();if(/perd|inutil|descarte|quebrado/.test(s))return 'bad';if(/estoque|instalado|cliente/.test(s))return 'ok';return ''}
function actionBtn(label,cls,fn){return '<button class="'+(cls||'')+'" onclick="'+fn+'">'+label+'</button>'}
function eqActions(e){let st=String(e.status||'').toLowerCase();let id=e.id;let arr=[];if(/estoque/.test(st)){arr.push(actionBtn('Enviar para técnico','pri',"orIrSaida('"+id+"')"));arr.push(actionBtn('Reservar / saída OS','warn',"orIrSaida('"+id+"')"));}
 else if(/técnico|tecnico|com técnico|com tecnico/.test(st)){arr.push(actionBtn('Instalar no cliente','pri',"orIrInstalar('"+id+"')"));arr.push(actionBtn('Retornar ao estoque','ok',"orIrDevolucao('"+id+"')"));arr.push(actionBtn('Enviar manutenção','warn',"orIrManutencao('"+id+"')"));arr.push(actionBtn('Baixa autorizada','bad',"orIrBaixa('"+id+"')"));}
 else if(/cliente|instalado/.test(st)){arr.push(actionBtn('Retorno do cliente','ok',"orIrDevolucao('"+id+"')"));arr.push(actionBtn('Troca / saída nova','pri',"orIrSaida('"+id+"')"));}
 arr.push(actionBtn('Ver histórico','',"orIrHistorico('"+X(e.mac||e.serial||e.codigo)+"')"));arr.push(actionBtn('Copiar WhatsApp','warn',"orCopiarEq('"+id+"')"));arr.push(actionBtn('Editar equipamento','',"editEq('"+id+"')"));return arr.join('')}
function cardEq(e){let h=histEq(e.id);return '<div class="orResult"><h3>'+X(e.codigo||'')+' • '+X(nomeEq(e))+'</h3><p><span class="status '+statusClass(e.status)+'">'+X(e.status||'-')+'</span> <span class="status">'+X(e.local||'-')+'</span></p><div class="grid4"><div><b>MAC</b><br>'+X(e.mac||'-')+'</div><div><b>SN</b><br>'+X(e.serial||'-')+'</div><div><b>Patrimônio</b><br>'+X(e.patrimonio||'-')+'</div><div><b>Custo</b><br>'+money(e.custo||0)+'</div></div><p><b>Técnico:</b> '+X(tecEq(e)||'-')+'<br><b>Cliente:</b> '+X(cliEq(e)||'-')+'<br><b>OS:</b> '+X(osEq(e)||'-')+'</p><h4>Ações automáticas</h4><div class="orActions">'+eqActions(e)+'</div><h4>Histórico rápido</h4>'+(h.length?h.map(m=>'<div class="small">'+X(m.data||m.created_at||'')+' • '+X(m.tipo||'')+' • '+X(m.statusFinal||m.status_final||'')+'</div>').join(''):'<div class="small">Sem histórico localizado.</div>')+'</div>'}
function cardMat(m){return '<div class="orResult"><h3>'+X((m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||''))+'</h3><p><span class="status ok">'+X(m.categoria||'Material')+'</span> <span class="status">'+X(m.unidade_saida||'Unidade')+'</span></p><div class="grid4"><div><b>Quantidade</b><br>'+X(m.quantidade||0)+'</div><div><b>Local</b><br>'+X(m.local||'-')+'</div><div><b>Técnico</b><br>'+X(m.tecnico||'-')+'</div><div><b>Regra</b><br>'+X((m.categoria||'')==='Material fechado'?'Sai fechado':'Quantidade')+'</div></div><h4>Ações automáticas</h4><div class="orActions">'+actionBtn('Entrada de material','pri',"orIr('materiaisMain')")+actionBtn('Enviar para técnico','ok',"orIr('materiaisMain')")+actionBtn('Baixa por uso','bad',"orIr('materiaisMain')")+actionBtn('Saldo por técnico','',"orIr('tecnico')")+actionBtn('Histórico de material','warn',"orIr('materiaisMain')")+'</div></div>'}
function pesquisar(){let q=(E('orBusca')&&E('orBusca').value||'').trim();let out=E('orResultado'),msg=E('orBuscaMsg');if(!out||!msg)return;if(!q){out.innerHTML='';msg.textContent='Digite para pesquisar.';msg.className='msg';return}let eqs=(D.equipamentos||[]).filter(e=>match(q,txtEq(e))).slice(0,15);let mats=(matsRapida||[]).filter(m=>match(q,txtMat(m))).slice(0,15);msg.textContent='Encontrado(s): '+eqs.length+' equipamento(s) e '+mats.length+' material(is).';msg.className='msg '+((eqs.length||mats.length)?'ok':'bad');out.innerHTML=(eqs.map(cardEq).join('')+mats.map(cardMat).join(''))||'<div class="msg bad">Nenhum item encontrado. Tente parte do MAC, SN, modelo, técnico, cliente ou material.</div>'}
function bindBusca(){let b=E('orBusca');if(b&&!b.dataset.orb){b.dataset.orb=1;b.oninput=pesquisar;b.onkeyup=pesquisar}}
function renderAtalhos(){let box=E('orAtalhos');if(!box)return;let arr=[['Entrada individual','entrada','pri'],['Entrada em lote MAC/SN','entrada','ok'],['Entrada de material','materiaisMain','pri'],['Enviar equipamento para técnico','saida',''],['Enviar material para técnico','materiaisMain',''],['Baixa por uso material','materiaisMain','bad'],['Instalar no cliente','saida','pri'],['Retorno/devolução','devolucao','ok'],['Baixa autorizada/descarte','devolucao','bad'],['Histórico','historico','warn']];box.innerHTML=arr.map(a=>'<button class="'+a[2]+'" onclick="orIr(\''+a[1]+'\')">'+a[0]+'</button>').join('')}
function isToday(d){return String(d||'').slice(0,10)===hojeISO()||String(d||'').includes(new Date().toLocaleDateString('pt-BR'))}
function renderResumo(){let box=E('orResumo');if(!box)return;let movs=(D.movs||movsRapida||[]).filter(m=>isToday(m.data||m.created_at));let count=(re)=>movs.filter(m=>re.test(String(m.tipo||m.motivo||'')+' '+String(m.statusFinal||m.status_final||''))).length;let matUsado=(matsRapida||[]).filter(m=>Number(m.quantidade||0)>0&&m.tecnico).length;box.innerHTML='<div><small>Entradas</small><b>'+count(/entrada/i)+'</b></div><div><small>Saídas</small><b>'+count(/saída|saida/i)+'</b></div><div><small>Instalações</small><b>'+count(/instala/i)+'</b></div><div><small>Retornos</small><b>'+count(/devolu|retorno/i)+'</b></div><div><small>Baixas</small><b>'+count(/baixa|inutil|descarte/i)+'</b></div><div><small>Materiais c/ técnico</small><b>'+matUsado+'</b></div>'}
function renderAlertas(){let box=E('orAlertas');if(!box)return;let alertas=[];(D.equipamentos||[]).filter(e=>/manutenção|manutencao|teste/i.test(e.status||e.local||'')).slice(0,5).forEach(e=>alertas.push(['warn','Manutenção/Teste: '+(e.codigo||'')+' '+nomeEq(e)]));(D.equipamentos||[]).filter(e=>/descarte|perdido|inutil/i.test(e.status||'')).slice(0,5).forEach(e=>alertas.push(['danger','Atenção: '+(e.codigo||'')+' com status '+(e.status||'')]));(matsRapida||[]).filter(m=>!m.tecnico&&Number(m.quantidade||0)<=0).slice(0,5).forEach(m=>alertas.push(['warn','Material sem saldo: '+m.tipo+' '+(m.modelo||'')]));let comTec=(D.equipamentos||[]).filter(e=>/técnico|tecnico|com técnico|com tecnico/i.test(e.status||''));if(comTec.length>0)alertas.push(['warn',comTec.length+' equipamento(s) em posse de técnicos. Conferir pendências.']);box.innerHTML=alertas.slice(0,10).map(a=>'<div class="msg or'+(a[0]==='danger'?'Danger':'Warn')+'">'+X(a[1])+'</div>').join('')||'<div class="msg ok">Sem alerta crítico no momento.</div>'}
window.orIr=function(p){pg(p)};
window.orIrSaida=function(id){pg('saida');setTimeout(()=>{let e=(D.equipamentos||[]).find(x=>x.id===id);if(E('q')&&e){E('q').value=e.mac||e.serial||e.codigo;if(typeof choose==='function')choose(id)}},150)};
window.orIrInstalar=function(id){window.orIrSaida(id)};
window.orIrDevolucao=function(id){pg('devolucao');setTimeout(()=>{let e=(D.equipamentos||[]).find(x=>x.id===id);if(E('dq')&&e){E('dq').value=e.mac||e.serial||e.codigo;if(typeof chooseD==='function')chooseD(id)}},150)};
window.orIrManutencao=function(id){pg('manut');setTimeout(()=>{if(E('manEq'))E('manEq').value=id},150)};
window.orIrBaixa=function(id){window.orIrDevolucao(id)};
window.orIrHistorico=function(q){pg('historico');setTimeout(()=>{if(E('histFilter')){E('histFilter').value=q;E('histFilter').dispatchEvent(new Event('input'))}},150)};
window.orCopiarEq=function(id){let e=(D.equipamentos||[]).find(x=>x.id===id);if(!e)return;let txt='Equipamento: '+(e.codigo||'')+'\nModelo: '+nomeEq(e)+'\nMAC: '+(e.mac||'-')+'\nSN: '+(e.serial||'-')+'\nStatus: '+(e.status||'-')+'\nTécnico: '+(tecEq(e)||'-')+'\nCliente: '+(cliEq(e)||'-');navigator.clipboard.writeText(txt)};
async function renderOR(){ensurePage();await loadExtra();renderAtalhos();renderResumo();renderAlertas();pesquisar()}
function boot(){ensurePage();loadExtra().then(()=>{renderAtalhos();renderResumo();renderAlertas();})}
const pgBase=window.pg;window.pg=function(p){ensurePage();pgBase(p);if(p==='operacaoRapida')setTimeout(()=>{renderOR();if(E('orBusca'))E('orBusca').focus()},150)};
const renderBase=window.render;window.render=function(){renderBase();if(E('p-operacaoRapida')&&E('p-operacaoRapida').classList.contains('on'))renderOR()};
document.addEventListener('DOMContentLoaded',()=>{setTimeout(boot,1000);setTimeout(boot,4000);setTimeout(boot,9000)});
})();