(function(){
let mats=[],matMovs=[],cartEq=[],cartMat=[];
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function K(v){try{return N(v)}catch(e){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}}
function num(v){return Number(String(v||'').replace(',','.'))||0}
function eqs(){return (window.D&&D.equipamentos)||[]}
function tecs(){return (window.D&&D.tecnicos)||[]}
function modelos(){return (window.D&&D.modelos)||[]}
function tecEq(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function cliEq(e){return e.clienteAtual||e.cliente_atual||''}
function osEq(e){return e.osAtual||e.os_atual||''}
function nomeEq(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function st(e){return String(e.status||'')}
function isCentral(e){return /estoque|reservado/i.test(st(e))&&!/cliente|instalado|técnico|tecnico|manut|perdido|inutil/i.test(st(e))}
function isComTec(e){return /técnico|tecnico|com técnico|com tecnico/i.test(st(e))||tecEq(e)}
function isCliente(e){return /cliente|instalado/i.test(st(e))}
function blocked(e){return /perdido|inutil|descarte|manut/i.test(st(e))}
function catModelo(m){let c=String(m.categoria_estoque||m.categoria||m.controle||'').toLowerCase(),txt=[m.tipo,m.marca,m.modelo].join(' ').toLowerCase();if(/drop|bobina|cabo de rede|cat5|cat6|internet/.test(txt)||c.includes('fechado')||c.includes('pacote'))return 'Material fechado';if(c.includes('patrim')||c.includes('unit'))return 'Patrimônio';return 'Consumo'}
function unidadeModelo(m){let txt=[m.tipo,m.marca,m.modelo].join(' ').toLowerCase();if(m.unidade_saida)return m.unidade_saida;if(m.unidade)return m.unidade;if(catModelo(m)==='Material fechado')return /cat5|cat6|cabo de rede|internet/.test(txt)?'Caixa':'Bobina';return 'Unidade'}
function matName(m){return [m.tipo,m.marca,m.modelo].filter(Boolean).join(' ')}
function css(){if(E('orCoreCss'))return;let s=document.createElement('style');s.id='orCoreCss';s.textContent=`.orCoreHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:#fff;border-radius:22px;padding:20px;margin-bottom:14px}.orCoreTop{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.orCoreSearch{font-size:18px;padding:15px;border:2px solid #0f4c81}.orCoreActions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.orCoreActions button,.orCoreShort button{width:100%;min-height:44px;text-align:left}.orCoreResult{border:1px solid #e5e7eb;border-radius:16px;padding:14px;margin:10px 0;background:#fff}.orCoreCartItem{border:1px solid #e5e7eb;border-radius:12px;padding:9px;margin:7px 0;background:#f8fafc}.orCoreKpis{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.orCoreKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.orCoreShort{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.orCoreGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.orMuted{opacity:.55}.orLock{border-left:5px solid #f59e0b}.orDanger{border-left:5px solid #dc2626}@media(max-width:1000px){.orCoreTop,.orCoreActions,.orCoreShort,.orCoreGrid,.orCoreKpis{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function loadExtra(){try{mats=await loadTable('materiais_saldos','tipo',true)}catch(e){mats=[]}try{matMovs=await loadTable('materiais_movimentos','created_at',false)}catch(e){matMovs=[]}}
function ensurePage(){css();let main=document.querySelector('.main');if(!main)return;let sec=E('p-operacaoRapida');if(!sec){let ref=E('p-dash')||main.firstElementChild;ref.insertAdjacentHTML('beforebegin','<section id="p-operacaoRapida" class="page"></section>');sec=E('p-operacaoRapida')}sec.innerHTML=`<div class="orCoreHero"><h2>Operação rápida</h2><p>Painel principal para bipar, consultar, enviar para técnico e evitar fluxo errado.</p></div><div class="orCoreTop"><div class="card"><h2>Busca universal</h2><input id="orCoreBusca" class="orCoreSearch" placeholder="Bipe ou digite MAC, SN, EQP, patrimônio, técnico, cliente, OS, modelo ou material"><div id="orCoreMsg" class="msg">Digite para pesquisar.</div><div id="orCoreResultado"></div></div><div class="card"><h2>Carrinho de saída para técnico</h2><div class="grid"><select id="orCoreTec"></select><input id="orCoreOS" placeholder="OS/observação opcional"></div><p class="small">Use para bipar vários equipamentos e materiais antes de confirmar a saída.</p><div id="orCoreCart"></div><button class="pri" id="orCoreConfirmar">Confirmar saída para técnico</button><button class="warn" id="orCoreCopiar">Copiar WhatsApp</button><button class="bad" id="orCoreLimpar">Limpar carrinho</button><div id="orCoreCartMsg" class="msg">Carrinho vazio.</div></div></div><div class="card"><h2>Atalhos operacionais</h2><div class="orCoreShort"><button class="pri" onclick="pg('entrada')">Entrada individual</button><button onclick="pg('entrada')">Entrada em lote</button><button onclick="pg('materiaisMain')">Materiais</button><button onclick="pg('devolucao')">Devolução</button><button onclick="pg('relatorios')">Relatórios</button></div></div><div class="orCoreGrid"><div class="card"><h2>Resumo rápido</h2><div class="orCoreKpis" id="orCoreResumo"></div></div><div class="card"><h2>Alertas críticos</h2><div id="orCoreAlertas"></div></div></div>`;bind();fillTec();renderCart();renderResumo();renderAlertas()}
function fillTec(){let s=E('orCoreTec');if(!s)return;let old=s.value;let arr=[...new Set(tecs().map(t=>t.nome).concat(eqs().map(tecEq)).filter(Boolean))].sort();s.innerHTML='<option value="">Selecione o técnico</option>'+arr.map(n=>'<option>'+H(n)+'</option>').join('');if(arr.includes(old))s.value=old}
function bind(){let b=E('orCoreBusca');if(b&&!b.dataset.b){b.dataset.b=1;b.oninput=pesquisar;b.onkeyup=e=>{if(e.key==='Enter')autoAddScan()}}if(E('orCoreConfirmar'))E('orCoreConfirmar').onclick=confirmarSaida;if(E('orCoreCopiar'))E('orCoreCopiar').onclick=()=>copyMsg(true);if(E('orCoreLimpar'))E('orCoreLimpar').onclick=()=>{cartEq=[];cartMat=[];renderCart();msgCart('Carrinho limpo.','warn')}}
function textEq(e){return [e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tecEq(e),cliEq(e),osEq(e),e.motivoAtual,e.motivo_atual].join(' ')}
function textMat(m){return [m.tipo,m.marca,m.modelo,m.categoria,m.unidade_saida,m.local,m.tecnico,m.quantidade].join(' ')}
function match(q,t){return K(t).includes(K(q))}
function exactEq(q){let k=K(q);return eqs().find(e=>K(e.mac)===k||K(e.serial)===k||K(e.codigo)===k||K(e.patrimonio)===k)}
function exactMat(q){let k=K(q);return mats.find(m=>K([m.tipo,m.marca,m.modelo].join(' '))===k||K(m.modelo)===k)}
function statusClass(e){if(blocked(e))return 'bad';if(isCentral(e)||isCliente(e))return 'ok';return 'warn'}
function act(label,cls,js,disabled){return '<button class="'+(cls||'')+(disabled?' orMuted':'')+'" '+(disabled?'disabled':'onclick="'+js+'"')+'>'+label+'</button>'}
function msgSearch(t,c){let m=E('orCoreMsg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
function msgCart(t,c){let m=E('orCoreCartMsg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
function addEq(id){let e=eqs().find(x=>x.id===id);if(!e)return;if(blocked(e)){msgCart('Bloqueado: equipamento em '+e.status+'.','bad');return}if(!isCentral(e)){msgCart('Este equipamento não está disponível no estoque central/reservado. Status atual: '+(e.status||'-')+'.','bad');return}if(cartEq.includes(id)){msgCart('Equipamento já está no carrinho.','warn');return}cartEq.push(id);renderCart();msgCart('Equipamento adicionado ao carrinho.','ok')}
function removeEq(id){cartEq=cartEq.filter(x=>x!==id);renderCart()}
function addMat(id){let m=mats.find(x=>x.id===id);if(!m)return;if(m.tecnico){msgCart('Use apenas saldo do estoque central para enviar material.','bad');return}let q=prompt('Quantidade para enviar ao técnico. Saldo atual: '+m.quantidade+' '+(m.unidade_saida||''),'1');if(q===null)return;q=num(q);if(!q||q<=0){msgCart('Quantidade inválida.','bad');return}if(m.categoria==='Material fechado'&&!Number.isInteger(q)){msgCart('Material fechado sai somente em quantidade inteira.','bad');return}if(q>num(m.quantidade)){msgCart('Saldo insuficiente no estoque central.','bad');return}let ex=cartMat.find(x=>x.id===id);if(ex)ex.qtd+=q;else cartMat.push({id,qtd:q});renderCart();msgCart('Material adicionado ao carrinho.','ok')}
function removeMat(id){cartMat=cartMat.filter(x=>x.id!==id);renderCart()}
function cardEq(e){let info=isCentral(e)?'Disponível para saída':isComTec(e)?'Em posse de técnico':isCliente(e)?'Instalado em cliente':blocked(e)?'Bloqueado para saída':'Status exige conferência';let actions='';if(isCentral(e)){actions+=act('Adicionar ao carrinho','pri',"orCoreAddEq('"+e.id+"')");actions+=act('Enviar para técnico','ok',"orCoreAddEq('"+e.id+"')");actions+=act('Histórico','',"orCoreHist('"+(e.mac||e.serial||e.codigo)+"')")}else if(isComTec(e)&&!isCliente(e)){actions+=act('Instalar no cliente','pri',"orCoreInstalar('"+e.id+"')");actions+=act('Retornar/devolver','ok',"orCoreDevolver('"+e.id+"')");actions+=act('Manutenção','warn',"orCoreManut('"+e.id+"')")}else if(isCliente(e)){actions+=act('Retorno do cliente','ok',"orCoreDevolver('"+e.id+"')");actions+=act('Troca: enviar novo','pri',"pg('saida')");actions+=act('Histórico','',"orCoreHist('"+(e.mac||e.serial||e.codigo)+"')")}else{actions+=act('Adicionar ao carrinho','pri','',true);actions+=act('Resolver pela devolução/manutenção','warn',"pg('devolucao')");actions+=act('Histórico','',"orCoreHist('"+(e.mac||e.serial||e.codigo)+"')")}
let lock=!isCentral(e)&&!isComTec(e)&&!isCliente(e)||blocked(e);return '<div class="orCoreResult '+(lock?'orLock':'')+'"><h3>'+H(e.codigo||'')+' • '+H(nomeEq(e))+'</h3><p><span class="status '+statusClass(e)+'">'+H(e.status||'-')+'</span> <span class="status">'+H(info)+'</span></p><div class="grid4"><div><b>MAC</b><br>'+H(e.mac||'-')+'</div><div><b>SN</b><br>'+H(e.serial||'-')+'</div><div><b>Patrimônio</b><br>'+H(e.patrimonio||'-')+'</div><div><b>Técnico</b><br>'+H(tecEq(e)||'-')+'</div></div><p><b>Cliente:</b> '+H(cliEq(e)||'-')+'<br><b>OS:</b> '+H(osEq(e)||'-')+'</p><div class="orCoreActions">'+actions+'</div></div>'}
function cardMat(m){let central=!m.tecnico&&/estoque central/i.test(m.local||'');return '<div class="orCoreResult"><h3>'+H(matName(m))+'</h3><p><span class="status ok">'+H(m.categoria||'Material')+'</span> <span class="status">'+H(m.local||'-')+'</span></p><div class="grid4"><div><b>Saldo</b><br>'+H(m.quantidade||0)+'</div><div><b>Unidade</b><br>'+H(m.unidade_saida||'-')+'</div><div><b>Técnico</b><br>'+H(m.tecnico||'-')+'</div><div><b>Regra</b><br>'+H(m.categoria==='Material fechado'?'Somente fechado':'Quantidade')+'</div></div><div class="orCoreActions">'+act('Adicionar material ao carrinho','pri',"orCoreAddMat('"+m.id+"')",!central)+act('Baixa por uso','bad',"pg('materiaisMain')")+act('Ver materiais','',"pg('materiaisMain')")+'</div></div>'}
function pesquisar(){let q=(E('orCoreBusca')&&E('orCoreBusca').value||'').trim(),out=E('orCoreResultado');if(!out)return;if(!q){out.innerHTML='';msgSearch('Digite para pesquisar.','');return}let le=eqs().filter(e=>match(q,textEq(e))).slice(0,15);let lm=mats.filter(m=>match(q,textMat(m))).slice(0,15);msgSearch('Encontrado(s): '+le.length+' equipamento(s) e '+lm.length+' material(is).',le.length||lm.length?'ok':'bad');out.innerHTML=(le.map(cardEq).join('')+lm.map(cardMat).join(''))||'<div class="msg bad">Nenhum item encontrado.</div>'}
function autoAddScan(){let q=(E('orCoreBusca')&&E('orCoreBusca').value||'').trim();let e=exactEq(q);if(e){addEq(e.id);E('orCoreBusca').value='';pesquisar();return}msgSearch('Item não adicionado automaticamente. Selecione o resultado na tela.','warn')}
function renderCart(){let box=E('orCoreCart');if(!box)return;let html='';cartEq.forEach(id=>{let e=eqs().find(x=>x.id===id);if(e)html+='<div class="orCoreCartItem"><b>'+H(e.codigo)+'</b> • '+H(nomeEq(e))+'<br><small>'+H(e.mac||e.serial||'')+'</small><button class="bad" onclick="orCoreRemoveEq(\''+id+'\')">Remover</button></div>'});cartMat.forEach(x=>{let m=mats.find(s=>s.id===x.id);if(m)html+='<div class="orCoreCartItem"><b>'+H(matName(m))+'</b><br><small>'+H(x.qtd+' '+(m.unidade_saida||''))+'</small><button class="bad" onclick="orCoreRemoveMat(\''+x.id+'\')">Remover</button></div>'});box.innerHTML=html||'<div class="msg">Nenhum item no carrinho. Bipe ou adicione pela busca.</div>'}
function centralSaldoFor(s){return mats.find(x=>x.id===s.id)}
async function salvarSaldo(row,delta,tec){let novo=num(row.quantidade)+delta;if(novo<0)throw Error('Saldo insuficiente para '+matName(row));let r=await db().from('materiais_saldos').update({quantidade:novo,updated_at:new Date().toISOString()}).eq('id',row.id).select().single();if(r.error)throw r.error;Object.assign(row,r.data);return row}
async function addSaldoTec(base,qtd,tec){let ex=mats.find(s=>s.tipo===base.tipo&&(s.marca||'')===(base.marca||'')&&s.modelo===base.modelo&&s.categoria===base.categoria&&s.unidade_saida===base.unidade_saida&&s.local==='Técnico'&&(s.tecnico||'')===tec);if(ex){let r=await db().from('materiais_saldos').update({quantidade:num(ex.quantidade)+qtd,updated_at:new Date().toISOString()}).eq('id',ex.id).select().single();if(r.error)throw r.error;Object.assign(ex,r.data);return ex}let row={modelo_id:base.modelo_id,tipo:base.tipo,marca:base.marca||null,modelo:base.modelo,categoria:base.categoria,unidade_saida:base.unidade_saida,local:'Técnico',tecnico:tec,quantidade:qtd,qtd_interna:base.qtd_interna||1};let r=await db().from('materiais_saldos').insert(row).select().single();if(r.error)throw r.error;mats.push(r.data);return r.data}
async function movMat(base,qtd,tec,obs){let row={modelo_id:base.modelo_id,tipo:base.tipo,marca:base.marca||null,modelo:base.modelo,categoria:base.categoria,unidade_saida:base.unidade_saida,quantidade:qtd,origem:'Estoque central',destino:'Técnico',tecnico:tec,motivo:'Saída rápida para técnico',obs:obs||'',responsavel:''};let r=await db().from('materiais_movimentos').insert(row).select().single();if(r.error)throw r.error;matMovs.unshift(r.data)}
async function confirmarSaida(){try{let tec=E('orCoreTec').value,obs=(E('orCoreOS').value||'').trim();if(!tec){msgCart('Selecione o técnico.','bad');return}if(!cartEq.length&&!cartMat.length){msgCart('Carrinho vazio.','bad');return}for(let id of cartEq){let e=eqs().find(x=>x.id===id);if(!e)continue;if(!isCentral(e))throw Error('Equipamento '+(e.codigo||'')+' não está no estoque central/reservado.');e.status='Com técnico';e.local='Técnico';e.tecnicoAtual=tec;e.clienteAtual='';e.osAtual='';e.motivoAtual='Saída rápida';await upd('equipamentos',e.id,toEq(e));await mov(e,'Saída para técnico',{tec:tec,dest:'Técnico',mot:'Saída rápida',obs:obs})}for(let x of cartMat){let m=centralSaldoFor(x);if(!m)continue;if(num(m.quantidade)<x.qtd)throw Error('Saldo insuficiente para '+matName(m));await salvarSaldo(m,-x.qtd,tec);await addSaldoTec(m,x.qtd,tec);await movMat(m,x.qtd,tec,obs)}let texto=buildWhats(tec);cartEq=[];cartMat=[];await loadAll();await loadExtra();renderCart();renderResumo();renderAlertas();pesquisar();navigator.clipboard.writeText(texto).catch(()=>{});msgCart('Saída confirmada e mensagem copiada para WhatsApp.','ok')}catch(e){msgCart('Erro: '+e.message,'bad')}}
function buildWhats(tec){let linhas=[];linhas.push('📦 SAÍDA DE ESTOQUE');linhas.push('Técnico: '+(tec||E('orCoreTec').value||'-'));linhas.push('Data: '+new Date().toLocaleDateString('pt-BR'));let obs=(E('orCoreOS')&&E('orCoreOS').value||'').trim();if(obs)linhas.push('Obs/OS: '+obs);linhas.push('');linhas.push('EQUIPAMENTOS:');linhas.push(cartEq.map((id,i)=>{let e=eqs().find(x=>x.id===id);return e?(i+1)+'. '+(e.codigo||'')+' | '+nomeEq(e)+' | MAC/SN: '+(e.mac||e.serial||'-'):''}).filter(Boolean).join('\n')||'Sem equipamentos.');linhas.push('');linhas.push('MATERIAIS:');linhas.push(cartMat.map(x=>{let m=mats.find(s=>s.id===x.id);return m?'- '+matName(m)+': '+x.qtd+' '+(m.unidade_saida||''):''}).filter(Boolean).join('\n')||'Sem materiais.');linhas.push('');linhas.push('Favor conferir e confirmar.');return linhas.join('\n')}
function copyMsg(show){let tec=E('orCoreTec')&&E('orCoreTec').value||'';let txt=buildWhats(tec);navigator.clipboard.writeText(txt).then(()=>{if(show)msgCart('Mensagem copiada.','ok')})}
function renderResumo(){let box=E('orCoreResumo');if(!box)return;let movs=(D.movimentos||[]).filter(m=>String(m.data||m.created_at||'').slice(0,10)===new Date().toISOString().slice(0,10));let c=re=>movs.filter(m=>re.test(String(m.tipo||m.motivo||''))).length;box.innerHTML='<div><small>Entradas</small><b>'+c(/entrada/i)+'</b></div><div><small>Saídas</small><b>'+c(/saida|saída/i)+'</b></div><div><small>Instalações</small><b>'+c(/instala/i)+'</b></div><div><small>Retornos</small><b>'+c(/retorno|devolu/i)+'</b></div><div><small>Com técnico</small><b>'+eqs().filter(e=>isComTec(e)&&!isCliente(e)).length+'</b></div>'}
function renderAlertas(){let box=E('orCoreAlertas');if(!box)return;let a=[];eqs().filter(e=>blocked(e)).slice(0,5).forEach(e=>a.push('Bloqueado: '+(e.codigo||'')+' • '+e.status));mats.filter(m=>!m.tecnico&&/estoque central/i.test(m.local||'')&&num(m.quantidade)<=0).slice(0,5).forEach(m=>a.push('Material sem saldo: '+matName(m)));let ct=eqs().filter(e=>isComTec(e)&&!isCliente(e)).length;if(ct)a.push(ct+' equipamento(s) em posse de técnicos.');box.innerHTML=a.map(x=>'<div class="msg warn">'+H(x)+'</div>').join('')||'<div class="msg ok">Sem alerta crítico.</div>'}
window.orCoreAddEq=addEq;window.orCoreRemoveEq=removeEq;window.orCoreAddMat=addMat;window.orCoreRemoveMat=removeMat;
window.orCoreInstalar=function(id){let e=eqs().find(x=>x.id===id);if(!e)return;if(!isComTec(e)||isCentral(e)){msgSearch('Bloqueado: antes de instalar, envie o equipamento para um técnico.','bad');return}pg('saida');setTimeout(()=>{if(E('q')){E('q').value=e.mac||e.serial||e.codigo;if(typeof choose==='function')choose(id)}if(E('movTipo'))E('movTipo').value='Instalação cliente';},150)};
window.orCoreDevolver=function(id){let e=eqs().find(x=>x.id===id);pg('devolucao');setTimeout(()=>{if(E('dq')&&e){E('dq').value=e.mac||e.serial||e.codigo;if(typeof chooseD==='function')chooseD(id)}},150)};
window.orCoreManut=function(id){pg('manut');setTimeout(()=>{if(E('manEq'))E('manEq').value=id},150)};
window.orCoreHist=function(q){pg('historico');setTimeout(()=>{if(E('histFilter')){E('histFilter').value=q;E('histFilter').dispatchEvent(new Event('input'))}},150)};
async function boot(){ensurePage();await loadExtra();fillTec();renderCart();renderResumo();renderAlertas();bind()}
const oldPg=window.pg; if(!window.__orCorePg&&typeof oldPg==='function'){window.__orCorePg=1;window.pg=function(p){oldPg(p);if(p==='operacaoRapida')setTimeout(boot,80)}}
const oldRender=window.render; if(!window.__orCoreRender&&typeof oldRender==='function'){window.__orCoreRender=1;window.render=function(){oldRender();if(E('p-operacaoRapida')&&E('p-operacaoRapida').classList.contains('on'))setTimeout(boot,80)}}
document.addEventListener('DOMContentLoaded',()=>{[600,2000,5000,10000,16000].forEach(t=>setTimeout(boot,t))});
window.operacaoRapidaCoreBoot=boot;
})();