(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function K(v){try{return N(v||'')}catch(e){return String(v||'').toLowerCase().trim()}}
function eqName(x){return ((x.tipo||'')+' '+(x.marca||'')+' '+(x.modelo||'')).trim()}
function find(v){var k=K(v);return (D.equipamentos||[]).find(x=>K(x.codigo)===k||K(x.patrimonio)===k||K(x.mac)===k||K(x.serial)===k)}
function go(p){try{pg(p)}catch(e){}}
var sel=null;
function css(){if(E('p52css'))return;var s=document.createElement('style');s.id='p52css';s.textContent='.instGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.instPrev{background:#f8fafc;border:1px solid #dbe4ef;border-radius:14px;padding:14px;margin:8px 0}.instHead{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:18px;padding:18px;margin-bottom:14px}@media(max-width:950px){.instGrid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function page(){var main=document.querySelector('.main');if(!main||E('p-instalarCliente'))return;main.insertAdjacentHTML('beforeend','<section id="p-instalarCliente" class="page"><div class="instHead"><h2>Instalar no cliente</h2><p>Remove da caixa do técnico e registra o cliente.</p></div><div class="card"><div class="instGrid"><div><h2>Equipamento</h2><input id="instBusca" placeholder="MAC, SN, código ou patrimônio"><div id="instPrev" class="instPrev">Nenhum equipamento selecionado.</div></div><div><h2>Instalação</h2><input id="instCliente" placeholder="Nome do cliente"><select id="instTec"></select><textarea id="instObs" placeholder="Observação opcional"></textarea><button id="instBtn" class="pri">Confirmar instalação</button><div id="instMsg" class="msg"></div></div></div></div></section>')}
function nav(){var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="instalarCliente"]')){var r=document.querySelector('[data-p="devolucao"]')||document.querySelector('[data-p="saida"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="instalarCliente">Instalar no cliente</button>')}document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.p));var op=E('p-operacao');if(op&&!E('instQuick')){var g=op.querySelector('.opGrid');if(g)g.insertAdjacentHTML('afterbegin','<div id="instQuick" class="opBtn" data-go="instalarCliente"><div class="opIcon">🏠</div><b>Instalar no cliente</b><span>Tira da caixa do técnico.</span></div>')}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function techs(){var s=E('instTec');if(!s)return;var old=s.value;var a=[...new Set([...(D.tecnicos||[]).map(t=>t.nome),...(D.equipamentos||[]).map(x=>x.tecnicoAtual)].filter(Boolean))].sort();s.innerHTML='<option value="">Técnico instalador</option>'+a.map(n=>'<option>'+S(n)+'</option>').join('');if([...s.options].some(o=>o.value===old))s.value=old}
function prev(){sel=find(E('instBusca')&&E('instBusca').value);var p=E('instPrev');if(!p)return;if(!sel){p.innerHTML='<b>Equipamento não encontrado.</b>';p.style.background='#fee2e2';return}p.style.background='#f8fafc';p.innerHTML='<b>'+S(sel.codigo)+' - '+S(eqName(sel))+'</b><br><small>MAC/SN: '+S(sel.mac||sel.serial||'-')+'</small><br><small>Status: '+S(sel.status)+' | Técnico: '+S(sel.tecnicoAtual||'-')+'</small>';if(sel.tecnicoAtual&&E('instTec')&&!E('instTec').value)E('instTec').value=sel.tecnicoAtual}
async function ok(){try{if(!sel)prev();if(!sel)return msg('Selecione um equipamento válido.','bad');var cli=(E('instCliente').value||'').trim();var tec=(E('instTec').value||'').trim();if(!cli)return msg('Informe o cliente.','bad');if(!tec)return msg('Informe o técnico.','bad');var obs=(E('instObs').value||'').trim();var r=await db().from('equipamentos').update({status:'Instalado no cliente',local:'Cliente',cliente_atual:cli,tecnico_atual:null,os_atual:null,motivo_atual:'Instalado no cliente'}).eq('id',sel.id).select().single();if(r.error)throw r.error;sel.status='Instalado no cliente';sel.local='Cliente';sel.clienteAtual=cli;sel.tecnicoAtual='';try{await mov(sel,'Instalado no cliente',{tec:tec,dest:'Cliente',cli:cli,mot:'Instalação no cliente',obs:obs})}catch(e){}try{await loadAll()}catch(e){}try{render()}catch(e){}msg('Instalação registrada. Saiu da caixa do técnico e ficou no cliente.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
function msg(t,c){var m=E('instMsg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
function bind(){css();page();nav();techs();var b=E('instBusca');if(b&&!b.dataset.i){b.dataset.i=1;b.oninput=prev;b.onkeydown=function(ev){if(ev.key==='Enter')prev()}}if(E('instBtn'))E('instBtn').onclick=ok}
setInterval(bind,1200);document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,1500));
})();