(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function go(p){try{pg(p)}catch(e){}}
function css(){if(E('p53css'))return;var s=document.createElement('style');s.id='p53css';s.textContent='.cliHead{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:18px;padding:18px;margin-bottom:14px}.cliKpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.cliKpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.cliFilters{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px}@media(max-width:950px){.cliKpi,.cliFilters{grid-template-columns:1fr}}';document.head.appendChild(s)}
function nav(){var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="clientesInstalados"]')){var r=document.querySelector('[data-p="instalarCliente"]')||document.querySelector('[data-p="historico"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="clientesInstalados">Equipamentos no cliente</button>')}document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.p));var op=E('p-operacao');if(op&&!E('cliQuick')){var g=op.querySelector('.opGrid');if(g)g.insertAdjacentHTML('afterbegin','<div id="cliQuick" class="opBtn" data-go="clientesInstalados"><div class="opIcon">🏘️</div><b>Equipamentos no cliente</b><span>Veja o que saiu da caixa do técnico.</span></div>')}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function page(){var main=document.querySelector('.main');if(!main||E('p-clientesInstalados'))return;main.insertAdjacentHTML('beforeend','<section id="p-clientesInstalados" class="page"><div class="cliHead"><h2>Equipamentos instalados no cliente</h2><p>Lista de equipamentos que saíram da caixa do técnico e ficaram vinculados a clientes.</p></div><div class="card"><div class="cliFilters"><input id="cliBusca" placeholder="Buscar por cliente, MAC, SN, código ou modelo"><select id="cliTipo"><option value="">Todos os tipos</option></select><button id="cliReload" class="pri">Atualizar lista</button></div><div id="cliKpis" class="cliKpi"></div><div class="tbl"><table><thead><tr><th>Cliente</th><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th></tr></thead><tbody id="cliTable"></tbody></table></div></div></section>')}
function rows(){return (D.equipamentos||[]).filter(x=>x.status==='Instalado no cliente'||x.local==='Cliente'||x.clienteAtual||x.cliente_atual)}
function fillTipo(){var s=E('cliTipo');if(!s)return;var old=s.value;var tipos=[...new Set(rows().map(x=>x.tipo).filter(Boolean))].sort();s.innerHTML='<option value="">Todos os tipos</option>'+tipos.map(t=>'<option>'+S(t)+'</option>').join('');if([...s.options].some(o=>o.value===old))s.value=old}
function renderCli(){var tb=E('cliTable');if(!tb)return;var q=(E('cliBusca')&&E('cliBusca').value||'').toLowerCase().trim();var tipo=(E('cliTipo')&&E('cliTipo').value||'');var r=rows().filter(x=>!tipo||x.tipo===tipo).filter(x=>!q||[x.clienteAtual,x.cliente_atual,x.codigo,x.mac,x.serial,x.tipo,x.marca,x.modelo].join(' ').toLowerCase().includes(q));var k=E('cliKpis');if(k)k.innerHTML='<div><small>Total no cliente</small><b>'+r.length+'</b></div><div><small>Clientes distintos</small><b>'+new Set(r.map(x=>x.clienteAtual||x.cliente_atual).filter(Boolean)).size+'</b></div><div><small>Tipos</small><b>'+new Set(r.map(x=>x.tipo).filter(Boolean)).size+'</b></div><div><small>Sem cliente</small><b>'+r.filter(x=>!(x.clienteAtual||x.cliente_atual)).length+'</b></div>';tb.innerHTML=r.map(x=>'<tr><td><b>'+S(x.clienteAtual||x.cliente_atual||'-')+'</b></td><td>'+S(x.codigo)+'</td><td>'+S((x.tipo||'')+' '+(x.marca||'')+' '+(x.modelo||''))+'</td><td>'+S(x.mac||x.serial||'-')+'</td><td>'+S(x.status)+'</td><td>'+S(x.local||'-')+'</td></tr>').join('')||'<tr><td colspan="6">Nenhum equipamento instalado em cliente.</td></tr>'}
function bind(){css();page();nav();fillTipo();renderCli();if(E('cliBusca'))E('cliBusca').oninput=renderCli;if(E('cliTipo'))E('cliTipo').onchange=renderCli;if(E('cliReload'))E('cliReload').onclick=async function(){try{await loadAll()}catch(e){}fillTipo();renderCli()}}
setInterval(bind,1500);document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,1800));
})();