(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function money(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
var tecnicos=[],equipamentos=[],materiais=[],sel='',lastErr='';
async function q(tab,order){try{let r=await db().from(tab).select('*').order(order||'created_at',{ascending:true});if(r.error)throw r.error;return r.data||[]}catch(e){lastErr+=' '+tab+': '+e.message+'; ';return []}}
async function loadAllTec(){lastErr='';tecnicos=await q('tecnicos','nome');equipamentos=await q('equipamentos','codigo');materiais=await q('materiais_saldos','tipo');}
function tecnicoEq(e){return e.tecnico_atual||e.tecnicoAtual||e.tecnico||''}
function eqNome(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function nomes(){return [...new Set([...(tecnicos||[]).map(t=>t.nome),...(equipamentos||[]).map(tecnicoEq),...(materiais||[]).map(m=>m.tecnico)].filter(Boolean))].sort()}
function eqs(n){return (equipamentos||[]).filter(e=>tecnicoEq(e)===n && !['Em estoque','Inutilizado','Perdido','Descarte autorizado','Instalado no cliente','Instalado cliente'].includes(e.status||''))}
function mats(n){return (materiais||[]).filter(m=>(m.tecnico||'')===n && Number(m.quantidade||0)!==0)}
function css(){if(E('p66css'))return;var s=document.createElement('style');s.id='p66css';s.textContent='.t66Hero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.t66Grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:14px}.t66Item{display:flex;justify-content:space-between;align-items:center;gap:8px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:10px;margin:8px 0;cursor:pointer}.t66Item.on{outline:3px solid #0f4c8130;border-color:#0f4c81}.t66Kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.t66Kpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}@media(max-width:950px){.t66Grid,.t66Kpi{grid-template-columns:1fr}}';document.head.appendChild(s)}
function cleanup(){document.querySelectorAll('[data-p="tecnicosFull"],[data-p="tecnicos65"]').forEach(x=>x.remove());document.querySelectorAll('.nav').forEach((b,i)=>{if((b.textContent||'').trim()==='Técnicos'&&b.dataset.p!=='tecnicosFix')b.remove()});['p-tecnicosFull','p-tecnicos65'].forEach(id=>{var x=E(id);if(x)x.remove()})}
function nav(){cleanup();var side=document.querySelector('.side');if(!side)return;if(!document.querySelector('[data-p="tecnicosFix"]')){var r=document.querySelector('[data-p="materiais"]')||document.querySelector('[data-p="operacaoEstoque"]')||document.querySelector('[data-p="tecnico"]')||side.lastElementChild;(r||side).insertAdjacentHTML('afterend','<button class="nav" data-p="tecnicosFix">Técnicos</button>')}var b=document.querySelector('[data-p="tecnicosFix"]');if(b)b.onclick=function(ev){ev.preventDefault();openTecFix()}}
function page(){var main=document.querySelector('.main');if(!main)return;if(E('p-tecnicosFix'))return;main.insertAdjacentHTML('beforeend','<section id="p-tecnicosFix" class="page"><div class="t66Hero"><h2>Técnicos</h2><p>Cadastro, lista real de técnicos, equipamentos patrimoniais e materiais em posse.</p></div><div class="t66Grid"><div class="card"><h2>Adicionar técnico</h2><input id="t66Nome" placeholder="Nome do técnico"><button id="t66Add" class="pri">Adicionar técnico</button><div id="t66Msg" class="msg"></div><h2>Técnicos cadastrados</h2><input id="t66Busca" placeholder="Buscar técnico"><button id="t66Reload" class="ok">Atualizar lista</button><div id="t66List"></div></div><div class="card"><h2 id="t66Title">Selecione um técnico</h2><div id="t66Kpis" class="t66Kpi"></div><p><button id="t66View" class="pri">Ver equipamentos e materiais</button><button id="t66Copy" class="warn">Copiar cobrança</button><button id="t66Print" class="bad">Imprimir/PDF</button></p><div id="t66Area"></div></div></div></section>')}
function renderList(){var box=E('t66List');if(!box)return;var f=(E('t66Busca')&&E('t66Busca').value||'').toLowerCase();var arr=nomes().filter(n=>!f||n.toLowerCase().includes(f));box.innerHTML=(lastErr?'<div class="msg bad">Erro ao carregar: '+S(lastErr)+'</div>':'')+(arr.map(n=>{var rec=tecnicos.find(t=>t.nome===n);return '<div class="t66Item '+(sel===n?'on':'')+'"><div data-sel="'+S(n)+'" style="flex:1"><b>'+S(n)+'</b><br><small>'+eqs(n).length+' equipamento(s) • '+mats(n).length+' material(is)</small></div><button class="bad" data-del="'+S(n)+'" data-id="'+S(rec?rec.id:'')+'">Excluir</button></div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>');box.querySelectorAll('[data-sel]').forEach(x=>x.onclick=function(){sel=this.dataset.sel;renderAll(true)});box.querySelectorAll('[data-del]').forEach(x=>x.onclick=function(ev){ev.stopPropagation();delTec(this.dataset.id,this.dataset.del)})}
function renderK(){if(!E('t66Kpis'))return;if(!sel){E('t66Title').textContent='Selecione um técnico';E('t66Kpis').innerHTML='';E('t66Area').innerHTML='';return}var e=eqs(sel),m=mats(sel),val=e.reduce((a,b)=>a+Number(b.custo||0),0);E('t66Title').textContent='Técnico: '+sel;E('t66Kpis').innerHTML='<div><small>Equipamentos</small><b>'+e.length+'</b></div><div><small>Materiais</small><b>'+m.length+'</b></div><div><small>Valor patrimônio</small><b>'+money(val)+'</b></div><div><small>Total técnicos</small><b>'+nomes().length+'</b></div>'}
function tableHtml(){var e=eqs(sel),m=mats(sel);return '<h3>Equipamentos patrimoniais</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Valor</th></tr></thead><tbody>'+(e.map(x=>'<tr><td>'+S(x.codigo)+'</td><td>'+S(eqNome(x))+'</td><td>'+S(x.mac||x.serial||'-')+'</td><td>'+S(x.status||'-')+'</td><td>'+S(x.local||'-')+'</td><td>'+money(x.custo||0)+'</td></tr>').join('')||'<tr><td colspan="6">Sem equipamento patrimonial em posse.</td></tr>')+'</tbody></table></div><h3>Materiais em posse</h3><div class="tbl"><table><thead><tr><th>Categoria</th><th>Material</th><th>Quantidade</th><th>Unidade</th><th>Local</th></tr></thead><tbody>'+(m.map(x=>'<tr><td>'+S(x.categoria)+'</td><td>'+S(x.tipo+' '+(x.marca||'')+' '+x.modelo)+'</td><td><b>'+S(x.quantidade)+'</b></td><td>'+S(x.unidade_saida)+'</td><td>'+S(x.local||'Técnico')+'</td></tr>').join('')||'<tr><td colspan="5">Sem material em posse.</td></tr>')+'</tbody></table></div>'}
function renderAll(show){renderList();renderK();if(show&&sel&&E('t66Area'))E('t66Area').innerHTML=tableHtml()}
function msg(t,c){var m=E('t66Msg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
async function addTec(){try{var nome=(E('t66Nome').value||'').trim();if(!nome)return msg('Informe o nome do técnico.','bad');var r=await db().from('tecnicos').insert({nome:nome,ativo:true}).select().single();if(r.error)throw r.error;E('t66Nome').value='';sel=nome;await loadAllTec();renderAll(true);msg('Técnico adicionado.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
async function delTec(id,nome){try{if(eqs(nome).length||mats(nome).length){alert('Não exclua técnico com equipamento/material em posse. Devolva ou transfira antes.');return}if(!id){alert('Este nome vem de movimentação antiga e não tem cadastro direto para excluir.');return}if(!confirm('Excluir técnico '+nome+'?'))return;var r=await db().from('tecnicos').delete().eq('id',id);if(r.error)throw r.error;if(sel===nome)sel='';await loadAllTec();renderAll(false);msg('Técnico excluído.','ok')}catch(e){msg('Erro ao excluir: '+e.message,'bad')}}
function copiar(){if(!sel)return msg('Selecione um técnico.','bad');var txt='RELATÓRIO DO TÉCNICO\nTécnico: '+sel+'\nEquipamentos: '+eqs(sel).length+'\nMateriais: '+mats(sel).length+'\n\nEQUIPAMENTOS:\n'+(eqs(sel).map(x=>'- '+(x.codigo||'')+' | '+eqNome(x)+' | '+(x.mac||x.serial||'-')+' | '+(x.status||'')).join('\n')||'Sem equipamentos.')+'\n\nMATERIAIS:\n'+(mats(sel).map(x=>'- '+x.tipo+' '+(x.marca||'')+' '+x.modelo+' | '+x.quantidade+' '+x.unidade_saida).join('\n')||'Sem materiais.');navigator.clipboard.writeText(txt).then(()=>msg('Copiado.','ok'))}
function bind(){css();page();nav();if(E('t66Busca'))E('t66Busca').oninput=renderList;if(E('t66Add'))E('t66Add').onclick=addTec;if(E('t66Reload'))E('t66Reload').onclick=async function(){await loadAllTec();renderAll(true);msg('Lista atualizada.','ok')};if(E('t66View'))E('t66View').onclick=function(){if(!sel)return msg('Selecione um técnico.','bad');E('t66Area').innerHTML=tableHtml()};if(E('t66Copy'))E('t66Copy').onclick=copiar;if(E('t66Print'))E('t66Print').onclick=function(){window.print()}}
async function openTecFix(){bind();await loadAllTec();renderAll(true);document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('on'));E('p-tecnicosFix').classList.add('on');var b=document.querySelector('[data-p="tecnicosFix"]');if(b)b.classList.add('on');if(E('title'))E('title').textContent='Técnicos'}
window.openTecnicosFix=openTecFix;window.tecForceReload=openTecFix;
setInterval(function(){nav();cleanup();if(E('p-tecnicosFix')&&E('p-tecnicosFix').classList.contains('on'))loadAllTec().then(()=>renderAll(false))},2500);
document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){bind();loadAllTec().then(()=>renderAll(false))},1500)});
})();