(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function K(v){try{return N(v||'')}catch(e){return String(v||'').toLowerCase().trim()}}
function eqName(x){return ((x.tipo||'')+' '+(x.marca||'')+' '+(x.modelo||'')).trim()}
function findEq(v){var k=K(v);return (D.equipamentos||[]).find(x=>K(x.codigo)===k||K(x.patrimonio)===k||K(x.mac)===k||K(x.serial)===k)}
function go(p){try{pg(p)}catch(e){}}
function css(){if(E('p54css'))return;var s=document.createElement('style');s.id='p54css';s.textContent='.opEstHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.opEstGrid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.opEstPrev{background:#f8fafc;border:1px solid #dbe4ef;border-radius:16px;padding:14px;margin:10px 0}.opEstActions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.opEstActions button{padding:14px}.opEstForm{background:#f8fafc;border:1px solid #e5e7eb;border-radius:16px;padding:14px;margin-top:12px}.opEstHist{max-height:260px;overflow:auto}@media(max-width:950px){.opEstGrid,.opEstActions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function nav(){var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="operacaoEstoque"]')){var r=document.querySelector('[data-p="operacao"]')||document.querySelector('[data-p="entrada"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="operacaoEstoque">Operação estoque</button>')}document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.p));var op=E('p-operacao');if(op&&!E('opEstQuick')){var g=op.querySelector('.opGrid');if(g)g.insertAdjacentHTML('afterbegin','<div id="opEstQuick" class="opBtn" data-go="operacaoEstoque"><div class="opIcon">⚡</div><b>Operação estoque</b><span>Busca, instalação, retorno e WhatsApp.</span></div>')}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function page(){var main=document.querySelector('.main');if(!main||E('p-operacaoEstoque'))return;main.insertAdjacentHTML('beforeend','<section id="p-operacaoEstoque" class="page"><div class="opEstHero"><h2>Operação do estoque</h2><p>Tela central do responsável pelo estoque: buscar equipamento, instalar no cliente, retorno, baixa, histórico e confirmação para WhatsApp.</p></div><div class="card"><input id="opEstBusca" placeholder="Busca rápida: bipe/digite MAC, SN, código ou patrimônio"><div id="opEstPrev" class="opEstPrev">Nenhum equipamento selecionado.</div><div class="opEstGrid"><div><div class="opEstActions"><button id="opEstInstalar" class="pri">Instalar no cliente</button><button id="opEstRetorno" class="ok">Retorno do cliente</button><button id="opEstBaixa" class="bad">Baixa autorizada</button><button id="opEstHistBtn" class="warn">Histórico</button><button id="opEstRelTec" class="pri">Relatório por técnico</button><button id="opEstRelCli" class="ok">Equipamentos no cliente</button><button id="opEstCopy" class="warn">Copiar confirmação WhatsApp</button></div><div id="opEstForm" class="opEstForm">Selecione uma ação.</div><div id="opEstMsg" class="msg"></div></div><div><h3>Histórico resumido</h3><div id="opEstHist" class="opEstHist tbl"></div></div></div></div></section>')}
var sel=null,lastText='';
function selected(){return sel}
function preview(){sel=findEq(E('opEstBusca')&&E('opEstBusca').value);var p=E('opEstPrev');if(!p)return;if(!sel){p.innerHTML='<b>Equipamento não encontrado.</b><br><small>Confira MAC, SN, código ou patrimônio.</small>';p.style.background='#fee2e2';hist();return}p.style.background='#f8fafc';p.innerHTML='<b>'+S(sel.codigo)+' - '+S(eqName(sel))+'</b><br><small>MAC/SN: '+S(sel.mac||sel.serial||'-')+'</small><br><small>Status: '+S(sel.status)+' | Local: '+S(sel.local||'-')+'</small><br><small>Técnico: '+S(sel.tecnicoAtual||sel.tecnico_atual||'-')+' | Cliente: '+S(sel.clienteAtual||sel.cliente_atual||'-')+'</small>';hist()}
function techOptions(){var arr=[...new Set([...(D.tecnicos||[]).map(t=>t.nome),...(D.equipamentos||[]).map(x=>x.tecnicoAtual||x.tecnico_atual)].filter(Boolean))].sort();return '<option value="">Técnico</option>'+arr.map(x=>'<option>'+S(x)+'</option>').join('')}
function formInst(){if(!selected())return msg('Pesquise um equipamento primeiro.','bad');E('opEstForm').innerHTML='<h3>Instalar no cliente</h3><input id="opCli" placeholder="Nome do cliente"><select id="opTec">'+techOptions()+'</select><textarea id="opObs" placeholder="Observação opcional"></textarea><button id="opDoInst" class="pri">Confirmar instalação</button>';if(sel.tecnicoAtual&&E('opTec'))E('opTec').value=sel.tecnicoAtual;E('opDoInst').onclick=doInst}
function formRet(){if(!selected())return msg('Pesquise um equipamento primeiro.','bad');E('opEstForm').innerHTML='<h3>Retorno do cliente</h3><select id="retTec">'+techOptions()+'</select><select id="retCond"><option>Aguardando teste</option><option>Funcionando</option><option>Defeito</option><option>Quebrado</option></select><textarea id="retObs" placeholder="Observação opcional"></textarea><button id="opDoRet" class="ok">Confirmar retorno</button>';E('opDoRet').onclick=doRet}
async function doInst(){try{var cli=(E('opCli').value||'').trim(),tec=(E('opTec').value||'').trim(),obs=(E('opObs').value||'').trim();if(!cli)return msg('Informe o cliente.','bad');if(!tec)return msg('Informe o técnico.','bad');var ant=sel.clienteAtual||sel.cliente_atual||'';var r=await db().from('equipamentos').update({status:'Instalado no cliente',local:'Cliente',cliente_atual:cli,tecnico_atual:null,os_atual:null,motivo_atual:'Instalado no cliente'}).eq('id',sel.id).select().single();if(r.error)throw r.error;sel.status='Instalado no cliente';sel.local='Cliente';sel.clienteAtual=cli;sel.cliente_atual=cli;sel.tecnicoAtual='';sel.tecnico_atual='';try{await mov(sel,'Instalado no cliente',{tec:tec,dest:'Cliente',cli:cli,mot:'Instalação no cliente',obs:(ant?'Cliente anterior: '+ant+' | ':'')+obs})}catch(e){}lastText='REGISTRADO NO ESTOQUE\nCliente: '+cli+'\nTécnico: '+tec+'\nEquipamento: '+eqName(sel)+'\nMAC/SN: '+(sel.mac||sel.serial||'-')+'\nStatus: Instalado no cliente';await reload();msg('Instalação registrada e confirmação pronta para WhatsApp.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
async function doRet(){try{var tec=(E('retTec').value||'').trim(),cond=E('retCond').value,obs=(E('retObs').value||'').trim();if(!tec)return msg('Informe o técnico que trouxe.','bad');var ant=sel.clienteAtual||sel.cliente_atual||'';var status=cond==='Funcionando'?'Aguardando teste':cond;var r=await db().from('equipamentos').update({status:status,local:'Estoque central',cliente_atual:null,tecnico_atual:null,os_atual:null,motivo_atual:'Retorno do cliente'}).eq('id',sel.id).select().single();if(r.error)throw r.error;sel.status=status;sel.local='Estoque central';sel.clienteAtual='';sel.cliente_atual='';sel.tecnicoAtual='';sel.tecnico_atual='';try{await mov(sel,'Retorno do cliente',{tec:tec,dest:'Estoque central',cli:ant,mot:cond,obs:obs})}catch(e){}lastText='RETORNO REGISTRADO\nCliente anterior: '+(ant||'-')+'\nTécnico: '+tec+'\nEquipamento: '+eqName(sel)+'\nMAC/SN: '+(sel.mac||sel.serial||'-')+'\nStatus: '+status;await reload();msg('Retorno registrado e confirmação pronta para WhatsApp.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
function hist(){var h=E('opEstHist');if(!h)return;if(!sel){h.innerHTML='';return}var rows=(D.movimentos||[]).filter(m=>m.equipamento_id===sel.id||m.codigo===sel.codigo).slice(0,20);h.innerHTML='<table><thead><tr><th>Data</th><th>Movimento</th><th>Obs</th></tr></thead><tbody>'+(rows.map(m=>'<tr><td>'+S(m.created_at?new Date(m.created_at).toLocaleString('pt-BR'):'')+'</td><td>'+S(m.tipo||m.movimento||m.acao||'-')+'</td><td>'+S(m.obs||m.observacao||m.motivo||'')+'</td></tr>').join('')||'<tr><td colspan="3">Sem histórico encontrado.</td></tr>')+'</tbody></table>'}
function copy(){if(!lastText&&sel)lastText='REGISTRO DE ESTOQUE\nEquipamento: '+eqName(sel)+'\nMAC/SN: '+(sel.mac||sel.serial||'-')+'\nStatus: '+(sel.status||'-')+'\nCliente: '+(sel.clienteAtual||sel.cliente_atual||'-')+'\nTécnico: '+(sel.tecnicoAtual||sel.tecnico_atual||'-');if(lastText)navigator.clipboard.writeText(lastText).then(()=>msg('Mensagem copiada para WhatsApp.','ok'))}
async function reload(){try{await loadAll()}catch(e){}preview();try{render()}catch(e){}}
function msg(t,c){var m=E('opEstMsg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
function bind(){css();page();nav();var b=E('opEstBusca');if(b&&!b.dataset.p54){b.dataset.p54=1;b.oninput=preview;b.onkeydown=function(ev){if(ev.key==='Enter')preview()}}if(E('opEstInstalar'))E('opEstInstalar').onclick=formInst;if(E('opEstRetorno'))E('opEstRetorno').onclick=formRet;if(E('opEstBaixa'))E('opEstBaixa').onclick=function(){go('descarte')};if(E('opEstHistBtn'))E('opEstHistBtn').onclick=hist;if(E('opEstRelTec'))E('opEstRelTec').onclick=function(){go('perdasTec')};if(E('opEstRelCli'))E('opEstRelCli').onclick=function(){go('clientesInstalados')};if(E('opEstCopy'))E('opEstCopy').onclick=copy}
setInterval(bind,1500);document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,2000));
})();