(function(){
function E(i){return document.getElementById(i)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function getModelo(){var t=E('tipo')&&E('tipo').value,m=E('marca')&&E('marca').value,mo=E('modelo')&&E('modelo').value;return (D.modelos||[]).find(x=>x.tipo===t&&x.marca===m&&x.modelo===mo)}
function isQty(mod){if(!mod)return false;var c=String(mod.controle||'').toLowerCase();return c.includes('quant')||mod.exige_mac_sn===false}
function toggleEntrada(){var mod=getModelo();var q=isQty(mod);['mac','serial','pat'].forEach(function(id){var el=E(id);if(el){el.closest ? (el.closest('input,select,textarea')||el).style.display=q?'none':'' : el.style.display=q?'none':''}});var cod=E('cod');if(cod)cod.placeholder=q?'Código automático por lote':'Código automático';var custo=E('custo');if(custo)custo.placeholder=q?'Custo unitário ou total';var old=E('qtyEntrada');if(q&&!old){var input=document.createElement('input');input.id='qtyEntrada';input.type='number';input.min='1';input.placeholder='Quantidade';input.value='1';var ref=E('pat')||E('custo');ref&&ref.parentNode.insertBefore(input,ref.nextSibling)}if(!q&&old)old.remove();}
async function entradaNova(){try{var mod=getModelo();var q=isQty(mod);if(q){var qtd=Number((E('qtyEntrada')&&E('qtyEntrada').value)||1);if(!mod){msg('entMsg','Selecione tipo, marca e modelo.','bad');return}if(!qtd||qtd<1){msg('entMsg','Informe a quantidade.','bad');return}var e={codigo:next('LOT','codigo'),patrimonio:null,tipo:E('tipo').value,marca:E('marca').value,modelo:E('modelo').value,mac:null,serial:null,status:'Em estoque',local:E('local').value,custo:Number(E('custo').value||0),motivoAtual:'Entrada por quantidade: '+qtd};e=fromEq(await ins('equipamentos',toEq(e)));e.quantidade=qtd;D.equipamentos.unshift(e);try{await mov(e,'Entrada por quantidade',{dest:e.local,obs:'Quantidade: '+qtd+' | '+(E('obs')?E('obs').value:''),mot:'Entrada por quantidade'})}catch(x){}['custo','forn','nf','resp','obs'].forEach(function(i){if(E(i))E(i).value=''});if(E('qtyEntrada'))E('qtyEntrada').value='1';try{render()}catch(x){}toggleEntrada();msg('entMsg','Entrada por quantidade registrada: '+qtd+' un. de '+e.modelo,'ok');return}
 if(typeof window.__entradaOriginal==='function')return window.__entradaOriginal();
}catch(e){msg('entMsg','Erro ao registrar entrada: '+e.message,'bad')}}
function bind(){if(!window.__entradaOriginal&&typeof window.entrada==='function')window.__entradaOriginal=window.entrada;window.entrada=entradaNova;if(E('entrada'))E('entrada').onclick=entradaNova;['tipo','marca','modelo'].forEach(function(id){if(E(id))E(id).addEventListener('change',toggleEntrada)});toggleEntrada()}
setInterval(bind,1500);document.addEventListener('DOMContentLoaded',function(){setTimeout(bind,2500)});
})();