(function(){
function e(i){return document.getElementById(i)}
function h(v){try{return esc(v??'')}catch(x){return String(v??'')}}
function n(v){return Number(v||0)}
async function lp(){try{D.produtoTipos=await loadTable('produto_tipos','nome',true)}catch(x){D.produtoTipos=[]}try{D.produtoMarcas=await loadTable('produto_marcas','nome',true)}catch(x){D.produtoMarcas=[]}}
function css(){if(e('p50css'))return;var s=document.createElement('style');s.id='p50css';s.textContent='.prodHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.prodGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.prodCard{background:white;border:1px solid #e5e7eb;border-radius:18px;padding:16px;box-shadow:0 10px 28px #0f172a12}.prodBig{grid-column:1/-1}.prodMini{display:flex;justify-content:space-between;gap:8px;align-items:center;background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:9px;margin:6px 0}.prodTag{display:inline-block;border-radius:999px;padding:3px 8px;background:#eef2ff;color:#3730a3;font-weight:800;font-size:12px}.prodTag.ok{background:#dcfce7;color:#166534}.prodTag.bad{background:#fee2e2;color:#991b1b}.prodTag.warn{background:#fef3c7;color:#92400e}@media(max-width:950px){.prodGrid{grid-template-columns:1fr}.prodBig{grid-column:auto}}';document.head.appendChild(s)}
function opts(a,sel){return '<option value="">Selecione</option>'+a.map(x=>'<option '+(sel===x.nome?'selected':'')+'>'+h(x.nome)+'</option>').join('')}
function uopts(sel){return ['Unidade','Metro','Bobina','Caixa','Pacote','Peça','Par','Rolo','Kit'].map(x=>'<option '+(sel===x?'selected':'')+'>'+x+'</option>').join('')}
function draw(){var p=e('p-cadastros');if(!p)return;css();p.innerHTML='<div class="prodHero"><h2>Produtos</h2><p>Tipos, Marcas e Modelos em uma única tela. Aqui o padrão é excluir cadastro errado, não apenas ocultar.</p></div><div class="prodGrid"><div class="prodCard"><h2>Tipos</h2><input id="p50TipoNome" placeholder="Ex: ONU, RJ45, Cabo"><div class="grid"><select id="p50TipoControle"><option>Unitário</option><option>Quantidade</option></select><select id="p50TipoMac"><option value="true">Exige MAC/SN</option><option value="false">Não exige MAC/SN</option></select></div><button id="p50AddTipo" class="pri">Adicionar tipo</button><div id="p50TipoMsg" class="msg"></div><div id="p50Tipos"></div></div><div class="prodCard"><h2>Marcas</h2><input id="p50MarcaNome" placeholder="Ex: ZTE, Genérico, Sem marca"><button id="p50AddMarca" class="pri">Adicionar marca</button><div id="p50MarcaMsg" class="msg"></div><div id="p50Marcas"></div></div><div class="prodCard prodBig"><h2>Modelos / Produtos</h2><div class="grid4"><select id="p50ModTipo"></select><select id="p50ModMarca"></select><input id="p50ModNome" placeholder="Modelo/Produto"><select id="p50ModControle"><option>Unitário</option><option>Quantidade</option></select><select id="p50ModUnidade"></select><select id="p50ModMac"><option value="true">Exige MAC/SN</option><option value="false">Não exige MAC/SN</option></select><input id="p50ModCusto" type="number" placeholder="Custo padrão"><input id="p50ModMin" type="number" placeholder="Estoque mínimo"><input id="p50ModIdeal" type="number" placeholder="Estoque ideal"></div><button id="p50AddModelo" class="pri">Adicionar modelo/produto</button><div id="p50ModMsg" class="msg"></div><div class="tbl"><table><thead><tr><th>Tipo</th><th>Marca</th><th>Modelo</th><th>Controle</th><th>Unidade</th><th>MAC/SN</th><th>Mínimo</th><th>Ideal</th><th>Ações</th></tr></thead><tbody id="p50Modelos"></tbody></table></div></div></div>'}
function renderP(){if(e('p50ModTipo'))e('p50ModTipo').innerHTML=opts(D.produtoTipos||[],e('p50ModTipo').value);if(e('p50ModMarca'))e('p50ModMarca').innerHTML=opts(D.produtoMarcas||[],e('p50ModMarca').value);if(e('p50ModUnidade'))e('p50ModUnidade').innerHTML=uopts(e('p50ModUnidade').value||'Unidade');var t=e('p50Tipos');if(t)t.innerHTML=(D.produtoTipos||[]).map(x=>'<div class="prodMini"><div><b>'+h(x.nome)+'</b><br><span class="prodTag '+(x.controle==='Quantidade'?'warn':'ok')+'">'+h(x.controle)+'</span> <span class="prodTag '+(x.exige_mac_sn?'bad':'ok')+'">'+(x.exige_mac_sn?'Exige MAC/SN':'Sem MAC/SN')+'</span></div><button class="bad" onclick="p50Del(\'produto_tipos\',\''+x.id+'\')">Excluir</button></div>').join('')||'<div class="msg">Nenhum tipo.</div>';var m=e('p50Marcas');if(m)m.innerHTML=(D.produtoMarcas||[]).map(x=>'<div class="prodMini"><b>'+h(x.nome)+'</b><button class="bad" onclick="p50Del(\'produto_marcas\',\''+x.id+'\')">Excluir</button></div>').join('')||'<div class="msg">Nenhuma marca.</div>';var tb=e('p50Modelos');if(tb)tb.innerHTML=(D.modelos||[]).map(x=>'<tr><td>'+h(x.tipo)+'</td><td>'+h(x.marca)+'</td><td><b>'+h(x.modelo)+'</b></td><td>'+h(x.controle||'Unitário')+'</td><td>'+h(x.unidade||'Unidade')+'</td><td>'+(x.exige_mac_sn===false?'Não':'Sim')+'</td><td>'+h(x.minimo??x.estoque_minimo??'')+'</td><td>'+h(x.ideal??x.estoque_ideal??'')+'</td><td><button onclick="p50Edit(\''+x.id+'\')">Editar</button><button class="bad" onclick="p50Del(\'modelos\',\''+x.id+'\')">Excluir</button></td></tr>').join('')||'<tr><td colspan="9">Nenhum modelo.</td></tr>'}
async function addT(){try{var nome=(e('p50TipoNome').value||'').trim();if(!nome)throw Error('Informe o tipo.');var r=await db().from('produto_tipos').insert({nome:nome,controle:e('p50TipoControle').value,exige_mac_sn:e('p50TipoMac').value==='true',ativo:true});if(r.error)throw r.error;e('p50TipoNome').value='';await lp();renderP();e('p50TipoMsg').textContent='Tipo cadastrado.';e('p50TipoMsg').className='msg ok'}catch(x){e('p50TipoMsg').textContent='Erro: '+x.message;e('p50TipoMsg').className='msg bad'}}
async function addM(){try{var nome=(e('p50MarcaNome').value||'').trim();if(!nome)throw Error('Informe a marca.');var r=await db().from('produto_marcas').insert({nome:nome,ativo:true});if(r.error)throw r.error;e('p50MarcaNome').value='';await lp();renderP();e('p50MarcaMsg').textContent='Marca cadastrada.';e('p50MarcaMsg').className='msg ok'}catch(x){e('p50MarcaMsg').textContent='Erro: '+x.message;e('p50MarcaMsg').className='msg bad'}}
async function addModelo(){try{var row={tipo:e('p50ModTipo').value,marca:e('p50ModMarca').value,modelo:(e('p50ModNome').value||'').trim(),controle:e('p50ModControle').value,unidade:e('p50ModUnidade').value,exige_mac_sn:e('p50ModMac').value==='true',custo:n(e('p50ModCusto').value),minimo:n(e('p50ModMin').value),ideal:n(e('p50ModIdeal').value),ativo:true};if(!row.tipo||!row.marca||!row.modelo)throw Error('Preencha tipo, marca e modelo.');var r=await db().from('modelos').insert(row);if(r.error)throw r.error;['p50ModNome','p50ModCusto','p50ModMin','p50ModIdeal'].forEach(i=>e(i).value='');await loadAll();await lp();renderP();e('p50ModMsg').textContent='Modelo cadastrado.';e('p50ModMsg').className='msg ok'}catch(x){e('p50ModMsg').textContent='Erro: '+x.message;e('p50ModMsg').className='msg bad'}}
window.p50Del=async function(tab,id){if(!confirm('Excluir este cadastro?'))return;var r=await db().from(tab).delete().eq('id',id);if(r.error){alert('Erro ao excluir: '+r.error.message);return}await loadAll();await lp();draw();bind();renderP()}
window.p50Edit=function(id){var x=(D.modelos||[]).find(a=>a.id===id);if(!x)return;e('p50ModTipo').value=x.tipo;e('p50ModMarca').value=x.marca;e('p50ModNome').value=x.modelo;e('p50ModControle').value=x.controle||'Unitário';e('p50ModUnidade').value=x.unidade||'Unidade';e('p50ModMac').value=x.exige_mac_sn===false?'false':'true';e('p50ModCusto').value=x.custo||'';e('p50ModMin').value=x.minimo||'';e('p50ModIdeal').value=x.ideal||'';e('p50ModMsg').textContent='Edite e salve como novo. Depois exclua o antigo se necessário.';e('p50ModMsg').className='msg warn'}
function defaults(){var t=(D.produtoTipos||[]).find(x=>x.nome===e('p50ModTipo').value);if(t){e('p50ModControle').value=t.controle||'Unitário';e('p50ModMac').value=t.exige_mac_sn?'true':'false'}}
function bind(){if(!e('p50AddTipo'))draw();if(e('p50AddTipo'))e('p50AddTipo').onclick=addT;if(e('p50AddMarca'))e('p50AddMarca').onclick=addM;if(e('p50AddModelo'))e('p50AddModelo').onclick=addModelo;if(e('p50ModTipo'))e('p50ModTipo').onchange=defaults}
async function boot(){if(!e('p-cadastros'))return;await lp();draw();bind();renderP()}
setInterval(function(){if(e('p-cadastros')&&e('p-cadastros').classList.contains('on')&&!e('p50AddTipo'))boot()},700);
document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,1800)});
})();