(function(){
function load(id,src){if(document.getElementById(id))return;var s=document.createElement('script');s.id=id;s.src=src;document.body.appendChild(s)}
document.addEventListener('DOMContentLoaded',function(){
 setTimeout(function(){load('relatoriosFixLoader','relatorios_fix.js?v=1')},150);
 setTimeout(function(){load('patch59loader','patch59.js?v=59')},300);
 setTimeout(function(){load('patch37loader','patch37.js?v=37')},1200);
 setTimeout(function(){load('patch38loader','patch38.js?v=38')},1800);
 setTimeout(function(){load('patch39loader','patch39.js?v=39')},2200);
 setTimeout(function(){load('patch42loader','patch42.js?v=42')},2600);
 setTimeout(function(){load('patch43loader','patch43.js?v=43')},3200);
 setTimeout(function(){load('patch44loader','patch44.js?v=44')},3600);
 setTimeout(function(){load('patch46loader','patch46.js?v=46')},4200);
 setTimeout(function(){load('patch50loader','patch50.js?v=50')},4700);
 setTimeout(function(){load('patch51loader','patch51.js?v=56')},5200);
 setTimeout(function(){load('patch60loader','patch60.js?v=60')},6100);
 setTimeout(function(){load('patch61loader','patch61.js?v=61')},6800);
 setTimeout(function(){load('patch62loader','patch62.js?v=62')},7300);
 setTimeout(function(){load('materiaisMainLoader','materiais_main.js?v=4')},8100);
 setTimeout(function(){load('finalStableLoader','final_stable.js?v=2')},9000);
 setTimeout(function(){load('estoqueTecnicoMaterialLoader','estoque_tecnico_material.js?v=1')},9600);
 setTimeout(function(){load('estoqueCentralMateriaisLoader','estoque_central_materiais.js?v=1')},10200);
 setTimeout(function(){load('entradaLoteLoader','entrada_lote.js?v=1')},10800);
 setTimeout(function(){load('paginacaoTabelasLoader','paginacao_tabelas.js?v=1')},11400);
 setTimeout(function(){load('operacaoEstoqueBuscaLoader','operacao_estoque_busca.js?v=1')},12000);
 setTimeout(function(){load('operacaoRapidaLoader','operacao_rapida.js?v=1')},12600);
 setTimeout(function(){load('relatoriosBlocosLoader','relatorios_blocos.js?v=2')},13200);
 setTimeout(function(){load('relatoriosDatasLoader','relatorios_datas.js?v=1')},13800);
});
})();