/* LIKE Estoque V37 - prioridade: almoxarifado fechado, responsabilidade e descarte autorizado */
(function(){
  const BLOCKED=['Aguardando teste','Em manutenção','Inutilizado','Perdido','Descarte autorizado'];
  function $(id){return document.getElementById(id)}
  function E(v){return esc(v??'')}
  function K(v){return N(v||'')}
  function eqName(e){return `${E(e.codigo)} • ${E(e.tipo)} ${E(e.marca)} ${E(e.modelo)} • ${E(e.mac||e.serial||'sem MAC/SN')}`}
  function exact(term){const k=K(term);if(!k)return null;return D.equipamentos.find(e=>K(e.codigo)===k||K(e.patrimonio)===k||K(e.mac)===k||K(e.serial)===k)||null}
  async function qIns(t,r){const x=await db().from(t).insert(r).select().single();if(x.error)throw x.error;return x.data}
  async function qUpd(t,id,r){const x=await db().from(t).update(r).eq('id',id).select().single();if(x.error)throw x.error;return x.data}
  function setMsg(id,text,cls=''){const e=$(id);if(e){e.textContent=text;e.className='msg '+cls}}

  function style(){if($('policy37style'))return;const s=document.createElement('style');s.id='policy37style';s.textContent=`
    .policyBox{background:#fff7ed;border:2px solid #fed7aa;border-radius:18px;padding:16px;margin-bottom:14px}.policyBox h2{margin:0 0 8px;color:#7c2d12}.policyRules{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ruleCard{background:white;border:1px solid #fed7aa;border-radius:14px;padding:12px}.ruleCard b{display:block;color:#0d1b2e}.priorityBadge{display:inline-block;background:#fee2e2;color:#991b1b;border-radius:999px;padding:5px 9px;font-weight:900;font-size:12px}.termBox{background:white;border:1px solid #dbe4ef;border-radius:18px;padding:18px;margin-top:12px}.discardGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.lossKpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.lossKpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:12px}.bigSearch{font-size:18px;padding:15px;border:2px solid #0f4c81}@media(max-width:950px){.policyRules,.discardGrid,.lossKpi{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  async function loadDescartes(){try{D.descartes=await loadTable('descartes_autorizados','created_at',false)}catch(e){D.descartes=[]}}

  function addPages(){
    const main=document.querySelector('.main');if(!main||$('p-politicaEstoque'))return;
    const op=document.querySelector('[data-p="operacao"]')||document.querySelector('[data-p="dash"]');
    if(op)op.insertAdjacentHTML('afterend','<button class="nav" data-p="politicaEstoque">Prioridade estoque</button>');
    const pend=document.querySelector('[data-p="pendencias"]')||document.querySelector('[data-p="historico"]');
    if(pend)pend.insertAdjacentHTML('beforebegin','<button class="nav" data-p="descarte">Descarte autorizado</button><button class="nav" data-p="perdasTec">Perdas por técnico</button>');
    main.insertAdjacentHTML('beforeend',`
<section id="p-politicaEstoque" class="page"><div class="policyBox"><span class="priorityBadge">PRIORIDADE OPERACIONAL</span><h2>Almoxarifado fechado e responsabilidade por equipamento</h2><p>Use esta tela como regra do estoque: técnico não retira material sozinho. Tudo precisa ser bipado e vinculado a um responsável.</p><div class="policyRules"><div class="ruleCard"><b>1. Não pegar sozinho</b><small>Técnico solicita. Estoque separa e registra.</small></div><div class="ruleCard"><b>2. Sem bipagem, não saiu</b><small>MAC/SN/código precisam constar na saída.</small></div><div class="ruleCard"><b>3. Quebrado não vai para lixo</b><small>Vai para Aguardando teste ou descarte autorizado.</small></div><div class="ruleCard"><b>4. Faltou, vira pendência</b><small>Conferência gera cobrança formal.</small></div></div></div><div class="opGrid"><div class="opBtn" onclick="pg('saidaLote')"><div class="opIcon">🔒</div><b>Retirada controlada</b><span>Registrar saída antes do técnico levar.</span></div><div class="opBtn" onclick="pg('devolucaoLote')"><div class="opIcon">📥</div><b>Devolução com triagem</b><span>Voltou da rua? Coloque em Aguardando teste.</span></div><div class="opBtn" onclick="pg('descarte')"><div class="opIcon">🗑️</div><b>Descarte autorizado</b><span>Nada vai para lixo sem registro.</span></div><div class="opBtn" onclick="pg('conferenciaTec')"><div class="opIcon">🧰</div><b>Conferência do técnico</b><span>Gera pendência dos faltantes.</span></div><div class="opBtn" onclick="pg('pendencias')"><div class="opIcon">⚠️</div><b>Pendências</b><span>Cobrar devolução, perda ou justificativa.</span></div><div class="opBtn" onclick="pg('perdasTec')"><div class="opIcon">📉</div><b>Perdas por técnico</b><span>Relatório para gestão.</span></div></div><div class="termBox"><h2>Texto da regra interna</h2><textarea id="policyText" style="min-height:180px">A partir de agora, nenhum equipamento poderá ser retirado do almoxarifado sem registro individual no sistema, contendo código, MAC/SN, técnico responsável, data e destino.

Fica proibido descartar, jogar fora, trocar ou repassar qualquer equipamento sem registro e autorização.

Todo equipamento em posse do técnico será considerado de sua responsabilidade até que seja devolvido e baixado no sistema pelo estoque.

Equipamentos quebrados, queimados, com dano físico ou sem funcionamento devem obrigatoriamente retornar ao estoque para triagem. O descarte só poderá ocorrer após autorização.

Retiradas sem registro, descarte não autorizado ou ausência do equipamento em conferência serão tratados como pendência de responsabilidade.</textarea><button class="warn" onclick="navigator.clipboard.writeText(policyText.value)">Copiar regra</button></div></section>
<section id="p-descarte" class="page"><div class="card"><h2>Descarte autorizado</h2><p class="small">Use para impedir equipamento quebrado no lixo sem registro. Primeiro solicite. Depois aprove. Só então descarte.</p><div class="discardGrid"><div><input id="discSearch" class="bigSearch" placeholder="Bipe/digite MAC, SN, código ou patrimônio"><div id="discPrev" class="msg">Pesquise o equipamento.</div><select id="discMotivo"><option>Queimado</option><option>Quebrado</option><option>Oxidação</option><option>Com tinta/dano físico</option><option>Sem reparo</option><option>Extraviado</option><option>Outro</option></select><input id="discSolic" placeholder="Solicitado por"><input id="discAprov" placeholder="Aprovado por"><textarea id="discObs" placeholder="Observação / justificativa"></textarea><button id="discSolicitar" class="warn">Solicitar descarte</button><button id="discAprovar" class="bad">Aprovar e marcar descarte</button></div><div><h3>Descartes registrados</h3><div class="tbl"><table><thead><tr><th>Data</th><th>Equipamento</th><th>Motivo</th><th>Status</th><th>Aprovado por</th></tr></thead><tbody id="discTable"></tbody></table></div></div></div><div id="discMsg" class="msg"></div></div></section>
<section id="p-perdasTec" class="page"><div class="card"><h2>Relatório de perdas por técnico</h2><p class="small">Mostra pendências, perdas, descartes e valor estimado por responsável.</p><div class="grid4"><select id="lossTec"></select><button id="lossGen" class="pri">Gerar relatório</button><button id="lossPrint" class="ok">Imprimir/PDF</button><button id="lossCopy" class="warn">Copiar resumo</button></div><div id="lossArea"></div></div></section>`);
    document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>pg(b.dataset.p));
  }

  let discEq=null;
  function previewDisc(){discEq=exact($('discSearch')?.value||'');const p=$('discPrev');if(!p)return;if(!discEq){p.textContent='Equipamento não encontrado.';p.className='msg bad';return}p.innerHTML=`<b>${eqName(discEq)}</b><br>Status atual: ${E(discEq.status)} • Técnico: ${E(discEq.tecnicoAtual||'-')} • Local: ${E(discEq.local||'-')}`;p.className='msg ok'}
  async function solicitarDescarte(aprovar=false){try{if(!discEq)previewDisc();if(!discEq){setMsg('discMsg','Pesquise um equipamento válido.','bad');return}const motivo=$('discMotivo').value,sol=$('discSolic').value.trim(),ap=$('discAprov').value.trim(),obs=$('discObs').value.trim();if(aprovar&&!ap){setMsg('discMsg','Informe quem aprovou o descarte.','bad');return}const status=aprovar?'Descartado':'Solicitado';await qIns('descartes_autorizados',{equipamento_id:discEq.id,codigo:discEq.codigo,mac:discEq.mac,serial:discEq.serial,modelo:`${discEq.tipo} ${discEq.marca} ${discEq.modelo}`,tecnico:discEq.tecnicoAtual||'',solicitado_por:sol,aprovado_por:ap,motivo,status,observacao:obs,aprovado_em:aprovar?new Date().toISOString():null,descartado_em:aprovar?new Date().toISOString():null});if(aprovar){discEq.status='Descarte autorizado';discEq.local='Descarte autorizado';discEq.motivoAtual=motivo;Object.assign(discEq,fromEq(await upd('equipamentos',discEq.id,toEq(discEq))));await mov(discEq,'Descarte autorizado',{tec:discEq.tecnicoAtual||'',dest:'Descarte autorizado',mot:motivo,obs:'Descarte aprovado por '+ap+' | '+obs})}await loadDescartes();renderDescartes();render();setMsg('discMsg',aprovar?'Descarte aprovado e equipamento bloqueado.':'Solicitação de descarte registrada.','ok')}catch(e){setMsg('discMsg','Erro: '+e.message,'bad')}}
  function renderDescartes(){const t=$('discTable');if(!t)return;const list=D.descartes||[];t.innerHTML=list.map(d=>`<tr><td>${new Date(d.created_at).toLocaleDateString('pt-BR')}</td><td><b>${E(d.codigo)}</b><br><small>${E(d.modelo)}<br>${E(d.mac||d.serial||'')}</small></td><td>${E(d.motivo)}</td><td>${E(d.status)}</td><td>${E(d.aprovado_por||'-')}</td></tr>`).join('')||'<tr><td colspan="5">Nenhum descarte registrado.</td></tr>'}

  function fillLossTec(){const s=$('lossTec');if(!s)return;const old=s.value;s.innerHTML='<option value="">Todos os técnicos</option>'+D.tecnicos.map(t=>`<option>${E(t.nome)}</option>`).join('');if([...s.options].some(o=>o.value===old))s.value=old}
  function genLoss(){const tec=$('lossTec')?.value||'';const pend=(D.pendencias||[]).filter(p=>(!tec||p.tecnico===tec));const abertas=pend.filter(p=>p.status==='Aberta');const cobrar=pend.filter(p=>p.status==='Cobrar valor');const perdas=D.equipamentos.filter(e=>(!tec||e.tecnicoAtual===tec)&&['Perdido','Descarte autorizado','Inutilizado'].includes(e.status));const desc=(D.descartes||[]).filter(d=>(!tec||d.tecnico===tec));const valor=perdas.reduce((s,e)=>s+Number(e.custo||0),0);const area=$('lossArea');if(!area)return;area.innerHTML=`<div class="lossKpi"><div><small>Pendências abertas</small><b>${abertas.length}</b></div><div><small>Cobrar valor</small><b>${cobrar.length}</b></div><div><small>Perdas/descartes</small><b>${perdas.length}</b></div><div><small>Valor estimado</small><b>${money(valor)}</b></div></div><div class="tbl"><table><thead><tr><th>Técnico</th><th>Código</th><th>Equipamento</th><th>Status/Motivo</th><th>Valor</th></tr></thead><tbody>${perdas.map(e=>`<tr><td>${E(e.tecnicoAtual||'-')}</td><td>${E(e.codigo)}</td><td>${E(e.tipo)} ${E(e.marca)} ${E(e.modelo)}<br><small>${E(e.mac||e.serial||'')}</small></td><td>${E(e.status)}<br><small>${E(e.motivoAtual||e.inutilizadoObs||'')}</small></td><td>${money(e.custo)}</td></tr>`).join('')||'<tr><td colspan="5">Sem perdas nesse filtro.</td></tr>'}</tbody></table></div><h3>Pendências</h3><div class="tbl"><table><thead><tr><th>Técnico</th><th>Equipamento</th><th>Motivo</th><th>Status</th></tr></thead><tbody>${pend.map(p=>`<tr><td>${E(p.tecnico)}</td><td>${E(p.codigo)}<br><small>${E(p.modelo)}</small></td><td>${E(p.motivo)}</td><td>${E(p.status)}</td></tr>`).join('')||'<tr><td colspan="4">Sem pendências.</td></tr>'}</tbody></table></div>`}
  function copyLoss(){const txt=($('lossArea')?.innerText||'').trim();if(txt)navigator.clipboard.writeText(txt)}
  function printLoss(){const html=$('lossArea')?.innerHTML||'';if(!html){genLoss()}setTimeout(()=>{const w=window.open('','_blank');if(!w)return alert('Permita pop-ups.');w.document.write('<html><head><title>Perdas por técnico</title><style>body{font-family:Arial;padding:20px}table{width:100%;border-collapse:collapse}th{background:#0f4c81;color:white}td,th{border:1px solid #ddd;padding:8px}.lossKpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.lossKpi div{border:1px solid #ddd;padding:10px;border-radius:8px}</style></head><body><h2>LIKE internet - Relatório de perdas por técnico</h2>'+($('lossArea')?.innerHTML||'')+'</body></html>');w.document.close();w.print()},150)}

  function patchBlockedOutputs(){
    const oldApplyOut=window.applyOut; // normalmente não global
    const oldMov=window.mov;
  }
  function enforceBlockedInTables(){
    document.querySelectorAll('select').forEach(sel=>{[...sel.options].forEach(o=>{if(o.textContent==='Perdido'&&!([...sel.options].some(x=>x.textContent==='Descarte autorizado'))){const n=document.createElement('option');n.textContent='Descarte autorizado';sel.appendChild(n)}})})
  }
  function enhanceOperation(){const op=$('p-operacao .opGrid');if(!op||$('policyQuickBtn'))return;op.insertAdjacentHTML('afterbegin',`<div id="policyQuickBtn" class="opBtn" onclick="pg('politicaEstoque')"><div class="opIcon">🚫</div><b>Regra prioritária</b><span>Sem registro, não sai. Sem autorização, não descarta.</span></div><div class="opBtn" onclick="pg('descarte')"><div class="opIcon">🗑️</div><b>Descarte autorizado</b><span>Registrar quebrado antes de jogar fora.</span></div><div class="opBtn" onclick="pg('perdasTec')"><div class="opIcon">📉</div><b>Perdas por técnico</b><span>Relatório de prejuízo e responsabilidade.</span></div>`)}

  async function boot(){style();addPages();enhanceOperation();fillLossTec();renderDescartes();enforceBlockedInTables();if($('discSearch')&&!$('discSearch').dataset.h){$('discSearch').dataset.h='1';$('discSearch').addEventListener('input',previewDisc);$('discSearch').addEventListener('keydown',e=>{if(e.key==='Enter')previewDisc()})}if($('discSolicitar'))$('discSolicitar').onclick=()=>solicitarDescarte(false);if($('discAprovar'))$('discAprovar').onclick=()=>solicitarDescarte(true);if($('lossGen'))$('lossGen').onclick=genLoss;if($('lossCopy'))$('lossCopy').onclick=copyLoss;if($('lossPrint'))$('lossPrint').onclick=printLoss;try{await loadDescartes()}catch(e){D.descartes=[]}renderDescartes()}
  const oldLoad=loadAll;loadAll=async function(){await oldLoad();try{await loadDescartes()}catch(e){D.descartes=[]}renderDescartes();fillLossTec();enhanceOperation()};
  const oldRender=render;render=function(){oldRender();style();addPages();enhanceOperation();fillLossTec();renderDescartes();enforceBlockedInTables()};
  document.addEventListener('DOMContentLoaded',()=>{setTimeout(boot,1200);setTimeout(boot,2400)});
})();