(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function BR(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function eqName(x){return ((x.tipo||'')+' '+(x.marca||'')+' '+(x.modelo||'')).trim()}
function techName(x){return x.tecnicoAtual||x.tecnico_atual||x.tecnico||''}
function go(p){try{pg(p)}catch(e){}}
function css(){if(E('p55css'))return;var s=document.createElement('style');s.id='p55css';s.textContent='.tecHead{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.tecGrid{display:grid;grid-template-columns:.9fr 1.1fr;gap:14px}.tecMini{display:flex;justify-content:space-between;align-items:center;gap:8px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:10px;margin:8px 0;cursor:pointer}.tecMini.on{outline:3px solid #0f4c8124;border-color:#0f4c81}.tecKpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.tecKpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.tecActions{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}@media(max-width:950px){.tecGrid,.tecKpi,.tecActions{grid-template-columns:1fr}}';document.head.appendChild(s)}
function nav(){var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="tecnicosFull"]')){var r=document.querySelector('[data-p="operacaoEstoque"]')||document.querySelector('[data-p="cadastros"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="tecnicosFull">Técnicos</button>')}document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.p));var op=E('p-operacao');if(op&&!E('tecQuick')){var g=op.querySelector('.opGrid');if(g)g.insertAdjacentHTML('afterbegin','<div id="tecQuick" class="opBtn" data-go="tecnicosFull"><div class="opIcon">👷</div><b>Técnicos</b><span>Cadastro, posse e relatórios.</span></div>')}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function page(){var main=document.querySelector('.main');if(!main||E('p-tecnicosFull'))return;main.insertAdjacentHTML('beforeend','<section id="p-tecnicosFull" class="page"><div class="tecHead"><h2>Técnicos</h2><p>Cadastro, equipamentos em posse, pendências e relatórios essenciais por técnico.</p></div><div class="tecGrid"><div class="card"><h2>Adicionar técnico</h2><input id="tecNomeNovo" placeholder="Nome do técnico"><button id="tecAdd" class="pri">Adicionar técnico</button><div id="tecMsg" class="msg"></div><h2>Lista de técnicos</h2><input id="tecBusca" placeholder="Buscar técnico"><div id="tecList"></div></div><div class="card"><h2 id="tecTitle">Selecione um técnico</h2><div id="tecKpis" class="tecKpi"></div><div class="tecActions"><button id="tecView" class="pri">Ver equipamentos</button><button id="tecReport" class="ok">Gerar relatório</button><button id="tecCopy" class="warn">Copiar cobrança</button><button id="tecPrint" class="bad">Imprimir/PDF</button></div><div id="tecArea"></div></div></div></section>')}
var selected='';
function equipamentosTec(nome){return (D.equipamentos||[]).filter(x=>techName(x)===nome&&x.status!=='Descarte autorizado'&&x.status!=='Instalado no cliente')}
function pendTec(nome){return (D.pendencias||[]).filter(p=>(p.tecnico||'')===nome&&['Aberta','Cobrar valor','Divergente'].includes(p.status||''))}
function renderList(){var box=E('tecList');if(!box)return;var q=(E('tecBusca')&&E('tecBusca').value||'').toLowerCase().trim();var nomes=[...new Set([...(D.tecnicos||[]).map(t=>t.nome),...(D.equipamentos||[]).map(x=>techName(x))].filter(Boolean))].sort().filter(n=>!q||n.toLowerCase().includes(q));box.innerHTML=nomes.map(n=>{var qtd=equipamentosTec(n).length;var pend=pendTec(n).length;var rec=(D.tecnicos||[]).find(t=>t.nome===n);return '<div class="tecMini '+(selected===n?'on':'')+'" onclick="window.tecSelect(\''+S(n).replace(/'/g,'&#39;')+'\')"><div><b>'+S(n)+'</b><br><small>'+qtd+' equipamentos | '+pend+' pendências</small></div><button class="bad" onclick="event.stopPropagation();window.tecDelete(\''+(rec?rec.id:'')+'\',\''+S(n).replace(/'/g,'&#39;')+'\')">Excluir</button></div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>'}
function renderSelected(){if(!selected){if(E('tecTitle'))E('tecTitle').textContent='Selecione um técnico';if(E('tecKpis'))E('tecKpis').innerHTML='';if(E('tecArea'))E('tecArea').innerHTML='';return}var eqs=equipamentosTec(selected),pends=pendTec(selected);var val=eqs.reduce((s,x)=>s+Number(x.custo||0),0);E('tecTitle').textContent='Técnico: '+selected;E('tecKpis').innerHTML='<div><small>Equipamentos em posse</small><b>'+eqs.length+'</b></div><div><small>Pendências abertas</small><b>'+pends.length+'</b></div><div><small>Valor estimado</small><b>'+BR(val)+'</b></div><div><small>Instalados no cliente</small><b>'+(D.equipamentos||[]).filter(x=>(x.ultimoTecnico===selected||x.tecnicoInstalador===selected)&&x.status==='Instalado no cliente').length+'</b></div>'}
function tableHtml(){var eqs=equipamentosTec(selected),pends=pendTec(selected);return '<h3>Equipamentos em posse</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Valor</th></tr></thead><tbody>'+(eqs.map(x=>'<tr><td>'+S(x.codigo)+'</td><td>'+S(eqName(x))+'</td><td>'+S(x.mac||x.serial||'-')+'</td><td>'+S(x.status)+'</td><td>'+S(x.local||'-')+'</td><td>'+BR(x.custo||0)+'</td></tr>').join('')||'<tr><td colspan="6">Sem equipamentos em posse.</td></tr>')+'</tbody></table></div><h3>Pendências</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Motivo</th><th>Status</th><th>Valor</th></tr></thead><tbody>'+(pends.map(p=>'<tr><td>'+S(p.codigo||'-')+'</td><td>'+S(p.motivo||'-')+'</td><td>'+S(p.status||'-')+'</td><td>'+BR(p.valor_estimado||0)+'</td></tr>').join('')||'<tr><td colspan="4">Sem pendências abertas.</td></tr>')+'</tbody></table></div>'}
function view(){if(!selected)return msg('Selecione um técnico.','bad');renderSelected();E('tecArea').innerHTML=tableHtml()}
function report(){if(!selected)return msg('Selecione um técnico.','bad');var date=new Date().toLocaleString('pt-BR');E('tecArea').innerHTML='<div class="card"><h2>Relatório do técnico</h2><p><b>'+S(selected)+'</b><br>Gerado em '+date+'</p>'+tableHtml()+'</div>';msg('Relatório gerado.','ok')}
function copy(){if(!selected)return msg('Selecione um técnico.','bad');var eqs=equipamentosTec(selected),pends=pendTec(selected);var txt='RELATÓRIO DO TÉCNICO\nTécnico: '+selected+'\nEquipamentos em posse: '+eqs.length+'\nPendências abertas: '+pends.length+'\n\nEQUIPAMENTOS:\n'+(eqs.map(x=>'- '+(x.codigo||'')+' | '+eqName(x)+' | '+(x.mac||x.serial||'-')+' | '+(x.status||'')).join('\n')||'Sem equipamentos em posse.')+'\n\nPENDÊNCIAS:\n'+(pends.map(p=>'- '+(p.codigo||'-')+' | '+(p.motivo||'-')+' | '+(p.status||'-')).join('\n')||'Sem pendências abertas.');navigator.clipboard.writeText(txt).then(()=>msg('Relatório/coprança copiado para WhatsApp.','ok'))}
function print(){if(!selected)return msg('Selecione um técnico.','bad');if(!E('tecArea').innerHTML)report();var w=window.open('','_blank');var css='body{font-family:Segoe UI,Arial;padding:20px}table{width:100%;border-collapse:collapse;font-size:12px}td,th{border:1px solid #ddd;padding:6px}th{background:#0f4c81;color:white}@page{size:A4 landscape;margin:10mm}';w.document.write('<html><head><title>Relatório técnico</title><style>'+css+'</style></head><body>'+E('tecArea').innerHTML+'<script>setTimeout(function(){window.print()},400)<\/script></body></html>');w.document.close()}
async function add(){try{var nome=(E('tecNomeNovo').value||'').trim();if(!nome)return msg('Informe o nome do técnico.','bad');var r=await db().from('tecnicos').insert({nome:nome});if(r.error)throw r.error;E('tecNomeNovo').value='';try{await loadAll()}catch(e){}selected=nome;renderList();renderSelected();msg('Técnico adicionado.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
window.tecSelect=function(n){selected=n.replace(/&#39;/g,"'");renderList();renderSelected();view()}
window.tecDelete=async function(id,nome){nome=nome.replace(/&#39;/g,"'");var qtd=equipamentosTec(nome).length;if(qtd>0&&!confirm('Este técnico tem '+qtd+' equipamento(s) em posse. Excluir mesmo assim?'))return;if(qtd===0&&!confirm('Excluir técnico '+nome+'?'))return;try{if(id){var r=await db().from('tecnicos').delete().eq('id',id);if(r.error)throw r.error}D.tecnicos=(D.tecnicos||[]).filter(t=>t.id!==id&&t.nome!==nome);if(selected===nome)selected='';renderList();renderSelected();msg('Técnico removido da lista.','ok')}catch(e){msg('Erro ao excluir: '+e.message,'bad')}}
function msg(t,c){var m=E('tecMsg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
function bind(){css();page();nav();renderList();renderSelected();if(E('tecBusca'))E('tecBusca').oninput=renderList;if(E('tecAdd'))E('tecAdd').onclick=add;if(E('tecView'))E('tecView').onclick=view;if(E('tecReport'))E('tecReport').onclick=report;if(E('tecCopy'))E('tecCopy').onclick=copy;if(E('tecPrint'))E('tecPrint').onclick=print}
setInterval(function(){if(E('p-tecnicosFull')&&E('p-tecnicosFull').classList.contains('on'))bind();else{nav();page()}},1500);document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,2200));
})();