(function(){
function id(x){return document.getElementById(x)}
function sx(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function bx(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function nome(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
async function loadDesc(){try{D.descartes=await loadTable('descartes_autorizados','created_at',false)}catch(e){D.descartes=[]}}
function discardRows(){var arr=[];(D.descartes||[]).forEach(d=>arr.push({data:d.created_at,codigo:d.codigo,eq:d.modelo,id:d.mac||d.serial,tec:d.tecnico||'',motivo:d.motivo||'',status:d.status||'',aprov:d.aprovado_por||'',obs:d.observacao||'',valor:0}));(D.equipamentos||[]).filter(e=>['Descarte autorizado','Inutilizado'].includes(e.status)).forEach(e=>{if(!arr.some(r=>r.codigo===e.codigo))arr.push({data:'',codigo:e.codigo,eq:nome(e),id:e.mac||e.serial,tec:e.tecnicoAtual||'',motivo:e.motivoAtual||e.inutilizadoObs||'',status:e.status,aprov:'',obs:'',valor:Number(e.custo||0)})});return arr}
function htmlReport(){var rs=discardRows();var valor=rs.reduce((s,r)=>s+Number(r.valor||0),0);return '<div class="card printDiscard"><h2>Relatório de equipamentos sem funcionamento / descartados</h2><p><b>LIKE internet</b><br>Gerado em '+new Date().toLocaleString('pt-BR')+'</p><div class="gerGrid lossKpi"><div><small>Total registros</small><b>'+rs.length+'</b></div><div><small>Descartados</small><b>'+rs.filter(r=>String(r.status).toLowerCase().includes('descart')).length+'</b></div><div><small>Inutilizados</small><b>'+rs.filter(r=>r.status==='Inutilizado').length+'</b></div><div><small>Valor estimado</small><b>'+bx(valor)+'</b></div></div><div class="tbl"><table><thead><tr><th>Data</th><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Responsável</th><th>Motivo</th><th>Status</th><th>Aprovado por</th><th>Observação</th></tr></thead><tbody>'+(rs.map(r=>'<tr><td>'+(r.data?new Date(r.data).toLocaleDateString('pt-BR'):'-')+'</td><td>'+sx(r.codigo)+'</td><td>'+sx(r.eq)+'</td><td>'+sx(r.id)+'</td><td>'+sx(r.tec||'-')+'</td><td>'+sx(r.motivo)+'</td><td>'+sx(r.status)+'</td><td>'+sx(r.aprov||'-')+'</td><td>'+sx(r.obs||'')+'</td></tr>').join('')||'<tr><td colspan="9">Sem registros.</td></tr>')+'</tbody></table></div></div>'}
function renderDiscardIn(target){var e=id(target);if(e)e.innerHTML=htmlReport()}
function addGerencial(){var sel=id('reportType');if(sel&&!Array.from(sel.options).some(o=>o.value==='discarded'))sel.insertAdjacentHTML('beforeend','<option value="discarded">Descartados / sem funcionamento</option>');var btn=id('genGerReport');if(btn&&!btn.dataset.discard){btn.dataset.discard='1';var old=btn.onclick;btn.onclick=async function(){if(id('reportType')&&id('reportType').value==='discarded'){await loadDesc();renderDiscardIn('gerReportArea');var m=id('gerReportMsg');if(m){m.textContent='Relatório de descartados gerado.';m.className='msg ok'}}else if(old)old.call(this)}}}
function addButtonBaixa(){var box=id('p-descarte .card')||id('p-descarte');if(!box||id('discardReportBtn'))return;var b=document.createElement('button');b.id='discardReportBtn';b.className='ok';b.textContent='Relatório de descartados';b.onclick=async function(){await loadDesc();var area=id('discReportArea');if(!area){area=document.createElement('div');area.id='discReportArea';box.appendChild(area)}area.innerHTML=htmlReport();area.scrollIntoView({behavior:'smooth'});};box.insertBefore(b,box.children[1]||null)}
function printCss(){if(id('p41css'))return;var s=document.createElement('style');s.id='p41css';s.textContent='@media print{.side,.top,button,input,select,textarea,.msg:not(#discReportArea .msg){display:none!important}.page{display:none!important}.page.on,#p-descarte,#p-relatorios{display:block!important}.printDiscard{display:block!important;box-shadow:none!important;border:0!important}.tbl{overflow:visible!important}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#0f4c81!important;color:white!important}td,th{border:1px solid #ddd;padding:6px}.gerGrid,.lossKpi{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.gerGrid div,.lossKpi div{border:1px solid #ddd;padding:8px;border-radius:8px}}';document.head.appendChild(s)}
async function boot(){printCss();addGerencial();addButtonBaixa();}
setInterval(()=>{addGerencial();addButtonBaixa();printCss()},1200);document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1200));
})();