(function(){
function q(id){return document.getElementById(id)}
function go(p){try{pg(p)}catch(e){document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));var el=q('p-'+p);if(el)el.classList.add('on')}}
function addCss(){if(q('p39css'))return;var s=document.createElement('style');s.id='p39css';s.textContent='.p39grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.p39btn{background:white;border:1px solid #dbe4ef;border-radius:16px;padding:16px;text-align:left;cursor:pointer}.p39btn b{display:block;color:#0d1b2e;font-size:17px}.p39btn small{color:#64748b}.p39kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.p39kpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}@media(max-width:950px){.p39grid,.p39kpi{grid-template-columns:1fr}}';document.head.appendChild(s)}
function escx(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function brx(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function model(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function lastTec(e){var m=(D.movimentos||[]).find(x=>x.equipamento_id===e.id||x.codigo===e.codigo);return (m&&(m.tecnico||m.tec))||e.tecnicoAtual||''}
function exact(t){var k=N(t||'');return (D.equipamentos||[]).find(e=>N(e.codigo)===k||N(e.mac)===k||N(e.serial)===k||N(e.patrimonio)===k)}
function ensurePages(){var main=document.querySelector('.main');if(!main)return;if(!q('p-politicaEstoque')){main.insertAdjacentHTML('beforeend','<section id="p-politicaEstoque" class="page"><div class="card"><h2>Prioridade do estoque</h2><p class="small">Regra: sem registro não sai. Sem autorização não baixa. Faltou na conferência vira pendência.</p><div class="p39grid"><button class="p39btn" data-go="saidaLote"><b>Retirada controlada</b><small>Registrar antes do técnico levar.</small></button><button class="p39btn" data-go="devolucaoLote"><b>Devolução com triagem</b><small>Voltou, registrar condição.</small></button><button class="p39btn" data-go="descarte"><b>Baixa autorizada</b><small>Nada vai para lixo sem registro.</small></button><button class="p39btn" data-go="conferenciaTec"><b>Conferir técnico</b><small>Bipar mochila/carro.</small></button><button class="p39btn" data-go="pendencias"><b>Pendências</b><small>Cobrar faltantes.</small></button><button class="p39btn" data-go="perdasTec"><b>Relatório por técnico</b><small>Perdas e responsabilidade.</small></button></div></div></section>')}
if(!q('p-descarte')){main.insertAdjacentHTML('beforeend','<section id="p-descarte" class="page"><div class="card"><h2>Baixa / descarte autorizado</h2><input id="discSearch" placeholder="Digite ou bipe MAC, SN, código ou patrimônio"><div id="discPrev" class="msg">Pesquise o equipamento.</div><select id="discMotivo"><option>Queimado</option><option>Quebrado</option><option>Oxidação</option><option>Dano físico</option><option>Sem reparo</option><option>Extraviado</option><option>Outro</option></select><input id="discSolic" placeholder="Solicitado por"><input id="discAprov" placeholder="Aprovado por"><textarea id="discObs" placeholder="Observação"></textarea><button id="discSolicitar" class="warn">Registrar solicitação</button><button id="discAprovar" class="bad">Aprovar baixa</button><div id="discMsg" class="msg"></div><h3>Registros</h3><div class="tbl"><table><thead><tr><th>Data</th><th>Código</th><th>Responsável</th><th>Motivo</th><th>Status</th></tr></thead><tbody id="discTable"></tbody></table></div></div></section>')}
if(!q('p-perdasTec')){main.insertAdjacentHTML('beforeend','<section id="p-perdasTec" class="page"><div class="card"><h2>Relatório de perdas por técnico</h2><div class="grid4"><select id="lossTec"></select><button id="lossGen" class="pri">Gerar relatório</button><button id="lossPrint" class="ok">Imprimir/PDF</button><button id="lossCopy" class="warn">Copiar resumo</button></div><div id="lossArea"></div></div></section>')}
var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="politicaEstoque"]')){var h=document.querySelector('[data-p="historico"]');(h||side.lastElementChild).insertAdjacentHTML('beforebegin','<button class="nav" data-p="politicaEstoque">Prioridade estoque</button><button class="nav" data-p="descarte">Baixa autorizada</button><button class="nav" data-p="perdasTec">Perdas por técnico</button>')}
var op=q('p-operacao');if(op&&!q('p39quick')){var grid=op.querySelector('.opGrid');if(grid)grid.insertAdjacentHTML('afterbegin','<div id="p39quick" class="opBtn" data-go="politicaEstoque"><div class="opIcon">🔒</div><b>Prioridade estoque</b><span>Sem registro não sai.</span></div><div class="opBtn" data-go="descarte"><div class="opIcon">🧾</div><b>Baixa autorizada</b><span>Registrar descarte.</span></div><div class="opBtn" data-go="perdasTec"><div class="opIcon">📉</div><b>Perdas por técnico</b><span>Relatório de responsabilidade.</span></div>')}}
function loadDisc(){return loadTable('descartes_autorizados','created_at',false).then(x=>{D.descartes=x}).catch(()=>{D.descartes=[]})}
function renderDisc(){var t=q('discTable');if(!t)return;t.innerHTML=(D.descartes||[]).map(d=>'<tr><td>'+new Date(d.created_at).toLocaleDateString('pt-BR')+'</td><td>'+escx(d.codigo)+'</td><td>'+escx(d.tecnico||'-')+'</td><td>'+escx(d.motivo)+'</td><td>'+escx(d.status)+'</td></tr>').join('')||'<tr><td colspan="5">Nenhum registro.</td></tr>'}
var selected=null;function prev(){selected=exact(q('discSearch')?.value);var p=q('discPrev');if(!p)return;if(!selected){p.textContent='Equipamento não encontrado.';p.className='msg bad'}else{p.innerHTML='<b>'+escx(selected.codigo)+' - '+escx(model(selected))+'</b><br>'+escx(selected.mac||selected.serial||'')+' | responsável provável: '+escx(lastTec(selected)||'-');p.className='msg ok'}}
async function saveDisc(ap){try{if(!selected)prev();if(!selected){var m=q('discMsg');if(m){m.textContent='Pesquise um equipamento válido.';m.className='msg bad'}return}var aprovado=q('discAprov')?.value||'';if(ap&&!ap){q('discMsg').textContent='Informe quem aprovou.';q('discMsg').className='msg bad';return}var tec=lastTec(selected)||selected.tecnicoAtual||'';var r={equipamento_id:selected.id,codigo:selected.codigo,mac:selected.mac,serial:selected.serial,modelo:model(selected),tecnico:tec,solicitado_por:q('discSolic')?.value||'',aprovado_por:aprovado,motivo:q('discMotivo')?.value||'',status:ap?'Descartado':'Solicitado',observacao:q('discObs')?.value||'',aprovado_em:ap?new Date().toISOString():null,descartado_em:ap?new Date().toISOString():null};var x=await db().from('descartes_autorizados').insert(r);if(x.error)throw x.error;if(ap){selected.status='Descarte autorizado';selected.local='Descarte autorizado';selected.motivoAtual=r.motivo;Object.assign(selected,fromEq(await upd('equipamentos',selected.id,toEq(selected))));await mov(selected,'Descarte autorizado',{tec:tec,dest:'Descarte autorizado',mot:r.motivo,obs:'Aprovado por '+aprovado})}await loadDisc();renderDisc();q('discMsg').textContent=ap?'Baixa aprovada.':'Solicitação registrada.';q('discMsg').className='msg ok'}catch(e){q('discMsg').textContent='Erro: '+e.message;q('discMsg').className='msg bad'}}
function fillLoss(){var s=q('lossTec');if(!s)return;var old=s.value;var arr=[];(D.tecnicos||[]).forEach(t=>{if(t.nome)arr.push(t.nome)});(D.pendencias||[]).forEach(p=>{if(p.tecnico)arr.push(p.tecnico)});(D.descartes||[]).forEach(d=>{if(d.tecnico)arr.push(d.tecnico)});(D.equipamentos||[]).forEach(e=>{var n=lastTec(e);if(n)arr.push(n)});arr=Array.from(new Set(arr)).sort();s.innerHTML='<option value="">Todos</option>'+arr.map(n=>'<option>'+escx(n)+'</option>').join('');if([...s.options].some(o=>o.value===old))s.value=old}
function rows(){var r=[];(D.pendencias||[]).forEach(p=>{if(['Aberta','Cobrar valor','Divergente'].includes(p.status))r.push({o:'Pendência',t:p.tecnico||'-',c:p.codigo||'',e:p.modelo||'',id:p.mac||p.serial||'',s:p.status,m:p.motivo||'',v:Number(p.valor_estimado||0)})});(D.descartes||[]).forEach(d=>r.push({o:'Baixa',t:d.tecnico||'-',c:d.codigo||'',e:d.modelo||'',id:d.mac||d.serial||'',s:d.status,m:d.motivo||'',v:0}));(D.equipamentos||[]).forEach(e=>{if(['Perdido','Inutilizado','Descarte autorizado'].includes(e.status))r.push({o:'Equipamento',t:lastTec(e)||'-',c:e.codigo||'',e:model(e),id:e.mac||e.serial||'',s:e.status,m:e.motivoAtual||e.inutilizadoObs||'',v:Number(e.custo||0)})});return r}
function gen(){var area=q('lossArea');if(!area)return;var tec=q('lossTec')?.value||'';var rs=rows().filter(x=>!tec||x.t===tec);var val=rs.reduce((a,b)=>a+b.v,0);area.innerHTML='<div class="p39kpi"><div><small>Pendências abertas</small><b>'+rs.filter(x=>x.s==='Aberta').length+'</b></div><div><small>Cobrar valor</small><b>'+rs.filter(x=>x.s==='Cobrar valor').length+'</b></div><div><small>Ocorrências</small><b>'+rs.length+'</b></div><div><small>Valor estimado</small><b>'+brx(val)+'</b></div></div><div class="tbl"><table><thead><tr><th>Origem</th><th>Responsável</th><th>Código</th><th>Equipamento</th><th>Status/Motivo</th><th>Valor</th></tr></thead><tbody>'+(rs.map(x=>'<tr><td>'+escx(x.o)+'</td><td>'+escx(x.t)+'</td><td>'+escx(x.c)+'</td><td>'+escx(x.e)+'<br><small>'+escx(x.id)+'</small></td><td>'+escx(x.s)+'<br><small>'+escx(x.m)+'</small></td><td>'+brx(x.v)+'</td></tr>').join('')||'<tr><td colspan="6">Sem ocorrências.</td></tr>')+'</tbody></table></div>'}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>{b.onclick=()=>go(b.dataset.go)});document.querySelectorAll('.nav').forEach(b=>{b.onclick=()=>go(b.dataset.p)});if(q('discSearch')&&!q('discSearch').dataset.ok){q('discSearch').dataset.ok='1';q('discSearch').oninput=prev;q('discSearch').onkeydown=e=>{if(e.key==='Enter')prev()}}if(q('discSolicitar'))q('discSolicitar').onclick=()=>saveDisc(false);if(q('discAprovar'))q('discAprovar').onclick=()=>saveDisc(true);if(q('lossGen'))q('lossGen').onclick=gen;if(q('lossCopy'))q('lossCopy').onclick=()=>{var t=q('lossArea')?.innerText||'';if(t)navigator.clipboard.writeText(t)};if(q('lossPrint'))q('lossPrint').onclick=()=>{if(!q('lossArea')?.innerHTML)gen();window.print()}}
async function boot(){addCss();ensurePages();bind();try{await loadDisc()}catch(e){}renderDisc();fillLoss();bind()}
setInterval(()=>{ensurePages();bind();fillLoss();renderDisc()},1200);document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,800));
})();