/* LIKE Estoque V30 - edição inline, relatório técnico e relatórios gerenciais */
(function(){
  const statusList=['Em estoque','Com técnico','Instalado cliente','Na rua','Reservado','Em manutenção','Inutilizado','Perdido'];
  function byId(id){return document.getElementById(id)}
  function E(v){return esc(v??'')}
  function opt(list,val,placeholder=''){return (placeholder?`<option value="">${placeholder}</option>`:'')+list.map(x=>`<option value="${E(x)}" ${x===val?'selected':''}>${E(x)}</option>`).join('')}
  function locOpts(val){return opt(D.locais.map(l=>l.nome),val,'Local')}
  function tecOpts(val){return opt(D.tecnicos.map(t=>t.nome),val,'Técnico')}
  function modelFull(e){return `${E(e.tipo)} ${E(e.marca)} ${E(e.modelo)}`}
  function rawModel(e){return `${e.tipo||''} ${e.marca||''} ${e.modelo||''}`.trim()}
  function lastMovement(e){return D.movimentos.find(m=>m.equipamento_id===e.id||m.codigo===e.codigo)||null}
  function daysSince(dateStr){if(!dateStr)return null;const d=new Date(dateStr+'T00:00:00');if(isNaN(d))return null;return Math.floor((Date.now()-d.getTime())/86400000)}
  function addStyle(){if(byId('patch29style'))return;const s=document.createElement('style');s.id='patch29style';s.textContent=`.inlineInput,.inlineSelect{min-width:120px;padding:7px;border:1px solid #cbd5e1;border-radius:8px;margin:0}.inlineSmall{min-width:80px}.saveOk{outline:2px solid #22c55e}.reportHead{display:grid;grid-template-columns:1.2fr repeat(3,.6fr);gap:10px;margin:12px 0}.reportKpi,.gerKpi{border:1px solid #dbe4ef;background:#f8fafc;border-radius:16px;padding:12px}.reportKpi b,.gerKpi b{font-size:24px;display:block}.reportWarn{background:#fff7ed;border:1px solid #fed7aa;border-radius:14px;padding:12px;margin:10px 0}.signatureGrid{display:grid;grid-template-columns:1fr 1fr;gap:30px;margin-top:40px}.lineSign{border-top:1px solid #111;padding-top:8px;text-align:center}.gerGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:10px 0}.rankGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.reportToolbar{display:grid;grid-template-columns:1fr 170px 170px auto auto auto;gap:8px;align-items:end}.dangerText{color:#991b1b;font-weight:900}.okText{color:#166534;font-weight:900}@media print{#reportArea .card,#gerReportArea .card{box-shadow:none;border:0}.reportHead,.gerGrid{grid-template-columns:repeat(4,1fr)}button,.quickTop,.side,.top,.reportToolbar{display:none!important}}@media(max-width:950px){.reportToolbar,.gerGrid,.rankGrid{grid-template-columns:1fr}}`;document.head.appendChild(s)}

  window.saveInlineEq=async function(id){try{const e=D.equipamentos.find(x=>x.id===id); if(!e)return;const prefix='in_'+id.replaceAll('-','_')+'_';const oldStatus=e.status;e.status=byId(prefix+'status').value;e.local=byId(prefix+'local').value;e.tecnicoAtual=byId(prefix+'tec')?.value||'';e.clienteAtual=byId(prefix+'cli')?.value.trim()||'';e.osAtual=byId(prefix+'os')?.value.trim()||'';e.custo=Number(byId(prefix+'custo')?.value||e.custo||0);if(e.status==='Em estoque'){e.tecnicoAtual='';e.clienteAtual=''}if(['Inutilizado','Perdido'].includes(e.status)){e.local=e.status}Object.assign(e,fromEq(await upd('equipamentos',id,toEq(e))));await mov(e,'Edição inline',{tec:e.tecnicoAtual,dest:e.local,cli:e.clienteAtual,os:e.osAtual,mot:'Edição na tabela',obs:`Alterado na própria tabela. Status anterior: ${oldStatus}`});render()}catch(err){alert('Erro ao salvar: '+err.message)}};
  window.cancelInlineRender=function(){render()};
  function inlineRow(e,mode='full'){const p='in_'+e.id.replaceAll('-','_')+'_';const macsn=E(e.mac||e.serial||'');const actions=`<button class="ok" onclick="saveInlineEq('${e.id}')">Salvar</button><button onclick="showEqHistory('${e.id}')">Histórico</button><button class="warn" onclick="inutilizarEq('${e.id}')">Inutilizar</button>`;if(mode==='central')return `<tr><td><b>${E(e.codigo)}</b></td><td>${modelFull(e)}</td><td>${macsn}</td><td>${E(e.patrimonio)}</td><td><input id="${p}custo" class="inlineInput inlineSmall" type="number" value="${E(e.custo||0)}"></td><td><select id="${p}status" class="inlineSelect">${opt(statusList,e.status)}</select><select id="${p}local" class="inlineSelect">${locOpts(e.local)}</select>${actions}</td></tr>`;return `<tr><td><b>${E(e.codigo)}</b><br><small>${E(e.patrimonio||'')}</small></td><td>${E(e.tipo)}</td><td>${E(e.marca)}</td><td>${E(e.modelo)}</td><td>${E(e.mac||'')}</td><td>${E(e.serial||'')}</td><td><select id="${p}status" class="inlineSelect">${opt(statusList,e.status)}</select></td><td><select id="${p}local" class="inlineSelect">${locOpts(e.local)}</select></td><td><select id="${p}tec" class="inlineSelect">${tecOpts(e.tecnicoAtual)}</select></td><td><input id="${p}cli" class="inlineInput" value="${E(e.clienteAtual||'')}" placeholder="Cliente/backup"><input id="${p}os" class="inlineInput inlineSmall" value="${E(e.osAtual||'')}" placeholder="OS"><input id="${p}custo" class="inlineInput inlineSmall" type="number" value="${E(e.custo||0)}" placeholder="Custo"></td><td>${actions}</td></tr>`}
  function renderInlineTables(){const est=D.equipamentos.filter(e=>e.status==='Em estoque');const f=N(byId('f')?.value||'');if(byId('eqT'))byId('eqT').innerHTML=D.equipamentos.filter(e=>N(Object.values(e).join(' ')).includes(f)).map(e=>inlineRow(e)).join('')||'<tr><td colspan="11">Nenhum equipamento.</td></tr>';if(byId('estT'))byId('estT').innerHTML=est.map(e=>inlineRow(e,'central')).join('')||'<tr><td colspan="6">Nenhum item em estoque.</td></tr>'}

  function techReportData(tec){const itens=D.equipamentos.filter(e=>e.tecnicoAtual===tec&&!['Em estoque','Inutilizado','Perdido'].includes(e.status));const valor=itens.reduce((s,e)=>s+Number(e.custo||0),0);const byStatus={};itens.forEach(e=>byStatus[e.status]=(byStatus[e.status]||0)+1);const rows=itens.map(e=>{const lm=lastMovement(e);const dias=daysSince(lm?.data);return {e,lm,dias}}).sort((a,b)=>(b.dias||0)-(a.dias||0));return {itens,valor,byStatus,rows,criticos:rows.filter(r=>(r.dias||0)>=15)}}
  window.generateBetterReport=function(){const sel=byId('reportTec'); const tec=sel?.value;if(!tec){byId('reportMsg').textContent='Escolha um técnico.';byId('reportMsg').className='msg bad';byId('reportArea').innerHTML='';return}const data=techReportData(tec);byId('reportMsg').textContent=`Relatório gerado: ${data.itens.length} item(ns), ${data.criticos.length} pendência(s) acima de 15 dias.`;byId('reportMsg').className='msg ok';const statusHtml=Object.entries(data.byStatus).map(([s,q])=>`<span class="status">${E(s)}: ${q}</span>`).join(' ')||'<span class="status ok">Sem itens</span>';const critHtml=data.criticos.length?`<div class="reportWarn"><b>Atenção:</b> ${data.criticos.length} equipamento(s) estão há 15 dias ou mais desde a última movimentação. Priorizar conferência física e devolução.</div>`:'';byId('reportArea').innerHTML=`<div class="card"><h2>Relatório de responsabilidade técnica</h2><p><b>Técnico:</b> ${E(tec)}<br><b>Empresa:</b> LIKE internet<br><b>Data:</b> ${new Date().toLocaleString('pt-BR')}</p><div class="reportHead"><div class="reportKpi"><small>Status</small><br>${statusHtml}</div><div class="reportKpi"><small>Itens em posse</small><b>${data.itens.length}</b></div><div class="reportKpi"><small>Valor estimado</small><b>${br(data.valor)}</b></div><div class="reportKpi"><small>Pendências 15+ dias</small><b>${data.criticos.length}</b></div></div>${critHtml}<div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Cliente/OS</th><th>Última mov.</th><th>Dias</th><th>Observação conferência</th></tr></thead><tbody>${data.rows.map(r=>`<tr class="${(r.dias||0)>=15?'warnLine':''}"><td>${E(r.e.codigo)}</td><td>${modelFull(r.e)}</td><td>${E(r.e.mac||r.e.serial||'')}</td><td>${E(r.e.status)}</td><td>${E(r.e.local||'')}</td><td>${E(r.e.clienteAtual||'')} ${E(r.e.osAtual||'')}</td><td>${r.lm?E(r.lm.data)+' - '+E(r.lm.tipo):'Sem histórico'}</td><td>${r.dias??'-'}</td><td>☐ Conferido &nbsp; ☐ Devolver &nbsp; ☐ Divergente</td></tr>`).join('')||'<tr><td colspan="9">Sem itens em posse.</td></tr>'}</tbody></table></div><div class="signatureGrid"><div class="lineSign">Assinatura do técnico</div><div class="lineSign">Conferente / Estoquista</div></div></div>`};
  function hookReport(){const btn=byId('reportBtn'); if(btn)btn.onclick=window.generateBetterReport;const print=byId('printReport'); if(print)print.onclick=()=>{if(!byId('reportArea')?.innerHTML.trim())window.generateBetterReport();setTimeout(()=>window.print(),150)};const copy=byId('copyReport'); if(copy)copy.onclick=()=>navigator.clipboard.writeText(byId('reportArea')?.innerText||'')}

  function parseDate(d){return d?new Date(d+'T00:00:00'):null}
  function inPeriod(date,start,end){if(!date)return false;const d=parseDate(date);if(!d)return false;if(start&&d<parseDate(start))return false;if(end&&d>parseDate(end))return false;return true}
  function sumCost(list){return list.reduce((s,e)=>s+Number(e.custo||0),0)}
  function countBy(list,fn){const o={};list.forEach(x=>{const k=fn(x)||'Sem informação';o[k]=(o[k]||0)+1});return o}
  function topEntries(obj,n=5){return Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,n)}
  function table(headers,rows){return `<div class="tbl"><table><thead><tr>${headers.map(h=>`<th>${E(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">Sem dados.</td></tr>`}</tbody></table></div>`}
  function kpi(label,value,cls=''){return `<div class="gerKpi"><small>${E(label)}</small><b class="${cls}">${value}</b></div>`}
  function reportHeader(title){const s=byId('repStart')?.value||'';const e=byId('repEnd')?.value||'';return `<div class="card"><h2>${E(title)}</h2><p><b>LIKE internet</b><br>Gerado em ${new Date().toLocaleString('pt-BR')}${s||e?`<br>Período: ${E(s||'início')} até ${E(e||'hoje')}`:''}</p>`}
  function rowsFromObj(obj){return topEntries(obj,999).map(([k,v])=>[E(k),v])}
  function periodMovs(){const s=byId('repStart')?.value||'',e=byId('repEnd')?.value||'';return D.movimentos.filter(m=>!s&&!e?true:inPeriod(m.data,s,e))}
  function reportExecutive(){const eq=D.equipamentos, est=eq.filter(e=>e.status==='Em estoque'), tec=eq.filter(e=>e.tecnicoAtual&&!['Em estoque','Inutilizado','Perdido'].includes(e.status)), rua=eq.filter(e=>['Na rua','Instalado cliente','Reservado'].includes(e.status)), manut=eq.filter(e=>e.status==='Em manutenção'), perd=eq.filter(e=>['Inutilizado','Perdido'].includes(e.status));const abaixo=D.modelos.map(m=>{const qtd=est.filter(e=>e.tipo===m.tipo&&e.marca===m.marca&&e.modelo===m.modelo).length;return {m,qtd,min:Number(m.estoque_minimo||0),ideal:Number(m.estoque_ideal||0)}}).filter(x=>x.min&&x.qtd<x.min);const techRank=topEntries(countBy(tec,e=>e.tecnicoAtual),5);const lossRank=topEntries(countBy(perd,e=>e.motivoAtual||e.inutilizadoObs||e.status),5);return reportHeader('Resumo executivo do estoque')+`<div class="gerGrid">${kpi('Total equipamentos',eq.length)}${kpi('Valor estimado total',br(sumCost(eq)))}${kpi('Estoque central',est.length)}${kpi('Valor no estoque',br(sumCost(est)))}${kpi('Com técnicos',tec.length)}${kpi('Valor com técnicos',br(sumCost(tec)))}${kpi('Na rua/cliente',rua.length)}${kpi('Manutenção',manut.length)}${kpi('Inutilizado/perdido',perd.length,'dangerText')} ${kpi('Retorno sem cadastro',eq.filter(e=>e.retorno_sem_cadastro||e.origem==='Retorno sem cadastro anterior').length)}</div><div class="rankGrid"><div><h3>Modelos abaixo do mínimo</h3>${table(['Modelo','Atual','Mínimo','Comprar p/ ideal'],abaixo.slice(0,5).map(x=>[E(`${x.m.tipo} ${x.m.marca} ${x.m.modelo}`),x.qtd,x.min,Math.max(0,x.ideal-x.qtd)]))}</div><div><h3>Técnicos com mais itens</h3>${table(['Técnico','Qtd'],techRank.map(([k,v])=>[E(k),v]))}</div><div><h3>Principais perdas/inutilizações</h3>${table(['Motivo','Qtd'],lossRank.map(([k,v])=>[E(k),v]))}</div></div></div>`}
  function reportModels(){const est=D.equipamentos.filter(e=>e.status==='Em estoque');const rows=D.modelos.map(m=>{const all=D.equipamentos.filter(e=>e.tipo===m.tipo&&e.marca===m.marca&&e.modelo===m.modelo);const qEst=all.filter(e=>e.status==='Em estoque').length,qTec=all.filter(e=>e.tecnicoAtual&&!['Em estoque','Inutilizado','Perdido'].includes(e.status)).length,qRua=all.filter(e=>['Na rua','Instalado cliente','Reservado'].includes(e.status)).length,qMan=all.filter(e=>e.status==='Em manutenção').length,min=Number(m.estoque_minimo||0),ideal=Number(m.estoque_ideal||0);const sit=min&&qEst<min?'<span class="dangerText">Crítico</span>':(ideal&&qEst<ideal?'Abaixo do ideal':'OK');return [E(`${m.tipo} ${m.marca} ${m.modelo}`),qEst,qTec,qRua,qMan,min,ideal,Math.max(0,ideal-qEst),sit]});return reportHeader('Estoque por tipo / marca / modelo')+table(['Modelo','Estoque','Com técnico','Rua/cliente','Manutenção','Mínimo','Ideal','Comprar','Situação'],rows)+'</div>'}
  function reportMovements(){const movs=periodMovs();const by=countBy(movs,m=>m.tipo);const rows=rowsFromObj(by);return reportHeader('Movimentações do período')+`<div class="gerGrid">${kpi('Movimentações',movs.length)}${kpi('Entradas',movs.filter(m=>/entrada/i.test(m.tipo)).length)}${kpi('Saídas',movs.filter(m=>/saída|saida/i.test(m.tipo)).length)}${kpi('Devoluções',movs.filter(m=>/devolução|devolucao/i.test(m.tipo)).length)}</div>`+table(['Movimento','Quantidade'],rows)+table(['Data','Tipo','Código','MAC/SN','Técnico','Destino','OS','Obs'],movs.slice(0,300).map(m=>[E(m.data||''),E(m.tipo||''),E(m.codigo||''),E(m.mac||m.serial||''),E(m.tecnico||''),E(m.destino||''),E(m.os||''),E(m.obs||'')]))+'</div>'}
  function reportLosses(){const eq=D.equipamentos.filter(e=>['Inutilizado','Perdido'].includes(e.status));const by=countBy(eq,e=>e.motivoAtual||e.inutilizadoObs||e.status);return reportHeader('Perdas e inutilizados')+`<div class="gerGrid">${kpi('Itens perdidos/inutilizados',eq.length,'dangerText')}${kpi('Valor estimado perdido',br(sumCost(eq)),'dangerText')}</div>`+table(['Motivo','Qtd'],rowsFromObj(by))+table(['Código','Modelo','MAC/SN','Status','Motivo','Valor'],eq.map(e=>[E(e.codigo),modelFull(e),E(e.mac||e.serial||''),E(e.status),E(e.motivoAtual||e.inutilizadoObs||''),br(e.custo||0)]))+'</div>'}
  function reportMaintenance(){const eq=D.equipamentos.filter(e=>e.status==='Em manutenção');const rows=eq.map(e=>{const lm=lastMovement(e),dias=daysSince(lm?.data);return {e,lm,dias}}).sort((a,b)=>(b.dias||0)-(a.dias||0));return reportHeader('Manutenção / teste')+`<div class="gerGrid">${kpi('Em manutenção',eq.length)}${kpi('Valor parado',br(sumCost(eq)))}${kpi('15+ dias',rows.filter(r=>(r.dias||0)>=15).length,'dangerText')}</div>`+table(['Código','Modelo','MAC/SN','Dias parado','Última mov.','Motivo'],rows.map(r=>[E(r.e.codigo),modelFull(r.e),E(r.e.mac||r.e.serial||''),r.dias??'-',r.lm?E(r.lm.data)+' - '+E(r.lm.tipo):'Sem histórico',E(r.e.motivoAtual||r.e.inutilizadoObs||'')]))+'</div>'}
  function reportReturnLegacy(){const eq=D.equipamentos.filter(e=>e.retorno_sem_cadastro||e.origem==='Retorno sem cadastro anterior');const byCond=countBy(eq,e=>e.condicaoRetorno||e.motivoAtual||'Sem condição');return reportHeader('Retornos sem cadastro')+`<div class="gerGrid">${kpi('Regularizados',eq.length)}${kpi('Valor recuperado estimado',br(sumCost(eq)))}${kpi('Funcionando',eq.filter(e=>/funcionando|novo/i.test(e.condicaoRetorno||e.motivoAtual||'')).length)}${kpi('Defeito/inutilizado',eq.filter(e=>/defeito|quebrado|inutilizado|perdido/i.test((e.condicaoRetorno||e.motivoAtual||'')+' '+e.status)).length,'dangerText')}</div>`+table(['Condição','Qtd'],rowsFromObj(byCond))+table(['Data','Código','Modelo','MAC/SN','Técnico devolução','Condição','Destino'],eq.map(e=>[E(e.retorno_data||''),E(e.codigo),modelFull(e),E(e.mac||e.serial||''),E(e.tecnicoDevolucao||e.tecnicoAtual||''),E(e.condicaoRetorno||e.motivoAtual||''),E(e.local||e.status)]))+'</div>'}
  function reportQuality(){const eq=D.equipamentos;const problems=[['Sem MAC',eq.filter(e=>!e.mac).length],['Sem Serial/SN',eq.filter(e=>!e.serial).length],['Sem custo',eq.filter(e=>!Number(e.custo||0)).length],['Na rua sem cliente/OS',eq.filter(e=>['Na rua','Instalado cliente','Reservado'].includes(e.status)&&!e.clienteAtual&&!e.osAtual).length],['Com técnico sem técnico',eq.filter(e=>e.status==='Com técnico'&&!e.tecnicoAtual).length],['Em estoque com técnico preenchido',eq.filter(e=>e.status==='Em estoque'&&e.tecnicoAtual).length],['Sem histórico',eq.filter(e=>!lastMovement(e)).length]];const detail=eq.filter(e=>!e.mac||!e.serial||!Number(e.custo||0)||(['Na rua','Instalado cliente','Reservado'].includes(e.status)&&!e.clienteAtual&&!e.osAtual)||(e.status==='Com técnico'&&!e.tecnicoAtual)||(e.status==='Em estoque'&&e.tecnicoAtual)||!lastMovement(e));return reportHeader('Qualidade cadastral e divergências')+table(['Problema','Quantidade'],problems.map(x=>[E(x[0]),x[1]]))+table(['Código','Modelo','MAC','SN','Status','Técnico','Problema provável'],detail.slice(0,500).map(e=>[E(e.codigo),modelFull(e),E(e.mac||''),E(e.serial||''),E(e.status),E(e.tecnicoAtual||''),E([!e.mac?'sem MAC':'',!e.serial?'sem SN':'',!Number(e.custo||0)?'sem custo':'',!lastMovement(e)?'sem histórico':''].filter(Boolean).join(', '))]))+'</div>'}
  function reportDaily(){const date=byId('repStart')?.value||new Date().toISOString().slice(0,10);const movs=D.movimentos.filter(m=>m.data===date);return reportHeader('Fechamento diário')+`<div class="gerGrid">${kpi('Data',E(date))}${kpi('Movimentações',movs.length)}${kpi('Entradas',movs.filter(m=>/entrada/i.test(m.tipo)).length)}${kpi('Saídas',movs.filter(m=>/saída|saida/i.test(m.tipo)).length)}${kpi('Devoluções',movs.filter(m=>/devolução|devolucao/i.test(m.tipo)).length)}${kpi('Retorno sem cadastro',movs.filter(m=>/retorno sem cadastro/i.test(m.tipo)).length)}${kpi('Inutilizações',movs.filter(m=>/inutil/i.test(m.tipo)).length)}${kpi('Saldo estoque central',D.equipamentos.filter(e=>e.status==='Em estoque').length)}</div>`+table(['Data','Tipo','Código','MAC/SN','Técnico','Destino','Obs'],movs.map(m=>[E(m.data||''),E(m.tipo||''),E(m.codigo||''),E(m.mac||m.serial||''),E(m.tecnico||''),E(m.destino||''),E(m.obs||'')]))+'</div>'}
  function addReportsPage(){const hist=document.querySelector('[data-p="historico"]');const main=document.querySelector('.main');if(!hist||!main||byId('p-relatorios'))return;hist.insertAdjacentHTML('beforebegin','<button class="nav" data-p="relatorios">Relatórios gerenciais</button>');main.insertAdjacentHTML('beforeend',`<section id="p-relatorios" class="page"><div class="card"><h2>Relatórios gerenciais</h2><p class="small">Relatórios para apresentar gestão, controle por técnico, perdas, movimentações e qualidade do estoque.</p><div class="reportToolbar"><select id="reportType"><option value="executive">Resumo executivo</option><option value="models">Estoque por modelo</option><option value="movements">Movimentações por período</option><option value="losses">Perdas/Inutilizados</option><option value="maintenance">Manutenção parada</option><option value="legacy">Retorno sem cadastro</option><option value="quality">Qualidade/Divergências</option><option value="daily">Fechamento diário</option></select><input id="repStart" type="date"><input id="repEnd" type="date"><button id="genGerReport" class="pri">Gerar</button><button id="printGerReport" class="ok">Imprimir/PDF</button><button id="csvGerReport" class="warn">Exportar CSV</button></div><div id="gerReportMsg" class="msg">Escolha o relatório e clique em Gerar.</div><div id="gerReportArea" class="printArea"></div></div></section>`);document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>pg(b.dataset.p));byId('genGerReport').onclick=generateGerReport;byId('printGerReport').onclick=()=>{if(!byId('gerReportArea').innerHTML.trim())generateGerReport();setTimeout(()=>window.print(),150)};byId('csvGerReport').onclick=exportGerCsv}
  function generateGerReport(){const type=byId('reportType')?.value;let html='';if(type==='executive')html=reportExecutive();if(type==='models')html=reportModels();if(type==='movements')html=reportMovements();if(type==='losses')html=reportLosses();if(type==='maintenance')html=reportMaintenance();if(type==='legacy')html=reportReturnLegacy();if(type==='quality')html=reportQuality();if(type==='daily')html=reportDaily();byId('gerReportArea').innerHTML=html;byId('gerReportMsg').textContent='Relatório gerado.';byId('gerReportMsg').className='msg ok'}
  function exportGerCsv(){if(!byId('gerReportArea')?.innerText.trim())generateGerReport();const rows=[...byId('gerReportArea').querySelectorAll('table tr')].map(tr=>[...tr.children].map(td=>'"'+td.innerText.replaceAll('"','""')+'"').join(';')).join('\n');const blob=new Blob([rows||byId('gerReportArea').innerText],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='relatorio-like-estoque.csv';a.click();URL.revokeObjectURL(a.href)}

  const oldRender29=render;
  render=function(){oldRender29();renderInlineTables();hookReport();addReportsPage()};
  document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{addStyle();renderInlineTables();hookReport();addReportsPage()},500));
})();