(function(){
function el(i){return document.getElementById(i)}
function sx(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function bx(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function k(v){try{return N(v||'')}catch(e){return String(v||'').toLowerCase().trim()}}
function mod(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function findEq(t){var kk=k(t);return (D.equipamentos||[]).find(function(e){return k(e.codigo)===kk||k(e.patrimonio)===kk||k(e.mac)===kk||k(e.serial)===kk})}
function resp(e){var m=(D.movimentos||[]).find(function(x){return x.equipamento_id===e.id||x.codigo===e.codigo});return (m&&(m.tecnico||m.tec))||e.tecnicoAtual||''}
async function loadDesc(){try{D.descartes=await loadTable('descartes_autorizados','created_at',false)}catch(e){D.descartes=[]}}
function css(){if(el('p42css'))return;var s=document.createElement('style');s.id='p42css';s.textContent='.baixa42Steps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.baixa42Steps div{background:#f8fafc;border:1px solid #dbe4ef;border-radius:12px;padding:10px}.baixa42Grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.baixa42Prev{border:1px solid #dbe4ef;border-radius:14px;background:#f8fafc;padding:12px;margin:8px 0}.baixa42Warn{background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;padding:10px;margin:8px 0}.baixa42Report{margin-top:14px}@media(max-width:950px){.baixa42Steps,.baixa42Grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
var chosen=null;
function rows(){var a=[];(D.descartes||[]).forEach(function(d){a.push({dt:d.created_at,cod:d.codigo,eq:d.modelo,id:d.mac||d.serial,tec:d.tecnico||'',mot:d.motivo||'',st:d.status||'',ap:d.aprovado_por||'',obs:d.observacao||'',val:0})});(D.equipamentos||[]).filter(function(e){return ['Descarte autorizado','Inutilizado'].includes(e.status)}).forEach(function(e){if(!a.some(function(r){return r.cod===e.codigo}))a.push({dt:'',cod:e.codigo,eq:mod(e),id:e.mac||e.serial,tec:resp(e)||e.tecnicoAtual||'',mot:e.motivoAtual||e.inutilizadoObs||'',st:e.status,ap:'',obs:'',val:Number(e.custo||0)})});return a}
function reportHtml(){var r=rows();var val=r.reduce(function(s,x){return s+Number(x.val||0)},0);return '<div class="baixa42Report"><h2>Relatório de equipamentos sem funcionamento / descartados</h2><p><b>LIKE internet</b><br>Gerado em '+new Date().toLocaleString('pt-BR')+'</p><div class="p39kpi"><div><small>Total</small><b>'+r.length+'</b></div><div><small>Descartados</small><b>'+r.filter(x=>String(x.st).toLowerCase().includes('descart')).length+'</b></div><div><small>Inutilizados</small><b>'+r.filter(x=>x.st==='Inutilizado').length+'</b></div><div><small>Valor estimado</small><b>'+bx(val)+'</b></div></div><div class="tbl"><table><thead><tr><th>Data</th><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Responsável</th><th>Motivo</th><th>Status</th><th>Aprovado por</th><th>Obs</th></tr></thead><tbody>'+(r.map(function(x){return '<tr><td>'+(x.dt?new Date(x.dt).toLocaleDateString('pt-BR'):'-')+'</td><td>'+sx(x.cod)+'</td><td>'+sx(x.eq)+'</td><td>'+sx(x.id)+'</td><td>'+sx(x.tec||'-')+'</td><td>'+sx(x.mot)+'</td><td>'+sx(x.st)+'</td><td>'+sx(x.ap||'-')+'</td><td>'+sx(x.obs)+'</td></tr>'}).join('')||'<tr><td colspan="9">Sem registros.</td></tr>')+'</tbody></table></div></div>'}
function stableTable(){var t=el('baixa42Table');if(!t)return;var r=rows().slice(0,80);t.innerHTML=r.map(function(x){return '<tr><td>'+(x.dt?new Date(x.dt).toLocaleDateString('pt-BR'):'-')+'</td><td><b>'+sx(x.cod)+'</b><br><small>'+sx(x.eq)+' '+sx(x.id)+'</small></td><td>'+sx(x.tec||'-')+'</td><td>'+sx(x.mot)+'</td><td>'+sx(x.st)+'</td></tr>'}).join('')||'<tr><td colspan="5">Nenhum registro.</td></tr>'}
function draw(){var p=el('p-descarte');if(!p)return;css();p.innerHTML='<div class="card"><h2>Baixa autorizada</h2><p class="small">Fluxo sem oscilação: localizar, solicitar, aprovar e gerar relatório.</p><div class="baixa42Steps"><div><b>1. Localizar</b><br><small>MAC/SN/código</small></div><div><b>2. Triagem</b><br><small>motivo</small></div><div><b>3. Solicitar</b><br><small>registro</small></div><div><b>4. Aprovar</b><br><small>baixa final</small></div></div><div class="baixa42Grid"><div><input id="discSearch" data-p40="1" data-ok="1" placeholder="Bipe ou digite MAC, SN, código ou patrimônio"><div id="baixa42Prev" class="baixa42Prev">Nenhum equipamento selecionado.</div><select id="baixa42Motivo"><option>Queimado</option><option>Quebrado</option><option>Oxidação</option><option>Dano físico</option><option>Sem reparo</option><option>Extraviado</option><option>Outro</option></select><input id="baixa42Solic" placeholder="Solicitado por"><input id="baixa42Aprov" placeholder="Aprovado por"><textarea id="baixa42Obs" placeholder="Observação"></textarea><div class="baixa42Warn"><b>Regra:</b> solicitação não é baixa final. Baixa final só com aprovação.</div><button id="baixa42Solicitar" class="warn">Registrar solicitação</button><button id="baixa42Aprovar" class="bad">Aprovar baixa final</button><button id="baixa42Rel" class="ok">Gerar relatório na tela</button><button id="baixa42Pdf" class="pri">Abrir PDF / impressão</button><div id="baixa42Msg" class="msg"></div></div><div><h3>Registros de baixa</h3><div class="tbl"><table><thead><tr><th>Data</th><th>Equipamento</th><th>Responsável</th><th>Motivo</th><th>Status</th></tr></thead><tbody id="baixa42Table"></tbody></table></div></div></div><div id="baixa42Report"></div></div>'}
function preview(){chosen=findEq(el('discSearch')&&el('discSearch').value);var p=el('baixa42Prev');if(!p)return;if(!chosen){p.innerHTML='<b>Equipamento não encontrado.</b><br><small>Confira o código, MAC ou SN.</small>';p.style.background='#fee2e2';return}p.style.background='#f8fafc';p.innerHTML='<b>'+sx(chosen.codigo)+' - '+sx(mod(chosen))+'</b><br><small>MAC/SN: '+sx(chosen.mac||chosen.serial||'-')+'</small><br><small>Status: '+sx(chosen.status)+' | Local: '+sx(chosen.local||'-')+'</small><br><small>Responsável provável: <b>'+sx(resp(chosen)||'-')+'</b></small>'}
async function save(finalizar){try{if(!chosen)preview();if(!chosen){el('baixa42Msg').textContent='Selecione um equipamento válido.';el('baixa42Msg').className='msg bad';return}var aprov=(el('baixa42Aprov').value||'').trim();if(finalizar&&!aprov){el('baixa42Msg').textContent='Informe quem aprovou a baixa final.';el('baixa42Msg').className='msg bad';return}var tec=resp(chosen)||chosen.tecnicoAtual||'';var rec={equipamento_id:chosen.id,codigo:chosen.codigo,mac:chosen.mac,serial:chosen.serial,modelo:mod(chosen),tecnico:tec,solicitado_por:el('baixa42Solic').value||'',aprovado_por:aprov,motivo:el('baixa42Motivo').value,status:finalizar?'Descartado':'Solicitado',observacao:el('baixa42Obs').value||'',aprovado_em:finalizar?new Date().toISOString():null,descartado_em:finalizar?new Date().toISOString():null};var r=await db().from('descartes_autorizados').insert(rec);if(r.error)throw r.error;if(finalizar){chosen.status='Descarte autorizado';chosen.local='Descarte autorizado';chosen.motivoAtual=rec.motivo;Object.assign(chosen,fromEq(await upd('equipamentos',chosen.id,toEq(chosen))));await mov(chosen,'Baixa autorizada',{tec:tec,dest:'Descarte autorizado',mot:rec.motivo,obs:'Aprovado por '+aprov+' | '+rec.observacao})}await loadDesc();stableTable();el('baixa42Msg').textContent=finalizar?'Baixa final aprovada.':'Solicitação registrada.';el('baixa42Msg').className='msg ok'}catch(e){el('baixa42Msg').textContent='Erro: '+e.message;el('baixa42Msg').className='msg bad'}}
function openPrint(html,title){if(!html||!html.trim()){alert('Gere o relatório primeiro.');return}var w=window.open('','_blank');if(!w){alert('Permita pop-ups para imprimir/PDF.');return}var css='body{font-family:Segoe UI,Arial;padding:20px;color:#111}h2{color:#0d1b2e}.p39kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.p39kpi div{border:1px solid #ddd;border-radius:8px;padding:8px;background:#f8fafc}.tbl{overflow:visible}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#0f4c81;color:white}td,th{border:1px solid #ddd;padding:6px;vertical-align:top}@page{size:A4 landscape;margin:10mm}';w.document.open();w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>'+title+'</title><style>'+css+'</style></head><body>'+html+'<script>setTimeout(function(){window.print()},400)<\/script></body></html>');w.document.close()}
function bind(){if(!el('p-descarte'))return;if(!el('baixa42Table'))draw();var ds=el('discSearch');if(ds){ds.dataset.p40=1;ds.dataset.ok=1;ds.oninput=preview;ds.onkeydown=function(e){if(e.key==='Enter')preview()}}if(el('baixa42Solicitar'))el('baixa42Solicitar').onclick=function(){save(false)};if(el('baixa42Aprovar'))el('baixa42Aprovar').onclick=function(){save(true)};if(el('baixa42Rel'))el('baixa42Rel').onclick=async function(){await loadDesc();el('baixa42Report').innerHTML=reportHtml();el('baixa42Report').scrollIntoView({behavior:'smooth'})};if(el('baixa42Pdf'))el('baixa42Pdf').onclick=async function(){await loadDesc();openPrint(reportHtml(),'Relatório de descartados')}}
function hookGlobalPdf(){var pg=el('printGerReport');if(pg&&!pg.dataset.p42){pg.dataset.p42=1;pg.onclick=function(){var html=(el('gerReportArea')&&el('gerReportArea').innerHTML)||'';openPrint(html,'Relatório gerencial')}}}
async function boot(){bind();await loadDesc();stableTable();hookGlobalPdf()}
setInterval(function(){bind();stableTable();hookGlobalPdf()},1500);document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,1200)});
})();