(function(){
function el(i){return document.getElementById(i)}
function sx(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function num(v){return Number(v||0)}
async function loadProdutos(){try{D.produtoTipos=await loadTable('produto_tipos','nome',true)}catch(e){D.produtoTipos=[]}try{D.produtoMarcas=await loadTable('produto_marcas','nome',true)}catch(e){D.produtoMarcas=[]}}
function css(){if(el('p45css'))return;var s=document.createElement('style');s.id='p45css';s.textContent='.prodHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.prodHero h2{margin:0 0 5px}.prodGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.prodCard{background:white;border:1px solid #e5e7eb;border-radius:18px;padding:16px;box-shadow:0 10px 28px #0f172a12}.prodCardBig{grid-column:1/-1}.prodMini{display:flex;justify-content:space-between;gap:8px;align-items:center;background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:9px;margin:6px 0}.prodTag{display:inline-block;border-radius:999px;padding:3px 8px;background:#eef2ff;color:#3730a3;font-weight:800;font-size:12px}.prodTag.ok{background:#dcfce7;color:#166534}.prodTag.bad{background:#fee2e2;color:#991b1b}.prodTag.warn{background:#fef3c7;color:#92400e}@media(max-width:950px){.prodGrid{grid-template-columns:1fr}.prodCardBig{grid-column:auto}}';document.head.appendChild(s)}
function tipoOpts(sel){return '<option value="">Tipo</option>'+(D.produtoTipos||[]).filter(t=>t.ativo!==false).map(t=>'<option value="'+sx(t.nome)+'" '+(sel===t.nome?'selected':'')+'>'+sx(t.nome)+'</option>').join('')}
function marcaOpts(sel){return '<option value="">Marca</option>'+(D.produtoMarcas||[]).filter(m=>m.ativo!==false).map(m=>'<option value="'+sx(m.nome)+'" '+(sel===m.nome?'selected':'')+'>'+sx(m.nome)+'</option>').join('')}
function unidadeOpts(sel){var a=['Unidade','Metro','Bobina','Caixa','Pacote','Peça','Par','Rolo','Kit'];return a.map(x=>'<option '+(sel===x?'selected':'')+'>'+x+'</option>').join('')}
function draw(){var p=el('p-cadastros');if(!p)return;css();p.innerHTML='<div class="prodHero"><h2>Produtos</h2><p>Cadastro único de Tipos, Marcas e Modelos. Tipo e marca ficam travados para evitar duplicidade na entrada.</p></div><div class="prodGrid"><div class="prodCard"><h2>Tipos</h2><p class="small">Define se o produto é unitário ou por quantidade.</p><input id="prodTipoNome" placeholder="Ex: ONU, Roteador, RJ45"><div class="grid"><select id="prodTipoControle"><option>Unitário</option><option>Quantidade</option></select><select id="prodTipoMac"><option value="true">Exige MAC/SN</option><option value="false">Não exige MAC/SN</option></select></div><button id="prodAddTipo" class="pri">Adicionar tipo</button><div id="prodTipoMsg" class="msg"></div><div id="prodTipoList"></div></div><div class="prodCard"><h2>Marcas</h2><p class="small">Use Genérico ou Sem marca para materiais simples.</p><input id="prodMarcaNome" placeholder="Ex: ZTE, Intelbras, Genérico"><button id="prodAddMarca" class="pri">Adicionar marca</button><div id="prodMarcaMsg" class="msg"></div><div id="prodMarcaList"></div></div><div class="prodCard prodCardBig"><h2>Modelos / Produtos</h2><p class="small">Aqui o modelo fica preso ao Tipo e Marca cadastrados.</p><div class="grid4"><select id="prodModeloTipo"></select><select id="prodModeloMarca"></select><input id="prodModeloNome" placeholder="Modelo/Produto. Ex: F601, RJ45 Cat5e"><select id="prodModeloControle"><option>Unitário</option><option>Quantidade</option></select><select id="prodModeloUnidade"></select><select id="prodModeloMac"><option value="true">Exige MAC/SN</option><option value="false">Não exige MAC/SN</option></select><input id="prodModeloCusto" type="number" placeholder="Custo padrão"><input id="prodModeloMin" type="number" placeholder="Estoque mínimo"><input id="prodModeloIdeal" type="number" placeholder="Estoque ideal"></div><button id="prodAddModelo" class="pri">Adicionar modelo/produto</button><div id="prodModeloMsg" class="msg"></div><div class="tbl"><table><thead><tr><th>Tipo</th><th>Marca</th><th>Modelo</th><th>Controle</th><th>Unidade</th><th>MAC/SN</th><th>Mínimo</th><th>Ideal</th><th>Ações</th></tr></thead><tbody id="prodModeloTable"></tbody></table></div></div></div>'}
function renderLists(){
 if(el('prodModeloTipo'))el('prodModeloTipo').innerHTML=tipoOpts(el('prodModeloTipo').value);
 if(el('prodModeloMarca'))el('prodModeloMarca').innerHTML=marcaOpts(el('prodModeloMarca').value);
 if(el('prodModeloUnidade'))el('prodModeloUnidade').innerHTML=unidadeOpts(el('prodModeloUnidade').value||'Unidade');
 var tl=el('prodTipoList');if(tl)tl.innerHTML=(D.produtoTipos||[]).map(t=>'<div class="prodMini"><div><b>'+sx(t.nome)+'</b><br><span class="prodTag '+(t.controle==='Quantidade'?'warn':'ok')+'">'+sx(t.controle)+'</span> <span class="prodTag '+(t.exige_mac_sn?'bad':'ok')+'">'+(t.exige_mac_sn?'Exige MAC/SN':'Sem MAC/SN')+'</span></div><button onclick="window.prodToggleTipo(\''+t.id+'\','+(t.ativo===false?'true':'false')+')">'+(t.ativo===false?'Ativar':'Desativar')+'</button></div>').join('')||'<div class="msg">Nenhum tipo cadastrado.</div>';
 var ml=el('prodMarcaList');if(ml)ml.innerHTML=(D.produtoMarcas||[]).map(m=>'<div class="prodMini"><b>'+sx(m.nome)+'</b><button onclick="window.prodToggleMarca(\''+m.id+'\','+(m.ativo===false?'true':'false')+')">'+(m.ativo===false?'Ativar':'Desativar')+'</button></div>').join('')||'<div class="msg">Nenhuma marca cadastrada.</div>';
 var mt=el('prodModeloTable');if(mt)mt.innerHTML=(D.modelos||[]).map(m=>'<tr><td>'+sx(m.tipo)+'</td><td>'+sx(m.marca)+'</td><td><b>'+sx(m.modelo)+'</b></td><td>'+sx(m.controle||'Unitário')+'</td><td>'+sx(m.unidade||'Unidade')+'</td><td>'+(m.exige_mac_sn===false?'Não':'Sim')+'</td><td>'+sx(m.minimo??m.estoque_minimo??'')+'</td><td>'+sx(m.ideal??m.estoque_ideal??'')+'</td><td><button onclick="window.prodEditModelo(\''+m.id+'\')">Editar</button><button class="bad" onclick="window.prodDisableModelo(\''+m.id+'\')">Desativar</button></td></tr>').join('')||'<tr><td colspan="9">Nenhum modelo/produto cadastrado.</td></tr>';
}
async function addTipo(){try{var nome=(el('prodTipoNome').value||'').trim();if(!nome)throw new Error('Informe o nome do tipo.');var r=await db().from('produto_tipos').insert({nome:nome,controle:el('prodTipoControle').value,exige_mac_sn:el('prodTipoMac').value==='true',ativo:true});if(r.error)throw r.error;el('prodTipoNome').value='';await loadProdutos();renderLists();el('prodTipoMsg').textContent='Tipo cadastrado.';el('prodTipoMsg').className='msg ok'}catch(e){el('prodTipoMsg').textContent='Erro: '+e.message;el('prodTipoMsg').className='msg bad'}}
async function addMarca(){try{var nome=(el('prodMarcaNome').value||'').trim();if(!nome)throw new Error('Informe o nome da marca.');var r=await db().from('produto_marcas').insert({nome:nome,ativo:true});if(r.error)throw r.error;el('prodMarcaNome').value='';await loadProdutos();renderLists();el('prodMarcaMsg').textContent='Marca cadastrada.';el('prodMarcaMsg').className='msg ok'}catch(e){el('prodMarcaMsg').textContent='Erro: '+e.message;el('prodMarcaMsg').className='msg bad'}}
async function addModelo(){try{var tipo=el('prodModeloTipo').value,marca=el('prodModeloMarca').value,modelo=(el('prodModeloNome').value||'').trim();if(!tipo||!marca||!modelo)throw new Error('Escolha tipo, marca e informe o modelo.');var row={tipo:tipo,marca:marca,modelo:modelo,controle:el('prodModeloControle').value,unidade:el('prodModeloUnidade').value,exige_mac_sn:el('prodModeloMac').value==='true',custo:num(el('prodModeloCusto').value),minimo:num(el('prodModeloMin').value),ideal:num(el('prodModeloIdeal').value),ativo:true};var r=await db().from('modelos').insert(row);if(r.error)throw r.error;['prodModeloNome','prodModeloCusto','prodModeloMin','prodModeloIdeal'].forEach(i=>el(i).value='');await loadAll();await loadProdutos();renderLists();el('prodModeloMsg').textContent='Modelo/produto cadastrado.';el('prodModeloMsg').className='msg ok'}catch(e){el('prodModeloMsg').textContent='Erro: '+e.message;el('prodModeloMsg').className='msg bad'}}
window.prodToggleTipo=async function(id,ativo){await db().from('produto_tipos').update({ativo:ativo}).eq('id',id);await loadProdutos();renderLists()}
window.prodToggleMarca=async function(id,ativo){await db().from('produto_marcas').update({ativo:ativo}).eq('id',id);await loadProdutos();renderLists()}
window.prodDisableModelo=async function(id){await db().from('modelos').update({ativo:false}).eq('id',id);await loadAll();renderLists()}
window.prodEditModelo=function(id){var m=(D.modelos||[]).find(x=>x.id===id);if(!m)return;el('prodModeloTipo').value=m.tipo;el('prodModeloMarca').value=m.marca;el('prodModeloNome').value=m.modelo;el('prodModeloControle').value=m.controle||'Unitário';el('prodModeloUnidade').value=m.unidade||'Unidade';el('prodModeloMac').value=(m.exige_mac_sn===false?'false':'true');el('prodModeloCusto').value=m.custo||'';el('prodModeloMin').value=m.minimo||'';el('prodModeloIdeal').value=m.ideal||'';el('prodModeloMsg').textContent='Edite os campos e clique em Adicionar modelo/produto para criar novo padrão. O registro antigo pode ser desativado.';el('prodModeloMsg').className='msg warn'}
function syncTipoDefaults(){var tipo=(D.produtoTipos||[]).find(t=>t.nome===el('prodModeloTipo')?.value);if(tipo){el('prodModeloControle').value=tipo.controle||'Unitário';el('prodModeloMac').value=tipo.exige_mac_sn?'true':'false';if(tipo.controle==='Quantidade')el('prodModeloUnidade').value='Unidade'}}
function bind(){if(!el('p-cadastros'))return;if(!el('prodAddTipo'))draw();renderLists();if(el('prodAddTipo'))el('prodAddTipo').onclick=addTipo;if(el('prodAddMarca'))el('prodAddMarca').onclick=addMarca;if(el('prodAddModelo'))el('prodAddModelo').onclick=addModelo;if(el('prodModeloTipo'))el('prodModeloTipo').onchange=syncTipoDefaults}
async function boot(){await loadProdutos();draw();bind();renderLists()}
var oldLoad=loadAll;loadAll=async function(){await oldLoad();await loadProdutos()}
var oldRender=render;render=function(){oldRender();if(el('p-cadastros')){draw();bind();renderLists()}}
document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,1800)});setInterval(function(){if(el('p-cadastros')&&el('p-cadastros').classList.contains('on'))bind()},1500);
})();