(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function M(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
let tecnicos=[],equipamentos=[],materiais=[],sel='';
async function qtab(t,order){try{let q=db().from(t).select('*'); if(order)q=q.order(order,{ascending:true}); let r=await q; if(r.error)throw r.error; return r.data||[]}catch(e){return []}}
async function loadData(){
 tecnicos=await qtab('tecnicos','nome');
 equipamentos=await qtab('equipamentos','codigo');
 materiais=await qtab('materiais_saldos','tipo');
 if(window.D){D.tecnicos=tecnicos;D.equipamentos=equipamentos.map(x=>{try{return fromEq(x)}catch(e){return x}})}
 equipamentos=(window.D&&D.equipamentos)||equipamentos;
}
function tnEq(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function en(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function names(){return [...new Set([...(tecnicos||[]).map(t=>t.nome),...(equipamentos||[]).map(tnEq),...(materiais||[]).map(x=>x.tecnico)].filter(Boolean))].sort()}
function eqs(n){return (equipamentos||[]).filter(e=>tnEq(e)===n && !['Em estoque','Inutilizado','Perdido','Descarte autorizado','Instalado no cliente','Instalado cliente'].includes(e.status||''))}
function mats(n){return (materiais||[]).filter(m=>(m.tecnico||'')===n && Number(m.quantidade||0)!==0)}
function css(){if(E('p65css'))return;let s=document.createElement('style');s.id='p65css';s.textContent='.tec65Hero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.tec65Grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:14px}.tec65Item{display:flex;justify-content:space-between;gap:8px;align-items:center;background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:10px;margin:8px 0;cursor:pointer}.tec65Item.on{outline:3px solid #0f4c8130;border-color:#0f4c81}.tec65Kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.tec65Kpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}@media(max-width:950px){.tec65Grid,.tec65Kpi{grid-template-columns:1fr}}';document.head.appendChild(s)}
function page(){let main=document.querySelector('.main');if(!main)return;let old=E('p-tecnicosFull');if(old)old.remove();let old2=E('p-tecnicos65');if(old2)old2.remove();main.insertAdjacentHTML('beforeend','<section id="p-tecnicos65" class="page"><div class="tec65Hero"><h2>Técnicos</h2><p>Lista real dos técnicos, equipamentos patrimoniais e materiais em posse.</p></div><div class="tec65Grid"><div class="card"><h2>Adicionar técnico</h2><input id="tec65Nome" placeholder="Nome do técnico"><button id="tec65Add" class="pri">Adicionar técnico</button><div id="tec65Msg" class="msg"></div><h2>Técnicos cadastrados</h2><input id="tec65Busca" placeholder="Buscar técnico"><button id="tec65Reload" class="ok">Atualizar lista</button><div id="tec65Lista"></div></div><div class="card"><h2 id="tec65Titulo">Selecione um técnico</h2><div id="tec65Kpis" class="tec65Kpi"></div><p><button id="tec65Ver" class="pri">Ver equipamentos e materiais</button><button id="tec65Copiar" class="warn">Copiar cobrança</button><button id="tec65Print" class="bad">Imprimir/PDF</button></p><div id="tec65Area"></div></div></div></section>')}
function nav(){let side=document.querySelector('.side');if(side){let old=document.querySelector('[data-p="tecnicosFull"]');if(old)old.remove();if(!document.querySelector('[data-p="tecnicos65"]')){let r=document.querySelector('[data-p="materiais"]')||document.querySelector('[data-p="tecnico"]')||document.querySelector('[data-p="operacaoEstoque"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="tecnicos65">Técnicos</button>')}}document.querySelectorAll('.nav').forEach(b=>{if(b.dataset.p==='tecnicos65')b.onclick=e=>{e.preventDefault();open65()}})}
function renderList(){let box=E('tec65Lista');if(!box)return;let f=(E('tec65Busca')&&E('tec65Busca').value||'').toLowerCase();let arr=names().filter(n=>!f||n.toLowerCase().includes(f));box.innerHTML=arr.map(n=>{let rec=tecnicos.find(t=>t.nome===n);return '<div class="tec65Item '+(sel===n?'on':'')+'"><div data-sel="'+S(n)+'" style="flex:1"><b>'+S(n)+'</b><br><small>'+eqs(n).length+' equipamento(s) • '+mats(n).length+' material(is)</small></div><button class="bad" data-id="'+S(rec?rec.id:'')+'" data-del="'+S(n)+'">Excluir</button></div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>';box.querySelectorAll('[data-sel]').forEach(x=>x.onclick=function(){sel=this.dataset.sel;renderAll(true)});box.querySelectorAll('[data-del]').forEach(x=>x.onclick=function(ev){ev.stopPropagation();delTec(this.dataset.id,this.dataset.del)})}
function renderK(){if(!E('tec65Kpis'))return;if(!sel){E('tec65Titulo').textContent='Selecione um técnico';E('tec65Kpis').innerHTML='';E('tec65Area').innerHTML='';return}let e=eqs(sel),m=mats(sel),val=e.reduce((a,b)=>a+Number(b.custo||0),0);E('tec65Titulo').textContent='Técnico: '+sel;E('tec65Kpis').innerHTML='<div><small>Equipamentos</small><b>'+e.length+'</b></div><div><small>Materiais</small><b>'+m.length+'</b></div><div><small>Valor patrimônio</small><b>'+M(val)+'</b></div><div><small>Técnicos</small><b>'+names().length+'</b></div>'}
function tables(){let e=eqs(sel),m=mats(sel);return '<h3>Equipamentos patrimoniais</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Valor</th></tr></thead><tbody>'+(e.map(x=>'<tr><td>'+S(x.codigo)+'</td><td>'+S(en(x))+'</td><td>'+S(x.mac||x.serial||'-')+'</td><td>'+S(x.status||'-')+'</td><td>'+S(x.local||'-')+'</td><td>'+M(x.custo||0)+'</td></tr>').join('')||'<tr><td colspan="6">Sem equipamento patrimonial em posse.</td></tr>')+'</tbody></table></div><h3>Materiais em posse</h3><div class="tbl"><table><thead><tr><th>Categoria</th><th>Material</th><th>Quantidade</th><th>Unidade</th><th>Local</th></tr></thead><tbody>'+(m.map(x=>'<tr><td>'+S(x.categoria)+'</td><td>'+S(x.tipo+' '+(x.marca||'')+' '+x.modelo)+'</td><td><b>'+S(x.quantidade)+'</b></td><td>'+S(x.unidade_saida)+'</td><td>'+S(x.local||'Técnico')+'</td></tr>').join('')||'<tr><td colspan="5">Sem material em posse.</td></tr>')+'</tbody></table></div>'}
function renderAll(show){renderList();renderK();if(show&&sel&&E('tec65Area'))E('tec65Area').innerHTML=tables()}
function msg(t,c){let m=E('tec65Msg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
async function addTec(){try{let nome=(E('tec65Nome').value||'').trim();if(!nome)return msg('Informe o nome do técnico.','bad');let r=await db().from('tecnicos').insert({nome:nome,ativo:true}).select().single();if(r.error)throw r.error;E('tec65Nome').value='';sel=nome;await loadData();renderAll(true);msg('Técnico adicionado.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
async function delTec(id,nome){try{if(eqs(nome).length||mats(nome).length){alert('Não exclua técnico com equipamento/material em posse. Devolva ou transfira antes.');return}if(!id){alert('Este técnico aparece por movimentação antiga, mas não tem cadastro direto para excluir.');return}if(!confirm('Excluir técnico '+nome+'?'))return;let r=await db().from('tecnicos').delete().eq('id',id);if(r.error)throw r.error;if(sel===nome)sel='';await loadData();renderAll(false);msg('Técnico excluído.','ok')}catch(e){msg('Erro ao excluir: '+e.message,'bad')}}
function copiar(){if(!sel)return msg('Selecione um técnico.','bad');let txt='RELATÓRIO DO TÉCNICO\nTécnico: '+sel+'\nEquipamentos: '+eqs(sel).length+'\nMateriais: '+mats(sel).length+'\n\nEQUIPAMENTOS:\n'+(eqs(sel).map(x=>'- '+(x.codigo||'')+' | '+en(x)+' | '+(x.mac||x.serial||'-')+' | '+(x.status||'')).join('\n')||'Sem equipamentos.')+'\n\nMATERIAIS:\n'+(mats(sel).map(x=>'- '+x.tipo+' '+(x.marca||'')+' '+x.modelo+' | '+x.quantidade+' '+x.unidade_saida).join('\n')||'Sem materiais.');navigator.clipboard.writeText(txt).then(()=>msg('Copiado.','ok'))}
function bind(){css();page();nav();if(E('tec65Busca'))E('tec65Busca').oninput=renderList;if(E('tec65Add'))E('tec65Add').onclick=addTec;if(E('tec65Reload'))E('tec65Reload').onclick=async()=>{await loadData();renderAll(true);msg('Lista atualizada.','ok')};if(E('tec65Ver'))E('tec65Ver').onclick=()=>{if(!sel)return msg('Selecione um técnico.','bad');E('tec65Area').innerHTML=tables()};if(E('tec65Copiar'))E('tec65Copiar').onclick=copiar;if(E('tec65Print'))E('tec65Print').onclick=()=>window.print()}
async function open65(){bind();await loadData();renderAll(true);document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('on'));E('p-tecnicos65').classList.add('on');let b=document.querySelector('[data-p="tecnicos65"]');if(b)b.classList.add('on');if(E('title'))E('title').textContent='Técnicos'}
window.openTecnicos65=open65;window.tecForceReload=open65;
setInterval(()=>{nav();if(E('p-tecnicos65')&&E('p-tecnicos65').classList.contains('on')){loadData().then(()=>renderAll(false))}},7000);
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{bind();loadData().then(()=>renderAll(false))},2500));
})();