(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function money(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
var matSaldos=[];
async function loadTecData(){
 try{D.tecnicos=await loadTable('tecnicos','nome',true)}catch(e){D.tecnicos=D.tecnicos||[]}
 try{matSaldos=await loadTable('materiais_saldos','updated_at',false)}catch(e){matSaldos=[]}
}
function techNameEq(x){return x.tecnicoAtual||x.tecnico_atual||x.tecnico||''}
function eqName(x){return ((x.tipo||'')+' '+(x.marca||'')+' '+(x.modelo||'')).trim()}
function techNames(){
 return [...new Set([...(D.tecnicos||[]).map(t=>t.nome),...(D.equipamentos||[]).map(x=>techNameEq(x)),...matSaldos.map(x=>x.tecnico)].filter(Boolean))].sort();
}
function eqs(nome){return (D.equipamentos||[]).filter(e=>techNameEq(e)===nome && !['Em estoque','Inutilizado','Perdido','Descarte autorizado','Instalado no cliente'].includes(e.status))}
function mats(nome){return matSaldos.filter(m=>(m.tecnico||'')===nome && Number(m.quantidade||0)!==0)}
function css(){if(E('p64css'))return;var s=document.createElement('style');s.id='p64css';s.textContent='.t64Hero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.t64Grid{display:grid;grid-template-columns:.85fr 1.15fr;gap:14px}.t64Item{display:flex;justify-content:space-between;align-items:center;gap:8px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:10px;margin:8px 0;cursor:pointer}.t64Item.on{outline:3px solid #0f4c8124;border-color:#0f4c81}.t64Kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.t64Kpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}@media(max-width:950px){.t64Grid,.t64Kpi{grid-template-columns:1fr}}';document.head.appendChild(s)}
function page(){var main=document.querySelector('.main');if(!main)return;var old=E('p-tecnicosFull');if(old)old.remove();main.insertAdjacentHTML('beforeend','<section id="p-tecnicosFull" class="page"><div class="t64Hero"><h2>Técnicos</h2><p>Equipamentos patrimoniais e materiais em posse do técnico.</p></div><div class="t64Grid"><div class="card"><h2>Adicionar técnico</h2><input id="t64Nome" placeholder="Nome do técnico"><button id="t64Add" class="pri">Adicionar técnico</button><div id="t64Msg" class="msg"></div><h2>Técnicos cadastrados</h2><input id="t64Busca" placeholder="Buscar técnico"><button id="t64Reload" class="ok">Atualizar lista</button><div id="t64List"></div></div><div class="card"><h2 id="t64Title">Selecione um técnico</h2><div id="t64Kpis" class="t64Kpi"></div><p><button id="t64View" class="pri">Ver equipamentos e materiais</button><button id="t64Copy" class="warn">Copiar cobrança</button><button id="t64Print" class="bad">Imprimir/PDF</button></p><div id="t64Area"></div></div></div></section>')}
function nav(){var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="tecnicosFull"]')){var r=document.querySelector('[data-p="operacaoEstoque"]')||document.querySelector('[data-p="tecnico"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="tecnicosFull">Técnicos</button>')}document.querySelectorAll('.nav').forEach(function(b){if(b.dataset.p==='tecnicosFull')b.onclick=function(ev){ev.preventDefault();openTec64()}})}
var selected='';
function renderList(){var box=E('t64List');if(!box)return;var q=(E('t64Busca')&&E('t64Busca').value||'').toLowerCase();var names=techNames().filter(n=>!q||n.toLowerCase().includes(q));box.innerHTML=names.map(function(n){var rec=(D.tecnicos||[]).find(t=>t.nome===n);return '<div class="t64Item '+(selected===n?'on':'')+'"><div data-sel="'+S(n)+'" style="flex:1"><b>'+S(n)+'</b><br><small>'+eqs(n).length+' equipamento(s) • '+mats(n).length+' material(is)</small></div><button class="bad" data-del="'+S(n)+'" data-id="'+S(rec?rec.id:'')+'">Excluir</button></div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>';box.querySelectorAll('[data-sel]').forEach(x=>x.onclick=function(){selected=this.dataset.sel;renderAll()});box.querySelectorAll('[data-del]').forEach(x=>x.onclick=function(ev){ev.stopPropagation();delTec64(this.dataset.id,this.dataset.del)})}
function kpis(){if(!E('t64Kpis'))return;if(!selected){E('t64Title').textContent='Selecione um técnico';E('t64Kpis').innerHTML='';E('t64Area').innerHTML='';return}var e=eqs(selected),m=mats(selected),val=e.reduce((a,b)=>a+Number(b.custo||0),0);E('t64Title').textContent='Técnico: '+selected;E('t64Kpis').innerHTML='<div><small>Equipamentos</small><b>'+e.length+'</b></div><div><small>Materiais</small><b>'+m.length+'</b></div><div><small>Valor patrimônio</small><b>'+money(val)+'</b></div><div><small>Total técnicos</small><b>'+techNames().length+'</b></div>'}
function tables(){var e=eqs(selected),m=mats(selected);return '<h3>Equipamentos patrimoniais</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Valor</th></tr></thead><tbody>'+(e.map(x=>'<tr><td>'+S(x.codigo)+'</td><td>'+S(eqName(x))+'</td><td>'+S(x.mac||x.serial||'-')+'</td><td>'+S(x.status||'-')+'</td><td>'+S(x.local||'-')+'</td><td>'+money(x.custo||0)+'</td></tr>').join('')||'<tr><td colspan="6">Sem equipamento patrimonial em posse.</td></tr>')+'</tbody></table></div><h3>Materiais em posse</h3><div class="tbl"><table><thead><tr><th>Categoria</th><th>Material</th><th>Unidade</th><th>Quantidade</th><th>Local</th></tr></thead><tbody>'+(m.map(x=>'<tr><td>'+S(x.categoria)+'</td><td>'+S(x.tipo+' '+(x.marca||'')+' '+x.modelo)+'</td><td>'+S(x.unidade_saida)+'</td><td><b>'+S(x.quantidade)+'</b></td><td>'+S(x.local||'Técnico')+'</td></tr>').join('')||'<tr><td colspan="5">Sem material em posse.</td></tr>')+'</tbody></table></div>'}
function renderAll(){renderList();kpis();if(selected&&E('t64Area'))E('t64Area').innerHTML=tables()}
async function addTec64(){try{var nome=(E('t64Nome').value||'').trim();if(!nome)return msg('Informe o nome do técnico.','bad');if((D.tecnicos||[]).some(t=>(t.nome||'').toLowerCase()===nome.toLowerCase()))return msg('Técnico já existe.','bad');var r=await db().from('tecnicos').insert({nome:nome,ativo:true}).select().single();if(r.error)throw r.error;D.tecnicos.push(r.data);E('t64Nome').value='';selected=nome;renderAll();msg('Técnico adicionado.','ok')}catch(e){msg('Erro: '+e.message,'bad')}}
async function delTec64(id,nome){try{if(eqs(nome).length||mats(nome).length){alert('Não remova técnico com equipamento/material em posse. Transfira ou devolva antes.');return}if(!id){alert('Este nome vem de movimentação antiga. Não há cadastro direto para excluir.');return}if(!confirm('Excluir técnico '+nome+'?'))return;var r=await db().from('tecnicos').delete().eq('id',id);if(r.error)throw r.error;D.tecnicos=D.tecnicos.filter(t=>t.id!==id);if(selected===nome)selected='';renderAll();msg('Técnico excluído.','ok')}catch(e){msg('Erro ao excluir: '+e.message,'bad')}}
function copy(){if(!selected)return msg('Selecione um técnico.','bad');var txt='RELATÓRIO DO TÉCNICO\nTécnico: '+selected+'\nEquipamentos: '+eqs(selected).length+'\nMateriais: '+mats(selected).length+'\n\nEQUIPAMENTOS:\n'+(eqs(selected).map(x=>'- '+(x.codigo||'')+' | '+eqName(x)+' | '+(x.mac||x.serial||'-')+' | '+(x.status||'')).join('\n')||'Sem equipamentos.')+'\n\nMATERIAIS:\n'+(mats(selected).map(x=>'- '+x.tipo+' '+(x.marca||'')+' '+x.modelo+' | '+x.quantidade+' '+x.unidade_saida).join('\n')||'Sem materiais.');navigator.clipboard.writeText(txt).then(()=>msg('Relatório copiado.','ok'))}
function msg(t,c){var m=E('t64Msg');if(m){m.textContent=t;m.className='msg '+(c||'')}}
function bind(){css();page();nav();if(E('t64Busca'))E('t64Busca').oninput=renderList;if(E('t64Add'))E('t64Add').onclick=addTec64;if(E('t64Reload'))E('t64Reload').onclick=async function(){await loadTecData();renderAll();msg('Lista atualizada.','ok')};if(E('t64View'))E('t64View').onclick=function(){if(selected)E('t64Area').innerHTML=tables();else msg('Selecione um técnico.','bad')};if(E('t64Copy'))E('t64Copy').onclick=copy;if(E('t64Print'))E('t64Print').onclick=function(){window.print()}}
async function openTec64(){bind();await loadTecData();renderAll();document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('on'));E('p-tecnicosFull').classList.add('on');var b=document.querySelector('[data-p="tecnicosFull"]');if(b)b.classList.add('on');if(E('title'))E('title').textContent='Técnicos'}
function renderTechStock64(){var box=E('techStockBox');if(!box)return;var names=techNames();box.innerHTML=names.map(function(n){var e=eqs(n),m=mats(n),val=e.reduce((a,b)=>a+Number(b.custo||0),0);return '<div class="card"><h2>'+S(n)+' <span class="status">'+e.length+' eqp</span> <span class="status ok">'+m.length+' mat</span> <span class="status">'+money(val)+'</span></h2>'+tablesFor(n,e,m)+'</div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>'}
function tablesFor(n,e,m){return '<h3>Equipamentos</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Modelo</th><th>MAC/SN</th><th>Status</th></tr></thead><tbody>'+(e.map(x=>'<tr><td>'+S(x.codigo)+'</td><td>'+S(eqName(x))+'</td><td>'+S(x.mac||x.serial||'-')+'</td><td>'+S(x.status)+'</td></tr>').join('')||'<tr><td colspan="4">Sem equipamento.</td></tr>')+'</tbody></table></div><h3>Materiais</h3><div class="tbl"><table><thead><tr><th>Material</th><th>Categoria</th><th>Qtd</th><th>Unidade</th></tr></thead><tbody>'+(m.map(x=>'<tr><td>'+S(x.tipo+' '+(x.marca||'')+' '+x.modelo)+'</td><td>'+S(x.categoria)+'</td><td>'+S(x.quantidade)+'</td><td>'+S(x.unidade_saida)+'</td></tr>').join('')||'<tr><td colspan="4">Sem material.</td></tr>')+'</tbody></table></div>'}
window.renderTechStock=renderTechStock64;window.tecForceReload=openTec64;
setInterval(async function(){nav();if(sb){await loadTecData();if(E('p-tecnico')&&E('p-tecnico').classList.contains('on'))renderTechStock64();if(E('p-tecnicosFull')&&E('p-tecnicosFull').classList.contains('on'))renderAll()}},5000);
document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){bind();if(sb)loadTecData().then(renderTechStock64)},2500)})
})();