(function(){
function id(x){return document.getElementById(x)}
function safe(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function key(v){try{return N(v||'')}catch(e){return String(v||'').toLowerCase().trim()}}
function eqName(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function findEq(t){var k=key(t);return (D.equipamentos||[]).find(e=>key(e.codigo)===k||key(e.patrimonio)===k||key(e.mac)===k||key(e.serial)===k)}
function lastResp(e){var m=(D.movimentos||[]).find(x=>x.equipamento_id===e.id||x.codigo===e.codigo);return (m&&(m.tecnico||m.tec))||e.tecnicoAtual||''}
function css(){if(id('p40css'))return;var s=document.createElement('style');s.id='p40css';s.textContent='.baixaSteps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.baixaStep{border:1px solid #dbe4ef;background:#f8fafc;border-radius:14px;padding:10px}.baixaStep b{display:block;color:#0d1b2e}.baixaStep.on{border-color:#0f4c81;box-shadow:0 0 0 3px #0f4c8120}.baixaBox{display:grid;grid-template-columns:1fr 1fr;gap:14px}.baixaPreview{border:1px solid #dbe4ef;border-radius:16px;background:#f8fafc;padding:14px}.baixaActions button{width:100%;margin:6px 0;padding:13px}.baixaWarn{background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;padding:10px;margin:8px 0}@media(max-width:950px){.baixaSteps,.baixaBox{grid-template-columns:1fr}}';document.head.appendChild(s)}
var chosen=null;
function draw(){var p=id('p-descarte');if(!p)return;css();p.innerHTML='<div class="card"><h2>Baixa autorizada de equipamento</h2><p class="small">Fluxo seguro: localizar equipamento, registrar triagem, solicitar baixa e aprovar somente com responsável.</p><div class="baixaSteps"><div class="baixaStep on"><b>1. Localizar</b><small>MAC/SN/código</small></div><div class="baixaStep"><b>2. Triagem</b><small>Motivo e condição</small></div><div class="baixaStep"><b>3. Solicitar</b><small>Registra pedido</small></div><div class="baixaStep"><b>4. Aprovar</b><small>Baixa final</small></div></div><div class="baixaBox"><div><label><b>Pesquisar equipamento</b></label><input id="discSearch" placeholder="Bipe ou digite MAC, SN, código ou patrimônio"><div id="discPrev" class="baixaPreview">Nenhum equipamento selecionado.</div><label><b>Motivo da baixa</b></label><select id="discMotivo"><option>Queimado</option><option>Quebrado</option><option>Oxidação</option><option>Dano físico</option><option>Sem reparo</option><option>Extraviado</option><option>Outro</option></select><label><b>Solicitado por</b></label><input id="discSolic" placeholder="Nome de quem solicitou"><label><b>Aprovado por</b></label><input id="discAprov" placeholder="Obrigatório para aprovar"><label><b>Observação</b></label><textarea id="discObs" placeholder="Descreva o ocorrido. Ex: voltou quebrado, encontrado no lixo, sem fonte, etc."></textarea><div class="baixaWarn"><b>Regra:</b> equipamento quebrado não vai para o lixo. Primeiro registra solicitação, depois aprovação.</div><div class="baixaActions"><button id="discSolicitar" class="warn">1. Registrar solicitação de baixa</button><button id="discAprovar" class="bad">2. Aprovar baixa final</button></div><div id="discMsg" class="msg"></div></div><div><h3>Últimas baixas/solicitações</h3><div class="tbl"><table><thead><tr><th>Data</th><th>Equipamento</th><th>Responsável</th><th>Motivo</th><th>Status</th></tr></thead><tbody id="discTable"></tbody></table></div></div></div></div>'}
function prev(){chosen=findEq(id('discSearch')&&id('discSearch').value);var p=id('discPrev');if(!p)return;if(!chosen){p.innerHTML='<b>Equipamento não encontrado.</b><br><small>Confira MAC, SN, código ou patrimônio.</small>';p.className='baixaPreview rowBad';return}var resp=lastResp(chosen)||'-';p.className='baixaPreview';p.innerHTML='<b>'+safe(chosen.codigo)+' - '+safe(eqName(chosen))+'</b><br><small>MAC/SN: '+safe(chosen.mac||chosen.serial||'-')+'</small><br><small>Status atual: '+safe(chosen.status)+' | Local: '+safe(chosen.local||'-')+'</small><br><small>Responsável provável: <b>'+safe(resp)+'</b></small>'}
async function loadDisc(){try{D.descartes=await loadTable('descartes_autorizados','created_at',false)}catch(e){D.descartes=[]}}
function table(){var t=id('discTable');if(!t)return;t.innerHTML=(D.descartes||[]).slice(0,50).map(d=>'<tr><td>'+new Date(d.created_at).toLocaleDateString('pt-BR')+'</td><td><b>'+safe(d.codigo)+'</b><br><small>'+safe(d.modelo)+' '+safe(d.mac||d.serial||'')+'</small></td><td>'+safe(d.tecnico||'-')+'</td><td>'+safe(d.motivo)+'</td><td>'+safe(d.status)+'</td></tr>').join('')||'<tr><td colspan="5">Nenhum registro.</td></tr>'}
async function save(finalizar){try{if(!chosen)prev();if(!chosen){id('discMsg').textContent='Pesquise e selecione um equipamento válido.';id('discMsg').className='msg bad';return}var aprov=(id('discAprov').value||'').trim();if(finalizar&&!aprov){id('discMsg').textContent='Para aprovar a baixa, informe quem aprovou.';id('discMsg').className='msg bad';return}var tec=lastResp(chosen)||chosen.tecnicoAtual||'';var rec={equipamento_id:chosen.id,codigo:chosen.codigo,mac:chosen.mac,serial:chosen.serial,modelo:eqName(chosen),tecnico:tec,solicitado_por:id('discSolic').value||'',aprovado_por:aprov,motivo:id('discMotivo').value,status:finalizar?'Descartado':'Solicitado',observacao:id('discObs').value||'',aprovado_em:finalizar?new Date().toISOString():null,descartado_em:finalizar?new Date().toISOString():null};var r=await db().from('descartes_autorizados').insert(rec);if(r.error)throw r.error;if(finalizar){chosen.status='Descarte autorizado';chosen.local='Descarte autorizado';chosen.motivoAtual=rec.motivo;Object.assign(chosen,fromEq(await upd('equipamentos',chosen.id,toEq(chosen))));await mov(chosen,'Baixa autorizada',{tec:tec,dest:'Descarte autorizado',mot:rec.motivo,obs:'Aprovado por '+aprov+' | '+rec.observacao})}await loadDisc();table();id('discMsg').textContent=finalizar?'Baixa final aprovada e equipamento bloqueado.':'Solicitação registrada. Ainda não é baixa final.';id('discMsg').className='msg ok'}catch(e){id('discMsg').textContent='Erro: '+e.message;id('discMsg').className='msg bad'}}
function bind(){if(!id('p-descarte'))return;if(!id('discSearch'))draw();if(id('discSearch')&&!id('discSearch').dataset.p40){id('discSearch').dataset.p40=1;id('discSearch').oninput=prev;id('discSearch').onkeydown=e=>{if(e.key==='Enter')prev()}}if(id('discSolicitar'))id('discSolicitar').onclick=()=>save(false);if(id('discAprovar'))id('discAprovar').onclick=()=>save(true)}
async function boot(){if(id('p-descarte'))draw();bind();await loadDisc();table()}
setInterval(()=>{bind();table()},1200);document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1000));
})();