(function(){
function E(i){return document.getElementById(i)}
function S(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function N2(v){return Number(v||0)}
function cls(m){var c=(m.categoria_estoque||m.categoria||m.controle||'').toLowerCase();var text=((m.tipo||'')+' '+(m.modelo||'')).toLowerCase();if(c.includes('patrim')||c.includes('unit'))return 'Patrimônio';if(c.includes('fechado')||c.includes('pacote')||/drop|bobina|cabo de rede|cat5|cat6|internet/.test(text))return 'Material fechado';return 'Consumo'}
function unidade(m){return m.unidade_saida||m.unidade||(cls(m)==='Material fechado'?'Bobina':'Unidade')}
function isMat(m){return cls(m)!=='Patrimônio'}
async function tbl(t,o,a){try{return await loadTable(t,o||'created_at',a===undefined?false:a)}catch(e){return []}}
var saldos=[],movs=[];
function css(){if(E('p63css'))return;var st=document.createElement('style');st.id='p63css';st.textContent='.matHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.matGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.matKpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.matKpi div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2ff;font-size:12px;font-weight:900}@media(max-width:950px){.matGrid,.matKpi{grid-template-columns:1fr}}';document.head.appendChild(st)}
function nav(){var side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="materiais"]')){var r=document.querySelector('[data-p="entrada"]')||document.querySelector('[data-p="estoque"]');(r||side.lastElementChild).insertAdjacentHTML('afterend','<button class="nav" data-p="materiais">Materiais</button>')}document.querySelectorAll('.nav').forEach(function(b){if(b.dataset.p==='materiais')b.onclick=function(ev){ev.preventDefault();openMat()}})}
function page(){var main=document.querySelector('.main');if(!main||E('p-materiais'))return;main.insertAdjacentHTML('beforeend','<section id="p-materiais" class="page"><div class="matHero"><h2>Materiais</h2><p>Controle separado de Consumo, Material fechado e Patrimônio.</p></div><div class="matKpi" id="matKpis"></div><div class="matGrid"><div class="card"><h2>Entrada de material</h2><select id="matProduto"></select><input id="matQtd" type="number" min="1" placeholder="Quantidade"><select id="matLocal"><option>Estoque central</option></select><textarea id="matObs" placeholder="Observação"></textarea><button id="matEntrada" class="pri">Registrar entrada</button><div id="matMsg" class="msg"></div></div><div class="card"><h2>Saída para técnico</h2><select id="matProdutoS"></select><select id="matTec"></select><input id="matQtdS" type="number" min="1" placeholder="Quantidade"><textarea id="matObsS" placeholder="Observação"></textarea><button id="matSaida" class="ok">Enviar para técnico</button><div id="matMsgS" class="msg"></div></div></div><div class="card"><h2>Saldos de materiais</h2><input id="matBusca" placeholder="Buscar material, técnico ou local"><div class="tbl"><table><thead><tr><th>Categoria</th><th>Material</th><th>Unidade</th><th>Local</th><th>Técnico</th><th>Quantidade</th><th>Regra</th></tr></thead><tbody id="matSaldoT"></tbody></table></div></div><div class="card"><h2>Histórico de materiais</h2><div class="tbl"><table><thead><tr><th>Data</th><th>Material</th><th>Qtd</th><th>Origem</th><th>Destino</th><th>Técnico</th><th>Obs</th></tr></thead><tbody id="matMovT"></tbody></table></div></div></section>')}
function matModels(){return (D.modelos||[]).filter(isMat)}
function opt(){var opts='<option value="">Selecione material</option>'+matModels().map(function(m){return '<option value="'+m.id+'">'+S(cls(m))+' • '+S(m.tipo)+' '+S(m.marca||'')+' '+S(m.modelo)+' • '+S(unidade(m))+'</option>'}).join('');['matProduto','matProdutoS'].forEach(function(id){if(E(id))E(id).innerHTML=opts});if(E('matTec'))E('matTec').innerHTML='<option value="">Técnico</option>'+(D.tecnicos||[]).map(t=>'<option>'+S(t.nome)+'</option>').join('')}
function mm(id){var v=E(id)&&E(id).value;return matModels().find(x=>x.id===v)}
async function loadMat(){saldos=await tbl('materiais_saldos','updated_at',false);movs=await tbl('materiais_movimentos','created_at',false)}
async function upSaldo(m,local,tec,delta){var cat=cls(m),uni=unidade(m);var found=saldos.find(s=>s.tipo===m.tipo&&s.marca===(m.marca||null)&&s.modelo===m.modelo&&s.categoria===cat&&s.unidade_saida===uni&&s.local===local&&(s.tecnico||'')===(tec||''));if(found){var novo=N2(found.quantidade)+delta;var r=await db().from('materiais_saldos').update({quantidade:novo,updated_at:new Date().toISOString()}).eq('id',found.id).select().single();if(r.error)throw r.error;found.quantidade=novo;return}var row={modelo_id:m.id,tipo:m.tipo,marca:m.marca||null,modelo:m.modelo,categoria:cat,unidade_saida:uni,local:local,tecnico:tec||null,quantidade:delta,qtd_interna:N2(m.qtd_interna)||1};var insr=await db().from('materiais_saldos').insert(row).select().single();if(insr.error)throw insr.error;saldos.unshift(insr.data)}
async function mov(m,q,orig,dest,tec,obs){var row={modelo_id:m.id,tipo:m.tipo,marca:m.marca||null,modelo:m.modelo,categoria:cls(m),unidade_saida:unidade(m),quantidade:q,origem:orig,destino:dest,tecnico:tec||null,motivo:'Movimentação de material',obs:obs||''};var r=await db().from('materiais_movimentos').insert(row).select().single();if(r.error)throw r.error;movs.unshift(r.data)}
async function entrada(){try{var m=mm('matProduto'),q=N2(E('matQtd').value),loc=E('matLocal').value||'Estoque central';if(!m)return mmsg('matMsg','Selecione o material.','bad');if(!q||q<=0)return mmsg('matMsg','Informe a quantidade.','bad');await upSaldo(m,loc,'',q);await mov(m,q,'Entrada',loc,'',E('matObs').value);renderMat();mmsg('matMsg','Entrada registrada: '+q+' '+unidade(m)+'.','ok')}catch(e){mmsg('matMsg','Erro: '+e.message,'bad')}}
async function saida(){try{var m=mm('matProdutoS'),q=N2(E('matQtdS').value),tec=E('matTec').value;if(!m)return mmsg('matMsgS','Selecione o material.','bad');if(!tec)return mmsg('matMsgS','Selecione o técnico.','bad');if(!q||q<=0)return mmsg('matMsgS','Informe a quantidade.','bad');var central=saldos.find(s=>s.tipo===m.tipo&&s.modelo===m.modelo&&s.categoria===cls(m)&&s.local==='Estoque central'&&!(s.tecnico));if(!central||N2(central.quantidade)<q)return mmsg('matMsgS','Saldo insuficiente no estoque central.','bad');await upSaldo(m,'Estoque central','',-q);await upSaldo(m,'Técnico',tec,q);await mov(m,q,'Estoque central','Técnico',tec,E('matObsS').value);renderMat();mmsg('matMsgS','Saída registrada para '+tec+': '+q+' '+unidade(m)+'.','ok')}catch(e){mmsg('matMsgS','Erro: '+e.message,'bad')}}
function renderMat(){var q=(E('matBusca')&&E('matBusca').value||'').toLowerCase();var list=saldos.filter(s=>!q||Object.values(s).join(' ').toLowerCase().includes(q));var total=list.reduce((a,b)=>a+N2(b.quantidade),0);if(E('matKpis'))E('matKpis').innerHTML='<div><small>Registros</small><b>'+list.length+'</b></div><div><small>Total saldo</small><b>'+total+'</b></div><div><small>Consumo</small><b>'+list.filter(x=>x.categoria==='Consumo').length+'</b></div><div><small>Fechados</small><b>'+list.filter(x=>x.categoria==='Material fechado').length+'</b></div>';if(E('matSaldoT'))E('matSaldoT').innerHTML=list.map(function(s){return '<tr><td><span class="pill">'+S(s.categoria)+'</span></td><td>'+S(s.tipo+' '+(s.marca||'')+' '+s.modelo)+'</td><td>'+S(s.unidade_saida)+'</td><td>'+S(s.local)+'</td><td>'+S(s.tecnico||'-')+'</td><td><b>'+S(s.quantidade)+'</b></td><td>'+S(s.categoria==='Material fechado'?'Sai somente fechado':'Pode sair por quantidade')+'</td></tr>'}).join('')||'<tr><td colspan="7">Sem saldo.</td></tr>';if(E('matMovT'))E('matMovT').innerHTML=movs.slice(0,80).map(function(m){return '<tr><td>'+S(m.created_at?new Date(m.created_at).toLocaleString('pt-BR'):'')+'</td><td>'+S(m.tipo+' '+(m.marca||'')+' '+m.modelo)+'</td><td>'+S(m.quantidade+' '+m.unidade_saida)+'</td><td>'+S(m.origem||'-')+'</td><td>'+S(m.destino||'-')+'</td><td>'+S(m.tecnico||'-')+'</td><td>'+S(m.obs||'')+'</td></tr>'}).join('')||'<tr><td colspan="7">Sem histórico.</td></tr>'}
function mmsg(id,t,c){var e=E(id);if(e){e.textContent=t;e.className='msg '+(c||'')}}
function bind(){css();page();nav();opt();if(E('matEntrada'))E('matEntrada').onclick=entrada;if(E('matSaida'))E('matSaida').onclick=saida;if(E('matBusca'))E('matBusca').oninput=renderMat;renderMat()}
async function openMat(){bind();await loadMat();bind();document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('on'));E('p-materiais').classList.add('on');var b=document.querySelector('[data-p="materiais"]');if(b)b.classList.add('on');if(E('title'))E('title').textContent='Materiais'}
window.openMateriais=openMat;
setInterval(function(){nav();if(E('p-materiais')&&E('p-materiais').classList.contains('on'))renderMat()},1200);document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){bind();loadMat().then(renderMat)},2500)})
})();