(function(){
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v==null?'':v)}catch(e){return String(v==null?'':v)}}
function NR(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function BR(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2).replace('.',',')}}
function eqs(){return window.D&&Array.isArray(D.equipamentos)?D.equipamentos:[]}
function movs(){return window.D&&Array.isArray(D.movimentos)?D.movimentos:[]}
function tecs(){return window.D&&Array.isArray(D.tecnicos)?D.tecnicos:[]}
function nome(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function tecDireto(e){return (e.tecnicoAtual||e.tecnico_atual||e.tecnico||'').trim()}
function statusTec(e){return /com técnico|com tecnico|técnico|tecnico/i.test([e.status,e.local].join(' '))}
function eqKeyMatch(m,e){return (m.equipamento_id&&m.equipamento_id===e.id)||(m.codigo&&e.codigo&&m.codigo===e.codigo)||(m.mac&&e.mac&&m.mac===e.mac)||(m.serial&&e.serial&&m.serial===e.serial)}
function isMovSaida(m){return /saída|saida|técnico|tecnico/i.test([m.tipo,m.destino,m.motivo,m.status_final,m.statusFinal].join(' '))}
function tecMov(e){let arr=movs().filter(m=>eqKeyMatch(m,e)&&m.tecnico&&isMovSaida(m));return arr.length?String(arr[0].tecnico||'').trim():''}
function tecFinal(e){return tecDireto(e)||tecMov(e)||''}
function emPosseTecnico(e){return !!tecFinal(e)||statusTec(e)}
function naoFinalizado(e){return !/estoque|cliente|instalado|perdido|inutil|descarte/i.test(String(e.status||''))}
function tecnicoMap(){let map={};tecs().forEach(t=>{if(t&&t.nome)map[String(t.nome).trim()]=1});eqs().forEach(e=>{let t=tecFinal(e);if(t&&(emPosseTecnico(e)||naoFinalizado(e)))map[t]=1});movs().forEach(m=>{if(m&&m.tecnico&&isMovSaida(m))map[String(m.tecnico).trim()]=1});return map}
function refreshTecnicos(){let s=E('relTec');if(!s)return;let old=s.value;let arr=Object.keys(tecnicoMap()).filter(Boolean).sort((a,b)=>a.localeCompare(b,'pt-BR'));s.innerHTML='<option value="">Todos</option>'+arr.map(n=>'<option value="'+H(n)+'">'+H(n)+'</option>').join('');if(arr.includes(old))s.value=old;if(!E('relTecInfo')){s.insertAdjacentHTML('afterend','<div id="relTecInfo" class="small"></div>')}if(E('relTecInfo'))E('relTecInfo').textContent=arr.length+' técnico(s) disponíveis no filtro';}
function f(){return {q:NR(E('relQ')&&E('relQ').value),tec:E('relTec')?E('relTec').value:'',status:E('relStatus')?E('relStatus').value:''}}
function matchEq(e,F){let txt=[e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tecFinal(e),e.clienteAtual,e.cliente_atual,e.osAtual,e.os_atual].join(' ');return (!F.q||NR(txt).includes(F.q))&&(!F.tec||tecFinal(e)===F.tec)&&(!F.status||e.status===F.status)}
function table(cols,raw){return '<div class="tbl"><table><thead><tr>'+cols.map(c=>'<th>'+H(c)+'</th>').join('')+'</tr></thead><tbody>'+(raw.length?raw.map(r=>'<tr>'+r.map(c=>'<td>'+H(c)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+cols.length+'">Sem registros para os filtros aplicados.</td></tr>')+'</tbody></table></div>'}
function kpis(items){return '<div class="relKpis">'+items.map(i=>'<div><small>'+H(i[0])+'</small><b>'+H(i[1])+'</b></div>').join('')+'</div>'}
function show(rep){let out=E('relOut');if(!out)return;window.__relCore=rep;out.className='';out.innerHTML='<h2>'+H(rep.title)+'</h2><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button><button class="warn" onclick="relCsvCore()">Exportar CSV</button>'+(rep.whats?'<button class="ok" onclick="relWhatsCore()">Copiar WhatsApp</button>':'')+'</div>'+(rep.kpis?kpis(rep.kpis):'')+table(rep.cols,rep.raw);if(E('relPrintInfo'))E('relPrintInfo').textContent=rep.title+' • Gerado em '+new Date().toLocaleString('pt-BR');try{if(window.paginarTabelas)window.paginarTabelas()}catch(e){}}
function repTech(){refreshTecnicos();let F=f();let list=eqs().filter(e=>emPosseTecnico(e)&&naoFinalizado(e)&&matchEq(e,F));let raw=list.map(e=>[tecFinal(e)||'-',e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'',e.local||'',BR(e.custo||0)]);let total=list.reduce((s,e)=>s+Number(e.custo||0),0);show({title:'Estoque por técnico',cols:['Técnico','Código','Equipamento','MAC/SN','Status','Local','Valor'],raw,kpis:[['Equipamentos',list.length],['Valor',BR(total)],['Técnicos',[...new Set(raw.map(r=>r[0]).filter(x=>x&&x!=='-'))].length]]})}
function repCharge(){refreshTecnicos();let F=f();let name=F.tec||Object.keys(tecnicoMap()).filter(Boolean).sort()[0]||'';let list=eqs().filter(e=>tecFinal(e)===name&&naoFinalizado(e));let raw=list.map(e=>['Equipamento',e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'']);let whats='CONFERÊNCIA DE ESTOQUE\nTécnico: '+(name||'Não informado')+'\n\nEQUIPAMENTOS:\n'+(list.map(e=>'- '+(e.codigo||'')+' | '+nome(e)+' | MAC/SN: '+(e.mac||e.serial||'-')).join('\n')||'Sem equipamentos em posse.')+'\n\nFavor conferir e confirmar.';show({title:'Cobrança WhatsApp',cols:['Tipo','Código','Item','Identificação','Status'],raw,whats,kpis:[['Equipamentos',list.length]]})}
function install(){refreshTecnicos();if(window.runReportCore&&!window.runReportCore.__relSafeWrapper){window.__relSafeBaseRun=window.runReportCore}let base=window.__relSafeBaseRun;let wrap=function(id){try{refreshTecnicos();if(id==='tech')return repTech();if(id==='charge')return repCharge();return typeof base==='function'?base(id):null}catch(e){let out=E('relOut');if(out){out.className='msg bad';out.textContent='Erro ao gerar relatório: '+e.message}}};wrap.__relSafeWrapper=true;window.runReportCore=wrap;if(!window.relCsvCore){window.relCsvCore=function(){let r=window.__relCore;if(!r)return alert('Gere um relatório primeiro.');let csv=[r.cols.join(';')].concat((r.raw||[]).map(a=>a.map(x=>'"'+String(x==null?'':x).replace(/"/g,'""')+'"').join(';'))).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.title||'relatorio').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)}}if(!window.relWhatsCore){window.relWhatsCore=function(){let r=window.__relCore;if(!r||!r.whats)return alert('Este relatório não tem mensagem pronta.');navigator.clipboard.writeText(r.whats).then(()=>alert('Mensagem copiada.'))}}}
function patchPg(){if(window.__relSafePg||typeof pg!=='function')return;window.__relSafePg=true;let old=window.pg;window.pg=function(p){old(p);if(p==='relatorios')setTimeout(()=>{install();refreshTecnicos()},250)}}
function boot(){install();patchPg();let s=E('relTec');if(s&&!s.dataset.relSafe){s.dataset.relSafe='1';s.addEventListener('focus',refreshTecnicos);s.addEventListener('click',refreshTecnicos)}}
document.addEventListener('DOMContentLoaded',()=>{boot();setInterval(boot,2000)});window.relSafePatchInstall=boot;window.relSafeRefreshTecnicos=refreshTecnicos;
})();