(function(){
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v==null?'':v)}catch(e){return String(v==null?'':v)}}
function NR(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function ISO(v){if(!v)return '';var s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);var d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
function DBR(v){var s=ISO(v);if(!s)return '';var p=s.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
function BR(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2).replace('.',',')}}
function eqs(){return window.D&&D.equipamentos?D.equipamentos:[]}
function movs(){return window.D&&D.movimentos?D.movimentos:[]}
function mods(){return window.D&&D.modelos?D.modelos:[]}
function tecs(){return window.D&&D.tecnicos?D.tecnicos:[]}
function nome(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function cli(e){return e.clienteAtual||e.cliente_atual||e.cliente||''}
function os(e){return e.osAtual||e.os_atual||e.os||''}
function tecDireto(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function tecHistorico(e){var arr=movs().filter(function(m){return ((m.equipamento_id&&m.equipamento_id===e.id)||(m.codigo&&m.codigo===e.codigo)||(m.mac&&e.mac&&m.mac===e.mac)||(m.serial&&e.serial&&m.serial===e.serial))&&m.tecnico&&/saida|saída|técnico|tecnico/i.test([m.tipo,m.destino,m.motivo].join(' '))});return arr.length?arr[0].tecnico:''}
function tecEq(e){return tecDireto(e)||tecHistorico(e)||''}
function isComTecnico(e){return !!tecEq(e)||/com técnico|com tecnico|técnico|tecnico/i.test([e.status,e.local].join(' '))}
function css(){if(E('relSafeCss'))return;var s=document.createElement('style');s.id='relSafeCss';s.textContent='.relActions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.relKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.relKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.relKpis b{display:block;font-size:24px}@media(max-width:900px){.relKpis{grid-template-columns:1fr}}';document.head.appendChild(s)}
function refreshTecnicos(){var s=E('relTec');if(!s)return;var old=s.value;var map={};tecs().forEach(function(t){if(t.nome)map[t.nome]=1});eqs().forEach(function(e){var t=tecEq(e);if(t&&isComTecnico(e)&&!/estoque|cliente|instalado|perdido|inutil/i.test(e.status||''))map[t]=1});movs().forEach(function(m){if(m.tecnico)map[m.tecnico]=1});var arr=Object.keys(map).sort();s.innerHTML='<option value="">Todos</option>'+arr.map(function(n){return '<option value="'+H(n)+'">'+H(n)+'</option>'}).join('');if(arr.indexOf(old)>=0)s.value=old}
function getF(){return {q:NR(E('relQ')&&E('relQ').value),tec:E('relTec')?E('relTec').value:'',status:E('relStatus')?E('relStatus').value:'',start:E('relStart')?E('relStart').value:'',end:E('relEnd')?E('relEnd').value:'',period:period()}}
function period(){var a=E('relStart')&&E('relStart').value,b=E('relEnd')&&E('relEnd').value;if(!a&&!b)return 'Todos';return (a?DBR(a):'início')+' até '+(b?DBR(b):'hoje')}
function inDate(v,f){var d=ISO(v);if(!f.start&&!f.end)return true;if(!d)return false;if(f.start&&d<f.start)return false;if(f.end&&d>f.end)return false;return true}
function matchEq(e,f){var text=[e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tecEq(e),cli(e),os(e)].join(' ');return (!f.q||NR(text).indexOf(f.q)>=0)&&(!f.tec||tecEq(e)===f.tec)&&(!f.status||e.status===f.status)}
function movDate(m){return m.data||m.created_at||m.createdAt||m.dt}
function matchMov(m,f){var text=[m.tipo,m.codigo,m.mac,m.serial,m.tecnico,m.destino,m.cliente,m.os,m.motivo,m.obs,m.status_final,m.statusFinal].join(' ');return inDate(movDate(m),f)&&(!f.q||NR(text).indexOf(f.q)>=0)&&(!f.tec||m.tecnico===f.tec)}
function table(cols,raw){return '<div class="tbl"><table><thead><tr>'+cols.map(function(c){return '<th>'+H(c)+'</th>'}).join('')+'</tr></thead><tbody>'+(raw.length?raw.map(function(r){return '<tr>'+r.map(function(c){return '<td>'+H(c)+'</td>'}).join('')+'</tr>'}).join(''):'<tr><td colspan="'+cols.length+'">Sem registros para os filtros aplicados.</td></tr>')+'</tbody></table></div>'}
function kpis(items){return '<div class="relKpis">'+items.map(function(i){return '<div><small>'+H(i[0])+'</small><b>'+H(i[1])+'</b></div>'}).join('')+'</div>'}
function show(rep,f){var o=E('relOut');if(!o)return;window.__relCore=rep;if(E('relPrintInfo'))E('relPrintInfo').textContent=rep.title+' • Período: '+f.period+' • Gerado em '+new Date().toLocaleString('pt-BR');o.className='';o.innerHTML='<h2>'+H(rep.title)+'</h2><p class="small"><b>Período:</b> '+H(f.period)+'</p><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button><button class="warn" onclick="relCsvCore()">Exportar CSV</button>'+(rep.whats?'<button class="ok" onclick="relWhatsCore()">Copiar WhatsApp</button>':'')+'</div>'+(rep.kpis?kpis(rep.kpis):'')+table(rep.cols,rep.raw);try{if(window.paginarTabelas)window.paginarTabelas()}catch(e){}}
function repDaily(f){var list=movs().filter(function(m){return matchMov(m,f)});function c(re){return list.filter(function(m){return re.test(NR([m.tipo,m.motivo,m.status_final,m.statusFinal].join(' ')))}).length}var raw=[['Entradas',c(/entrada/)],['Saídas',c(/saida|saída/)],['Instalações',c(/instala/)],['Retornos',c(/retorno|devolu/)],['Baixas',c(/baixa|descarte|inutil|perdido/)],['Manutenção',c(/manut|teste/)],['Movimentos',list.length]];return {title:'Resumo operacional',cols:['Indicador','Quantidade'],raw:raw,kpis:raw}}
function repMov(f){var raw=movs().filter(function(m){return matchMov(m,f)}).map(function(m){return [DBR(movDate(m)),m.tipo||'',m.codigo||m.mac||m.serial||'',m.tecnico||'',m.destino||'',m.cliente||'',m.os||'',m.obs||m.motivo||'']});return {title:'Movimentações',cols:['Data','Tipo','Item','Técnico','Destino','Cliente','OS','Obs'],raw:raw}}
function repTech(f){var list=eqs().filter(isComTecnico).filter(function(e){return !/estoque|cliente|instalado|perdido|inutil/i.test(e.status||'')}).filter(function(e){return matchEq(e,f)});var raw=list.map(function(e){return [tecEq(e)||'-',e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'',e.local||'',BR(e.custo)]});var total=list.reduce(function(s,e){return s+Number(e.custo||0)},0);return {title:'Estoque por técnico',cols:['Técnico','Código','Equipamento','MAC/SN','Status','Local','Valor'],raw:raw,kpis:[['Equipamentos',list.length],['Valor',BR(total)],['Técnicos',Object.keys(raw.reduce(function(a,r){if(r[0]&&r[0]!=='-')a[r[0]]=1;return a},{})).length]]}}
function repCharge(f){var name=f.tec||Object.keys(eqs().reduce(function(a,e){var t=tecEq(e);if(t)a[t]=1;return a},{}))[0]||'';var list=eqs().filter(function(e){return tecEq(e)===name&&!/estoque|cliente|instalado|perdido|inutil/i.test(e.status||'')});var raw=list.map(function(e){return ['Equipamento',e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'']});var msg='CONFERÊNCIA DE ESTOQUE\nTécnico: '+(name||'Não informado')+'\n\nEQUIPAMENTOS:\n'+(list.map(function(e){return '- '+(e.codigo||'')+' | '+nome(e)+' | MAC/SN: '+(e.mac||e.serial||'-')}).join('\n')||'Sem equipamentos em posse.')+'\n\nFavor conferir e confirmar.';return {title:'Cobrança WhatsApp',cols:['Tipo','Código','Item','Identificação','Status'],raw:raw,whats:msg,kpis:[['Equipamentos',list.length]]}}
function repMat(f){var raw=[];try{raw=(window.MATS||[]).map(function(){return null}).filter(Boolean)}catch(e){}return {title:'Saldo de materiais',cols:['Aviso'],raw:[['Use a aba Materiais para saldos detalhados. Relatórios de equipamentos continuam ativos.']]}}
function repInst(f){var list=eqs().filter(function(e){return /cliente|instalado/i.test(e.status||'')&&matchEq(e,f)});var raw=list.map(function(e){return [cli(e)||'-',nome(e),e.mac||'',e.serial||'',e.codigo||'',tecEq(e)||'-',os(e)||'']});return {title:'Instalados',cols:['Cliente','Equipamento','MAC','SN','Código','Técnico','OS'],raw:raw,kpis:[['Instalados',list.length]]}}
function repRet(f){var raw=movs().filter(function(m){return matchMov(m,f)&&/retorno|devolu/i.test(NR([m.tipo,m.motivo].join(' ')))}).map(function(m){return [DBR(movDate(m)),m.cliente||'',m.codigo||'',m.mac||m.serial||'',m.destino||'',m.tecnico||'',m.obs||'']});return {title:'Retornos',cols:['Data','Cliente','Código','MAC/SN','Destino','Técnico','Obs'],raw:raw}}
function repLoss(f){var list=eqs().filter(function(e){return /baixa|descarte|perdido|inutil|quebrado/i.test([e.status,e.motivoAtual,e.motivo_atual,e.local].join(' '))&&matchEq(e,f)});var raw=list.map(function(e){return [e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'',tecEq(e)||'-',cli(e)||'-',BR(e.custo)]});return {title:'Baixas/descarte',cols:['Código','Equipamento','MAC/SN','Status','Técnico','Cliente','Valor'],raw:raw}}
function repIntel(f){var comTec=eqs().filter(isComTecnico).length,perdas=eqs().filter(function(e){return /perdido|inutil|descarte/i.test(e.status||'')});return {title:'Inteligência',cols:['Risco','Descrição'],raw:[['Equipamentos com técnico',comTec],['Perdas/baixas',perdas.length]],kpis:[['Eqp com técnico',comTec],['Perdas/baixas',perdas.length]]}}
function dispatch(id){var f=getF();var map={daily:repDaily,mov:repMov,hist:repMov,close:repDaily,tech:repTech,charge:repCharge,mat:repMat,min:repMat,inst:repInst,ret:repRet,loss:repLoss,intel:repIntel};var fn=map[id]||repDaily;var rep=fn(f);if(id==='close'){rep.title='Fechamento WhatsApp';rep.whats='FECHAMENTO DO ESTOQUE\nPeríodo: '+f.period+'\n\n'+rep.raw.map(function(r){return r[0]+': '+r[1]}).join('\n')}show(rep,f)}
function install(){css();refreshTecnicos();window.runReportCore=function(id){try{refreshTecnicos();dispatch(id)}catch(e){var o=E('relOut');if(o){o.className='msg bad';o.textContent='Erro ao gerar relatório: '+e.message}}};window.relCsvCore=function(){var r=window.__relCore;if(!r)return alert('Gere um relatório primeiro.');var csv=[r.cols.join(';')].concat((r.raw||[]).map(function(a){return a.map(function(x){return '"'+String(x==null?'':x).replace(/"/g,'""')+'"'}).join(';')})).join('\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.title||'relatorio').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)};window.relWhatsCore=function(){var r=window.__relCore;if(!r||!r.whats)return alert('Este relatório não tem mensagem pronta.');navigator.clipboard.writeText(r.whats).then(function(){alert('Mensagem copiada.')})}}
document.addEventListener('DOMContentLoaded',function(){[500,2000,5000,10000,16000].forEach(function(t){setTimeout(install,t)})});window.relSafePatchInstall=install;
})();