(function(){
let EQ=[],TEC=[],MOV=[];
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function NR(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function BR(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2).replace('.',',')}}
function ISO(v){if(!v)return '';let s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
function DBR(v){let s=ISO(v);if(!s)return '';let p=s.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
function nome(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function tec(e){return String(e.tecnico_atual||e.tecnicoAtual||e.tecnico||'').trim()}
function isTec(e){return (!!tec(e)||/técnico|tecnico|com técnico|com tecnico/i.test([e.status,e.local].join(' ')))&&!/estoque|cliente|instalado|perdido|inutil|descarte/i.test(String(e.status||''))}
async function loadDb(){try{let r=await db().from('equipamentos').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;EQ=r.data||[]}catch(e){EQ=(D&&D.equipamentos)||[]}try{let r=await db().from('tecnicos').select('*').order('nome',{ascending:true});if(r.error)throw r.error;TEC=r.data||[]}catch(e){TEC=(D&&D.tecnicos)||[]}try{let r=await db().from('movimentos').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;MOV=r.data||[]}catch(e){MOV=(D&&D.movimentos)||[]}}
function css(){if(E('relCoreCss'))return;let s=document.createElement('style');s.id='relCoreCss';s.textContent='.relHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.relFilter{display:grid;grid-template-columns:1.2fr .7fr .7fr .7fr .8fr .8fr;gap:10px}.relBlocks{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.relBlock{border:1px solid #e5e7eb;border-radius:18px;padding:16px;background:white;box-shadow:0 10px 28px #0f172a12}.relBtns{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.relBtns button{text-align:left;min-height:44px}.relActions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.relKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.relKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.relKpis b{display:block;font-size:24px}.relPrintHead{display:none}@media(max-width:1000px){.relFilter,.relBlocks,.relBtns,.relKpis{grid-template-columns:1fr}}@media print{body *{visibility:hidden!important}#relResultado,#relResultado *{visibility:visible!important}#relResultado{position:absolute;left:0;top:0;width:100%;padding:20px;background:white}.relActions,.relNoPrint,.pgTblCtl{display:none!important}.relPrintHead{display:block!important}}';document.head.appendChild(s)}
function page(){css();let main=document.querySelector('.main');if(!main)return;let sec=E('p-relatorios');if(!sec){let ref=E('p-historico')||E('p-cadastros')||main.lastElementChild;ref.insertAdjacentHTML('beforebegin','<section id="p-relatorios" class="page"></section>');sec=E('p-relatorios')}sec.innerHTML='<div class="relHero"><h2>Relatórios</h2><p>Relatórios operacionais, técnicos e de auditoria.</p></div><div class="card relNoPrint"><h2>Filtros globais</h2><div class="relFilter"><div><label>Busca</label><input id="relQ" placeholder="MAC, SN, código, técnico, cliente"></div><div><label>Período</label><select id="relPreset"><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="all">Todos</option></select></div><div><label>Data inicial</label><input id="relStart" type="date"></div><div><label>Data final</label><input id="relEnd" type="date"></div><div><label>Técnico</label><select id="relTec"></select></div><div><label>Status</label><select id="relStatus"></select></div></div><p id="relTecInfo" class="small"></p></div><div id="relBlocks" class="relBlocks relNoPrint"></div><div class="card" id="relResultado"><div class="relPrintHead"><h2>LIKE internet - Relatório de Estoque</h2><p id="relPrintInfo"></p></div><h2>Resultado</h2><div id="relOut" class="msg">Selecione um relatório acima.</div></div>';fillFilters();blocks();preset()}
function tecnicosFiltro(){let map={};TEC.forEach(t=>{if(t.nome)map[String(t.nome).trim()]=1});EQ.forEach(e=>{if(tec(e)&&isTec(e))map[tec(e)]=1});MOV.forEach(m=>{if(m.tecnico&&/saída|saida|técnico|tecnico/i.test([m.tipo,m.destino,m.motivo].join(' ')))map[String(m.tecnico).trim()]=1});return Object.keys(map).filter(Boolean).sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function fillFilters(){let s=E('relTec');if(s){let old=s.value,arr=tecnicosFiltro();s.innerHTML='<option value="">Todos</option>'+arr.map(n=>'<option value="'+H(n)+'">'+H(n)+'</option>').join('');if(arr.includes(old))s.value=old;if(E('relTecInfo'))E('relTecInfo').textContent='Filtro técnico direto do banco: '+arr.length+' técnico(s).'}let st=E('relStatus');if(st){let old=st.value,arr=[...new Set(EQ.map(e=>e.status).filter(Boolean))].sort();st.innerHTML='<option value="">Todos</option>'+arr.map(n=>'<option value="'+H(n)+'">'+H(n)+'</option>').join('');if(arr.includes(old))st.value=old}}
function preset(){let p=E('relPreset')&&E('relPreset').value,a=E('relStart'),b=E('relEnd');if(!a||!b)return;let now=new Date(),ini=new Date();if(p==='all'){a.value='';b.value='';return}if(p==='7')ini.setDate(now.getDate()-6);else if(p==='30')ini.setDate(now.getDate()-29);a.value=ini.toISOString().slice(0,10);b.value=now.toISOString().slice(0,10);E('relPreset').onchange=preset}
function blocks(){let g={'1. Operação diária':[['daily','Resumo operacional'],['mov','Movimentações'],['close','Fechamento WhatsApp']],'2. Técnicos':[['tech','Estoque por técnico'],['charge','Cobrança WhatsApp']],'3. Materiais':[['mat','Saldo de materiais']],'4. Clientes / campo':[['inst','Instalados'],['ret','Retornos']],'5. Auditoria e inteligência':[['loss','Baixas/descarte'],['intel','Inteligência']]};E('relBlocks').innerHTML=Object.keys(g).map(t=>'<div class="relBlock"><h3>'+H(t)+'</h3><div class="relBtns">'+g[t].map(x=>'<button onclick="runReportCore(\''+x[0]+'\')">'+H(x[1])+'</button>').join('')+'</div></div>').join('')}
function F(){return {q:NR(E('relQ')&&E('relQ').value),tec:E('relTec')?E('relTec').value:'',status:E('relStatus')?E('relStatus').value:'',start:E('relStart')?E('relStart').value:'',end:E('relEnd')?E('relEnd').value:'',period:period()}}
function period(){let a=E('relStart')&&E('relStart').value,b=E('relEnd')&&E('relEnd').value;if(!a&&!b)return 'Todos';return (a?DBR(a):'início')+' até '+(b?DBR(b):'hoje')}
function inDate(v,f){let d=ISO(v);if(!f.start&&!f.end)return true;if(!d)return false;if(f.start&&d<f.start)return false;if(f.end&&d>f.end)return false;return true}
function matchEq(e,f){let txt=[e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tec(e),e.cliente_atual,e.os_atual].join(' ');return (!f.q||NR(txt).includes(f.q))&&(!f.tec||tec(e)===f.tec)&&(!f.status||e.status===f.status)}
function matchMov(m,f){let txt=[m.tipo,m.codigo,m.mac,m.serial,m.tecnico,m.destino,m.cliente,m.os,m.motivo,m.obs].join(' ');return inDate(m.data||m.created_at,f)&&(!f.q||NR(txt).includes(f.q))&&(!f.tec||m.tecnico===f.tec)}
function table(cols,raw){return '<div class="tbl"><table><thead><tr>'+cols.map(c=>'<th>'+H(c)+'</th>').join('')+'</tr></thead><tbody>'+(raw.length?raw.map(r=>'<tr>'+r.map(c=>'<td>'+H(c)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+cols.length+'">Sem registros para os filtros aplicados.</td></tr>')+'</tbody></table></div>'}
function kpis(items){return '<div class="relKpis">'+items.map(i=>'<div><small>'+H(i[0])+'</small><b>'+H(i[1])+'</b></div>').join('')+'</div>'}
function show(rep,f){window.__relCore=rep;let o=E('relOut');if(!o)return;o.className='';o.innerHTML='<h2>'+H(rep.title)+'</h2><p class="small"><b>Período:</b> '+H(f.period)+'</p><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button><button class="warn" onclick="relCsvCore()">Exportar CSV</button>'+(rep.whats?'<button class="ok" onclick="relWhatsCore()">Copiar WhatsApp</button>':'')+'</div>'+(rep.kpis?kpis(rep.kpis):'')+table(rep.cols,rep.raw);if(E('relPrintInfo'))E('relPrintInfo').textContent=rep.title+' • '+f.period+' • '+new Date().toLocaleString('pt-BR')}
function repTech(f){let list=EQ.filter(e=>isTec(e)&&matchEq(e,f));let raw=list.map(e=>[tec(e)||'-',e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'',e.local||'',BR(e.custo)]);return {title:'Estoque por técnico',cols:['Técnico','Código','Equipamento','MAC/SN','Status','Local','Valor'],raw,kpis:[['Equipamentos',list.length],['Técnicos',[...new Set(raw.map(r=>r[0]).filter(x=>x&&x!=='-'))].length]]}}
function repCharge(f){let name=f.tec||tecnicosFiltro()[0]||'',list=EQ.filter(e=>tec(e)===name&&isTec(e));let raw=list.map(e=>['Equipamento',e.codigo||'',nome(e),e.mac||e.serial||'',e.status||'']);let whats='CONFERÊNCIA DE ESTOQUE\nTécnico: '+(name||'Não informado')+'\n\nEQUIPAMENTOS:\n'+(list.map(e=>'- '+(e.codigo||'')+' | '+nome(e)+' | MAC/SN: '+(e.mac||e.serial||'-')).join('\n')||'Sem equipamentos em posse.')+'\n\nFavor conferir e confirmar.';return {title:'Cobrança WhatsApp',cols:['Tipo','Código','Item','Identificação','Status'],raw,whats,kpis:[['Equipamentos',list.length]]}}
function repMov(f){let raw=MOV.filter(m=>matchMov(m,f)).map(m=>[DBR(m.data||m.created_at),m.tipo||'',m.codigo||m.mac||m.serial||'',m.tecnico||'',m.destino||'',m.cliente||'',m.os||'',m.obs||m.motivo||'']);return {title:'Movimentações',cols:['Data','Tipo','Item','Técnico','Destino','Cliente','OS','Obs'],raw}}
function repDaily(f){let m=MOV.filter(x=>matchMov(x,f)),c=re=>m.filter(x=>re.test(NR([x.tipo,x.motivo,x.status_final].join(' ')))).length;let raw=[['Entradas',c(/entrada/)],['Saídas',c(/saida|saída/)],['Instalações',c(/instala/)],['Retornos',c(/retorno|devolu/)],['Baixas',c(/baixa|descarte|inutil|perdido/)],['Movimentos',m.length]];return {title:'Resumo operacional',cols:['Indicador','Quantidade'],raw,kpis:raw}}
function repGeneric(title){return {title,cols:['Aviso'],raw:[['Relatório em consolidação. Use Movimentações, Estoque por técnico e Cobrança WhatsApp como base principal.']]}}
window.runReportCore=async function(id){try{await loadDb();fillFilters();let f=F(),map={daily:repDaily,mov:repMov,close:repDaily,tech:repTech,charge:repCharge,mat:()=>repGeneric('Saldo de materiais'),inst:()=>repGeneric('Instalados'),ret:repMov,loss:()=>repGeneric('Baixas/descarte'),intel:()=>repGeneric('Inteligência')};let rep=(map[id]||repDaily)(f);if(id==='close'){rep.title='Fechamento WhatsApp';rep.whats='FECHAMENTO DO ESTOQUE\nPeríodo: '+f.period+'\n\n'+rep.raw.map(r=>r[0]+': '+r[1]).join('\n')}show(rep,f)}catch(e){let o=E('relOut');if(o){o.className='msg bad';o.textContent='Erro ao gerar relatório: '+e.message}}}
window.relCsvCore=function(){let r=window.__relCore;if(!r)return alert('Gere um relatório primeiro.');let csv=[r.cols.join(';')].concat((r.raw||[]).map(a=>a.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(';'))).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.title||'relatorio').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)}
window.relWhatsCore=function(){let r=window.__relCore;if(!r||!r.whats)return alert('Este relatório não tem mensagem pronta.');navigator.clipboard.writeText(r.whats).then(()=>alert('Mensagem copiada.'))}
async function boot(){page();await loadDb();fillFilters();blocks()}document.addEventListener('DOMContentLoaded',()=>{[500,1500,4000,9000,15000].forEach(t=>setTimeout(()=>boot().catch(()=>{}),t))});window.relatoriosCoreBoot=boot;
})();