(function(){
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v==null?'':v)}catch(e){return String(v==null?'':v)}}
function NR(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function BR(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2).replace('.',',')}}
let EQ=[],TEC=[],MOV=[];
function nm(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function tecEq(e){return (e.tecnico_atual||e.tecnicoAtual||e.tecnico||'').trim()}
function isPosse(e){return /com técnico|com tecnico|técnico|tecnico/i.test([e.status,e.local].join(' '))||!!tecEq(e)}
function isAtivoTec(e){return isPosse(e)&&!/estoque|cliente|instalado|perdido|inutil|descarte/i.test(String(e.status||''))}
async function fetchDb(){try{let a=await db().from('equipamentos').select('*').order('created_at',{ascending:false});if(a.error)throw a.error;EQ=a.data||[]}catch(e){EQ=(D&&D.equipamentos)||[]}try{let b=await db().from('tecnicos').select('*').order('nome',{ascending:true});if(b.error)throw b.error;TEC=b.data||[]}catch(e){TEC=(D&&D.tecnicos)||[]}try{let c=await db().from('movimentos').select('*').order('created_at',{ascending:false});if(c.error)throw c.error;MOV=c.data||[]}catch(e){MOV=(D&&D.movimentos)||[]}}
function tecnicosReais(){let map={};TEC.forEach(t=>{if(t.nome)map[String(t.nome).trim()]=1});EQ.forEach(e=>{let t=tecEq(e);if(t&&isAtivoTec(e))map[t]=1});MOV.forEach(m=>{if(m.tecnico&&/saida|saída|técnico|tecnico/i.test([m.tipo,m.destino,m.motivo].join(' ')))map[String(m.tecnico).trim()]=1});return Object.keys(map).filter(Boolean).sort((a,b)=>a.localeCompare(b,'pt-BR'))}
async function refreshTec(){await fetchDb();let s=E('relTec');if(!s)return;let old=s.value;let arr=tecnicosReais();s.innerHTML='<option value="">Todos</option>'+arr.map(n=>'<option value="'+H(n)+'">'+H(n)+'</option>').join('');if(arr.includes(old))s.value=old;if(!E('relTecDbInfo'))s.insertAdjacentHTML('afterend','<div id="relTecDbInfo" class="small"></div>');if(E('relTecDbInfo'))E('relTecDbInfo').textContent='Filtro atualizado direto do banco: '+arr.length+' técnico(s).'}
function F(){return {q:NR(E('relQ')&&E('relQ').value),tec:E('relTec')?E('relTec').value:'',status:E('relStatus')?E('relStatus').value:''}}
function match(e,f){let txt=[e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tecEq(e),e.cliente_atual,e.os_atual].join(' ');return (!f.q||NR(txt).includes(f.q))&&(!f.tec||tecEq(e)===f.tec)&&(!f.status||e.status===f.status)}
function table(cols,raw){return '<div class="tbl"><table><thead><tr>'+cols.map(c=>'<th>'+H(c)+'</th>').join('')+'</tr></thead><tbody>'+(raw.length?raw.map(r=>'<tr>'+r.map(c=>'<td>'+H(c)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+cols.length+'">Sem registros para os filtros aplicados.</td></tr>')+'</tbody></table></div>'}
function kpis(items){return '<div class="relKpis">'+items.map(i=>'<div><small>'+H(i[0])+'</small><b>'+H(i[1])+'</b></div>').join('')+'</div>'}
function show(rep){let o=E('relOut');if(!o)return;window.__relCore=rep;o.className='';o.innerHTML='<h2>'+H(rep.title)+'</h2><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button><button class="warn" onclick="relCsvCore()">Exportar CSV</button>'+(rep.whats?'<button class="ok" onclick="relWhatsCore()">Copiar WhatsApp</button>':'')+'</div>'+(rep.kpis?kpis(rep.kpis):'')+table(rep.cols,rep.raw);if(E('relPrintInfo'))E('relPrintInfo').textContent=rep.title+' • Gerado em '+new Date().toLocaleString('pt-BR')}
async function repTech(){await refreshTec();let f=F();let list=EQ.filter(isAtivoTec).filter(e=>match(e,f));let raw=list.map(e=>[tecEq(e)||'-',e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'',e.local||'',BR(e.custo)]);let total=list.reduce((s,e)=>s+Number(e.custo||0),0);show({title:'Estoque por técnico',cols:['Técnico','Código','Equipamento','MAC/SN','Status','Local','Valor'],raw,kpis:[['Equipamentos',list.length],['Valor',BR(total)],['Técnicos',[...new Set(raw.map(r=>r[0]).filter(x=>x&&x!=='-'))].length]]})}
async function repCharge(){await refreshTec();let f=F();let name=f.tec||tecnicosReais()[0]||'';let list=EQ.filter(e=>tecEq(e)===name&&isAtivoTec(e));let raw=list.map(e=>['Equipamento',e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'']);let whats='CONFERÊNCIA DE ESTOQUE\nTécnico: '+(name||'Não informado')+'\n\nEQUIPAMENTOS:\n'+(list.map(e=>'- '+(e.codigo||'')+' | '+nm(e)+' | MAC/SN: '+(e.mac||e.serial||'-')).join('\n')||'Sem equipamentos em posse.')+'\n\nFavor conferir e confirmar.';show({title:'Cobrança WhatsApp',cols:['Tipo','Código','Item','Identificação','Status'],raw,whats,kpis:[['Equipamentos',list.length]]})}
function install(){if(!window.__relDbBase&&window.runReportCore)window.__relDbBase=window.runReportCore;window.runReportCore=async function(id){try{if(id==='tech')return await repTech();if(id==='charge')return await repCharge();if(window.__relDbBase)return window.__relDbBase(id)}catch(e){let o=E('relOut');if(o){o.className='msg bad';o.textContent='Erro ao gerar relatório: '+e.message}}};if(!window.relCsvCore){window.relCsvCore=function(){let r=window.__relCore;if(!r)return alert('Gere um relatório primeiro.');let csv=[r.cols.join(';')].concat((r.raw||[]).map(a=>a.map(x=>'"'+String(x==null?'':x).replace(/"/g,'""')+'"').join(';'))).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.title||'relatorio').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)}}refreshTec().catch(()=>{})}
function boot(){install();let s=E('relTec');if(s&&!s.dataset.dbPatch){s.dataset.dbPatch='1';s.addEventListener('focus',()=>refreshTec());s.addEventListener('click',()=>refreshTec())}}
document.addEventListener('DOMContentLoaded',()=>{[1000,3000,7000,12000,18000].forEach(t=>setTimeout(boot,t));setInterval(boot,3000)});window.relDbPatchBoot=boot;window.relDbRefreshTecnicos=refreshTec;
})();