(function(){
let MOVS=[],MATS=[];
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function NR(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function BR(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function ISO(v){if(!v)return '';let s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
function DBR(v){let s=ISO(v);if(!s)return '';let p=s.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
function eqs(){return (window.D&&D.equipamentos)||[]}
function mods(){return (window.D&&D.modelos)||[]}
function tecs(){return (window.D&&D.tecnicos)||[]}
function nm(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function cli(e){return e.clienteAtual||e.cliente_atual||e.cliente||''}
function os(e){return e.osAtual||e.os_atual||e.os||''}
function tecDireto(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function tecMov(e){let arr=((window.D&&D.movimentos)||MOVS||[]).filter(m=>(m.equipamento_id&&m.equipamento_id===e.id)||(m.codigo&&m.codigo===e.codigo)).filter(m=>m.tecnico&&/sa[ií]da|tecnico|técnico/i.test([m.tipo,m.destino,m.motivo].join(' ')));return arr.length?arr[0].tecnico:''}
function tec(e){return tecDireto(e)||tecMov(e)||''}
function md(m){return ISO(m.data||m.created_at||m.createdAt||m.dt)}
function mt(m){return [m.tipo,m.codigo,m.mac,m.serial,m.tecnico,m.destino,m.cliente,m.os,m.motivo,m.obs,m.status_final,m.statusFinal].join(' ')}
async function loadExtra(){try{MOVS=await loadTable('movimentos','created_at',false)}catch(e){MOVS=(D&&(D.movimentos||D.movs))||[]}try{MATS=await loadTable('materiais_saldos','tipo',true)}catch(e){MATS=[]}}
function css(){if(E('relCoreCss'))return;let s=document.createElement('style');s.id='relCoreCss';s.textContent='.relHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.relFilter{display:grid;grid-template-columns:1.2fr .7fr .7fr .7fr .8fr .8fr;gap:10px}.relFilter label{font-size:12px;font-weight:900;color:#64748b}.relBlocks{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.relBlock{border:1px solid #e5e7eb;border-radius:18px;padding:16px;background:white;box-shadow:0 10px 28px #0f172a12}.relBtns{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.relBtns button{text-align:left;min-height:44px}.relKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.relKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.relKpis b{display:block;font-size:24px}.relActions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.relPrintHead{display:none}@media(max-width:1000px){.relFilter,.relBlocks,.relKpis,.relBtns{grid-template-columns:1fr}}@media print{body *{visibility:hidden!important}#relResultado,#relResultado *{visibility:visible!important}#relResultado{position:absolute;left:0;top:0;width:100%;padding:20px;background:white}.relActions,.pgTblCtl,.relNoPrint{display:none!important}.relPrintHead{display:block!important}.tbl table tbody tr{display:table-row!important}}';document.head.appendChild(s)}
function page(){css();let main=document.querySelector('.main');if(!main)return;let sec=E('p-relatorios');if(!sec){let ref=E('p-historico')||E('p-cadastros')||main.lastElementChild;ref.insertAdjacentHTML('beforebegin','<section id="p-relatorios" class="page"></section>');sec=E('p-relatorios')}sec.dataset.core='1';sec.innerHTML='<div class="relHero"><h2>Relatórios</h2><p>Módulo central de relatórios operacionais, técnicos, materiais e auditoria.</p></div><div class="card relNoPrint"><h2>Filtros globais</h2><div class="relFilter"><div><label>Busca</label><input id="relQ" placeholder="MAC, SN, código, técnico, cliente, material"></div><div><label>Período</label><select id="relPreset"><option value="today">Hoje</option><option value="yesterday">Ontem</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="month">Este mês</option><option value="all">Todos</option><option value="custom">Personalizado</option></select></div><div><label>Data inicial</label><input id="relStart" type="date"></div><div><label>Data final</label><input id="relEnd" type="date"></div><div><label>Técnico</label><select id="relTec"></select></div><div><label>Status</label><select id="relStatus"></select></div></div><p class="small">Movimentações usam período. Estoque por técnico e posição atual usam o estado atual dos equipamentos.</p></div><div id="relBlocks" class="relBlocks relNoPrint"></div><div class="card" id="relResultado"><div class="relPrintHead"><h2>LIKE internet - Relatório de Estoque</h2><p id="relPrintInfo"></p></div><h2>Resultado</h2><div id="relOut" class="msg">Selecione um relatório acima.</div></div>';fillFilters();blocks();bind()}
function preset(force){let p=E('relPreset')?E('relPreset').value:'today',a=E('relStart'),b=E('relEnd');if(!a||!b)return;if(p==='custom'&&!force)return;let x=new Date(),y=new Date();if(p==='all'){a.value='';b.value='';return}if(p==='yesterday'){x.setDate(x.getDate()-1);y.setDate(y.getDate()-1)}if(p==='7')x.setDate(x.getDate()-6);if(p==='30')x.setDate(x.getDate()-29);if(p==='month')x=new Date(y.getFullYear(),y.getMonth(),1);a.value=x.toISOString().slice(0,10);b.value=y.toISOString().slice(0,10)}
function fillFilters(){let s=E('relTec');if(s){let old=s.value;let arr=[...new Set(tecs().map(t=>t.nome).concat(eqs().map(tec)).concat(MATS.map(m=>m.tecnico)).filter(Boolean))].sort();s.innerHTML='<option value="">Todos</option>'+arr.map(x=>'<option value="'+H(x)+'">'+H(x)+'</option>').join('');if(arr.includes(old))s.value=old}let st=E('relStatus');if(st){let old=st.value;let arr=[...new Set(eqs().map(e=>e.status).filter(Boolean))].sort();st.innerHTML='<option value="">Todos</option>'+arr.map(x=>'<option value="'+H(x)+'">'+H(x)+'</option>').join('');if(arr.includes(old))st.value=old}preset(false)}
const R={daily:['1. Operação diária','Resumo operacional',1,repDaily],mov:['1. Operação diária','Movimentações',1,repMov],hist:['1. Operação diária','Histórico do item',1,repHist],close:['1. Operação diária','Fechamento WhatsApp',1,repClose],tech:['2. Técnicos','Estoque por técnico',0,repTech],charge:['2. Técnicos','Cobrança WhatsApp',0,repCharge],mat:['3. Materiais','Saldo de materiais',0,repMat],min:['3. Materiais','Estoque mínimo',0,repMin],inst:['4. Clientes / campo','Instalados',0,repInst],ret:['4. Clientes / campo','Retornos',1,repRet],loss:['5. Auditoria e inteligência','Baixas/descarte',0,repLoss],intel:['5. Auditoria e inteligência','Inteligência',0,repIntel]};
function blocks(){let box=E('relBlocks');if(!box)return;let g={};Object.keys(R).forEach(k=>{let r=R[k];(g[r[0]]||(g[r[0]]=[])).push([k,r])});box.innerHTML=Object.keys(g).map(t=>'<div class="relBlock"><h3>'+H(t)+'</h3><div class="relBtns">'+g[t].map(x=>'<button onclick="runReportCore(\''+x[0]+'\')"><b>'+H(x[1][1])+'</b><br><small>'+(x[1][2]?'usa período':'posição atual')+'</small></button>').join('')+'</div></div>').join('')}
function bind(){if(E('relPreset')&&!E('relPreset').dataset.b){E('relPreset').dataset.b='1';E('relPreset').onchange=()=>preset(true)};['relStart','relEnd'].forEach(id=>{if(E(id))E(id).onchange=()=>{if(E('relPreset'))E('relPreset').value='custom'}})}
function F(){return {q:NR(E('relQ')&&E('relQ').value),start:E('relStart')?E('relStart').value:'',end:E('relEnd')?E('relEnd').value:'',tec:E('relTec')?E('relTec').value:'',status:E('relStatus')?E('relStatus').value:'',period:period()}}
function period(){let a=E('relStart')&&E('relStart').value,b=E('relEnd')&&E('relEnd').value;if(!a&&!b)return 'Todos';return (a?DBR(a):'início')+' até '+(b?DBR(b):'hoje')}
function inDate(v,f){let d=ISO(v);if(!f.start&&!f.end)return true;if(!d)return false;if(f.start&&d<f.start)return false;if(f.end&&d>f.end)return false;return true}
function fm(f){return MOVS.filter(m=>inDate(md(m),f)).filter(m=>!f.q||NR(mt(m)).includes(f.q)).filter(m=>!f.tec||m.tecnico===f.tec)}
function fe(list,f){return list.filter(e=>!f.q||NR([e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tec(e),cli(e),os(e)].join(' ')).includes(f.q)).filter(e=>!f.tec||tec(e)===f.tec).filter(e=>!f.status||e.status===f.status)}
function table(cols,raw){return '<div class="tbl"><table><thead><tr>'+cols.map(c=>'<th>'+H(c)+'</th>').join('')+'</tr></thead><tbody>'+(raw.length?raw.map(a=>'<tr>'+a.map(c=>'<td>'+H(c)+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+cols.length+'">Sem registros para os filtros aplicados.</td></tr>')+'</tbody></table></div>'}
function kpis(items){return '<div class="relKpis">'+items.map(i=>'<div><small>'+H(i[0])+'</small><b>'+H(i[1])+'</b></div>').join('')+'</div>'}
function out(rep,f){let o=E('relOut');if(!o)return;window.__relCore=rep;if(E('relPrintInfo'))E('relPrintInfo').textContent=rep.title+' • Período: '+f.period+' • Gerado em '+new Date().toLocaleString('pt-BR');o.className='';o.innerHTML='<h2>'+H(rep.title)+'</h2><p class="small"><b>Período:</b> '+H(f.period)+'</p><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button><button class="warn" onclick="relCsvCore()">Exportar CSV</button>'+(rep.whats?'<button class="ok" onclick="relWhatsCore()">Copiar WhatsApp</button>':'')+'</div>'+(rep.kpis?kpis(rep.kpis):'')+table(rep.cols,rep.raw);try{if(window.paginarTabelas)window.paginarTabelas()}catch(e){}}
window.runReportCore=async function(id){try{await loadExtra();fillFilters();let f=F(),r=R[id];if(!r)throw Error('Relatório não encontrado');out(await r[3](f),f)}catch(e){let o=E('relOut');if(o){o.className='msg bad';o.textContent='Erro ao gerar relatório: '+e.message}}}
window.relCsvCore=function(){let r=window.__relCore;if(!r)return alert('Gere um relatório primeiro.');let csv=[r.cols.join(';')].concat((r.raw||[]).map(a=>a.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';'))).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.title||'relatorio').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)}
window.relWhatsCore=function(){let r=window.__relCore;if(!r||!r.whats)return alert('Este relatório não tem mensagem pronta.');navigator.clipboard.writeText(r.whats).then(()=>alert('Mensagem copiada.'))}
function repDaily(f){let m=fm(f),c=re=>m.filter(x=>re.test(NR([x.tipo,x.motivo,x.status_final,x.statusFinal].join(' ')))).length;let raw=[['Entradas',c(/entrada/)],['Saídas',c(/saida|saída/)],['Instalações',c(/instala/)],['Retornos',c(/retorno|devolu/)],['Baixas',c(/baixa|descarte|inutil|perdido/)],['Manutenção',c(/manut|teste/)],['Movimentos',m.length]];return {title:'Resumo operacional',cols:['Indicador','Quantidade'],raw,kpis:raw}}
function repMov(f){let raw=fm(f).map(m=>[DBR(md(m)),m.tipo||'',m.codigo||m.mac||m.serial||'',m.tecnico||'',m.destino||'',m.cliente||'',m.os||'',m.obs||m.motivo||'']);return {title:'Movimentações',cols:['Data','Tipo','Item','Técnico','Destino','Cliente','OS','Obs'],raw}}
function repHist(f){if(!f.q)return {title:'Histórico do item',cols:['Aviso'],raw:[['Digite MAC, SN, código ou patrimônio na busca antes de gerar.']]};let raw=MOVS.filter(m=>inDate(md(m),f)&&NR([m.codigo,m.mac,m.serial,m.obs,m.motivo].join(' ')).includes(f.q)).map(m=>[DBR(md(m)),m.tipo||'',m.codigo||'',m.mac||m.serial||'',m.tecnico||'',m.destino||'',m.status_final||m.statusFinal||'',m.obs||m.motivo||'']);return {title:'Histórico do item',cols:['Data','Tipo','Código','MAC/SN','Técnico','Destino','Status','Obs'],raw}}
function repClose(f){let r=repDaily(f),o={};r.raw.forEach(x=>o[x[0]]=x[1]);r.title='Fechamento WhatsApp';r.whats='SAIDA/FECHAMENTO DO ESTOQUE\nPeríodo: '+f.period+'\n\nEntradas: '+(o.Entradas||0)+'\nSaídas para técnico: '+(o.Saídas||0)+'\nInstalações: '+(o.Instalações||0)+'\nRetornos/devoluções: '+(o.Retornos||0)+'\nBaixas/descarte: '+(o.Baixas||0)+'\nManutenção/teste: '+(o.Manutenção||0)+'\nMovimentações totais: '+(o.Movimentos||0);return r}
function repTech(f){let list=fe(eqs().filter(e=>tec(e)&&!/estoque|cliente|instalado|perdido|inutil/i.test(e.status||'')),f);let raw=list.map(e=>[tec(e)||'-',e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'',e.local||'',BR(e.custo)]);let total=list.reduce((s,e)=>s+Number(e.custo||0),0);return {title:'Estoque por técnico',cols:['Técnico','Código','Equipamento','MAC/SN','Status','Local','Valor'],raw,kpis:[['Equipamentos',list.length],['Valor',BR(total)],['Técnicos',[...new Set(list.map(tec).filter(Boolean))].length]]}}
function repCharge(f){let name=f.tec||[...new Set(eqs().map(tec).filter(Boolean))][0]||'';let list=eqs().filter(e=>tec(e)===name).filter(e=>!/estoque|cliente|instalado|perdido|inutil/i.test(e.status||''));let raw=list.map(e=>['Equipamento',e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'']);let msg='CONFERÊNCIA DE ESTOQUE\nTécnico: '+(name||'Não informado')+'\n\nEQUIPAMENTOS:\n'+(list.map(e=>'- '+(e.codigo||'')+' | '+nm(e)+' | MAC/SN: '+(e.mac||e.serial||'-')).join('\n')||'Sem equipamentos em posse.')+'\n\nFavor conferir e confirmar.';return {title:'Cobrança WhatsApp',cols:['Tipo','Código','Item','Identificação','Status'],raw,whats:msg,kpis:[['Equipamentos',list.length]]}}
function repMat(f){let raw=MATS.filter(m=>!f.q||NR([m.tipo,m.marca,m.modelo,m.categoria,m.tecnico,m.local].join(' ')).includes(f.q)).filter(m=>!f.tec||m.tecnico===f.tec).map(m=>[m.categoria||'',[(m.tipo||''),(m.marca||''),(m.modelo||'')].join(' ').trim(),m.local||'',m.tecnico||'-',m.quantidade||0,m.unidade_saida||'']);return {title:'Saldo de materiais',cols:['Categoria','Material','Local','Técnico','Qtd','Unidade'],raw}}
function repMin(f){let raw=mods().map(m=>{let saldo=MATS.filter(s=>s.tipo===m.tipo&&s.modelo===m.modelo&&!s.tecnico).reduce((a,b)=>a+Number(b.quantidade||0),0);let min=Number(m.minimo||m.estoque_minimo||0),ideal=Number(m.ideal||m.estoque_ideal||0);return [[m.tipo,m.marca,m.modelo].filter(Boolean).join(' '),saldo,min,ideal,Math.max(ideal-saldo,0),saldo<min?'Crítico':'OK']});return {title:'Estoque mínimo',cols:['Item','Atual','Mínimo','Ideal','Comprar','Status'],raw}}
function repInst(f){let list=fe(eqs().filter(e=>/cliente|instalado/i.test(e.status||'')),f);let raw=list.map(e=>[cli(e)||'-',nm(e),e.mac||'',e.serial||'',e.codigo||'',tec(e)||'-',os(e)||'']);return {title:'Instalados',cols:['Cliente','Equipamento','MAC','SN','Código','Técnico','OS'],raw,kpis:[['Instalados',list.length]]}}
function repRet(f){let raw=fm(f).filter(m=>/retorno|devolu/i.test(NR([m.tipo,m.motivo].join(' ')))).map(m=>[DBR(md(m)),m.cliente||'',m.codigo||'',m.mac||m.serial||'',m.destino||'',m.tecnico||'',m.obs||'']);return {title:'Retornos',cols:['Data','Cliente','Código','MAC/SN','Destino','Técnico','Obs'],raw}}
function repLoss(f){let list=fe(eqs().filter(e=>/baixa|descarte|perdido|inutil|quebrado/i.test([e.status,e.motivoAtual,e.motivo_atual,e.local].join(' '))),f);let raw=list.map(e=>[e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'',tec(e)||'-',cli(e)||'-',BR(e.custo)]);return {title:'Baixas/descarte',cols:['Código','Equipamento','MAC/SN','Status','Técnico','Cliente','Valor'],raw}}
function repIntel(f){let comTec=eqs().filter(e=>tec(e)).length,perdas=eqs().filter(e=>/perdido|inutil|descarte/i.test(e.status||'')),crit=MATS.filter(m=>!m.tecnico&&Number(m.quantidade||0)<=0);let raw=crit.map(m=>['Ruptura',[(m.tipo||''),(m.modelo||'')].join(' ')+' sem saldo central']).concat(perdas.slice(0,20).map(e=>['Perda',(e.codigo||'')+' '+nm(e)+' '+(e.status||'')]));return {title:'Inteligência',cols:['Risco','Descrição'],raw,kpis:[['Eqp com técnico',comTec],['Perdas/baixas',perdas.length],['Materiais críticos',crit.length]]}}
async function boot(){page();await loadExtra();fillFilters();blocks()}
document.addEventListener('DOMContentLoaded',()=>{[300,1200,3000,7000,12000,18000].forEach(t=>setTimeout(()=>boot().catch(()=>{}),t))});
window.relatoriosCoreBoot=boot;
})();