(function(){
var MOVS=[],MATS=[];
function el(id){return document.getElementById(id)}
function h(v){try{return esc(v==null?'':v)}catch(e){return String(v==null?'':v)}}
function nrm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function iso(v){if(!v)return '';var s=String(v);if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);var d=new Date(s);return isNaN(d)?'':d.toISOString().slice(0,10)}
function brd(v){var s=iso(v);if(!s)return '';var p=s.split('-');return p[2]+'/'+p[1]+'/'+p[0]}
function money(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function eqs(){return (window.D&&D.equipamentos)||[]}
function mods(){return (window.D&&D.modelos)||[]}
function tecs(){return (window.D&&D.tecnicos)||[]}
function tec(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function cli(e){return e.clienteAtual||e.cliente_atual||e.cliente||''}
function os(e){return e.osAtual||e.os_atual||e.os||''}
function nm(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function md(m){return iso(m.data||m.created_at||m.createdAt)}
function mt(m){return [m.tipo,m.codigo,m.mac,m.serial,m.tecnico,m.destino,m.cliente,m.os,m.motivo,m.obs,m.statusFinal,m.status_final].join(' ')}
async function loadExtra(){try{MOVS=await loadTable('movimentos','data',false)}catch(e){MOVS=(D&&(D.movimentos||D.movs))||[]}try{MATS=await loadTable('materiais_saldos','tipo',true)}catch(e){MATS=[]}}
function css(){if(el('relCoreCss'))return;var s=document.createElement('style');s.id='relCoreCss';s.textContent='.relHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.relFilter{display:grid;grid-template-columns:1.2fr .7fr .7fr .7fr .8fr .8fr;gap:10px}.relFilter label{font-size:12px;font-weight:900;color:#64748b}.relBlocks{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.relBlock{border:1px solid #e5e7eb;border-radius:18px;padding:16px;background:white;box-shadow:0 10px 28px #0f172a12}.relBtns{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.relBtns button{text-align:left;min-height:44px}.relKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0}.relKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.relKpis b{display:block;font-size:24px}.relActions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.relPrintHead{display:none}@media(max-width:1000px){.relFilter,.relBlocks,.relKpis,.relBtns{grid-template-columns:1fr}}@media print{body *{visibility:hidden!important}#relResultado,#relResultado *{visibility:visible!important}#relResultado{position:absolute;left:0;top:0;width:100%;padding:20px;background:white}.relActions,.pgTblCtl,.relNoPrint{display:none!important}.relPrintHead{display:block!important}.tbl table tbody tr{display:table-row!important}}';document.head.appendChild(s)}
function nav(){var side=document.querySelector('.side');if(!side)return;var b=null;document.querySelectorAll('.nav').forEach(function(x){var t=(x.textContent||'').toLowerCase();if(t.indexOf('relatório')>=0||t.indexOf('relatorio')>=0)b=x});if(b){b.textContent='Relatórios';b.dataset.p='relatorios'}else{var r=document.querySelector('[data-p="historico"]')||document.querySelector('[data-p="cadastros"]')||side.lastElementChild;r.insertAdjacentHTML('beforebegin','<button class="nav" data-p="relatorios">Relatórios</button>')}document.querySelectorAll('.nav').forEach(function(x){x.onclick=function(){if(typeof pg==='function')pg(x.dataset.p)}})}
function page(){css();nav();var main=document.querySelector('.main');if(!main)return;var sec=el('p-relatorios');if(!sec){var ref=el('p-historico')||el('p-cadastros')||main.lastElementChild;ref.insertAdjacentHTML('beforebegin','<section id="p-relatorios" class="page"></section>');sec=el('p-relatorios')}if(!sec.dataset.core||sec.innerText.indexOf('Relatórios gerenciais')>=0){sec.dataset.core='1';sec.innerHTML='<div class="relHero"><h2>Relatórios</h2><p>Módulo central com filtros, PDF, CSV e WhatsApp.</p></div><div class="card relNoPrint"><h2>Filtros globais</h2><div class="relFilter"><div><label>Busca</label><input id="relQ" placeholder="MAC, SN, código, técnico, cliente, material"></div><div><label>Período</label><select id="relPreset"><option value="today">Hoje</option><option value="yesterday">Ontem</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="month">Este mês</option><option value="all">Todos</option><option value="custom">Personalizado</option></select></div><div><label>Data inicial</label><input id="relStart" type="date"></div><div><label>Data final</label><input id="relEnd" type="date"></div><div><label>Técnico</label><select id="relTec"></select></div><div><label>Status</label><select id="relStatus"></select></div></div><p class="small">Relatórios de movimentação usam datas; relatórios de posição atual mostram o estoque atual.</p></div><div id="relBlocks" class="relBlocks relNoPrint"></div><div class="card" id="relResultado"><div class="relPrintHead"><h2>LIKE internet - Relatório de Estoque</h2><p id="relPrintInfo"></p></div><h2>Resultado</h2><div id="relOut" class="msg">Selecione um relatório acima.</div></div>'}filtersFill();blocks();bind()}
function preset(force){var p=el('relPreset')?el('relPreset').value:'today',a=el('relStart'),b=el('relEnd');if(!a||!b)return;if(p==='custom'&&!force)return;var x=new Date(),y=new Date();if(p==='all'){a.value='';b.value='';return}if(p==='yesterday'){x.setDate(x.getDate()-1);y.setDate(y.getDate()-1)}if(p==='7')x.setDate(x.getDate()-6);if(p==='30')x.setDate(x.getDate()-29);if(p==='month')x=new Date(y.getFullYear(),y.getMonth(),1);a.value=x.toISOString().slice(0,10);b.value=y.toISOString().slice(0,10)}
function filtersFill(){var s=el('relTec');if(s){var old=s.value;var arr=[].concat(tecs().map(function(t){return t.nome}),eqs().map(tec),MATS.map(function(m){return m.tecnico})).filter(Boolean);arr=Array.from(new Set(arr)).sort();s.innerHTML='<option value="">Todos</option>'+arr.map(function(x){return '<option>'+h(x)+'</option>'}).join('');if(arr.indexOf(old)>=0)s.value=old}var st=el('relStatus');if(st){var o=st.value;var ss=Array.from(new Set(eqs().map(function(e){return e.status}).filter(Boolean))).sort();st.innerHTML='<option value="">Todos</option>'+ss.map(function(x){return '<option>'+h(x)+'</option>'}).join('');if(ss.indexOf(o)>=0)st.value=o}preset(false)}
var R={daily:['1. Operação diária','Resumo operacional',true,repDaily],mov:['1. Operação diária','Movimentações',true,repMov],hist:['1. Operação diária','Histórico do item',true,repHist],close:['1. Operação diária','Fechamento WhatsApp',true,repClose],tech:['2. Técnicos','Estoque por técnico',false,repTech],charge:['2. Técnicos','Cobrança WhatsApp',false,repCharge],mat:['3. Materiais','Saldo de materiais',false,repMat],min:['3. Materiais','Estoque mínimo',false,repMin],inst:['4. Clientes / campo','Instalados',false,repInst],ret:['4. Clientes / campo','Retornos',true,repRet],loss:['5. Auditoria e inteligência','Baixas/descarte',false,repLoss],intel:['5. Auditoria e inteligência','Inteligência',false,repIntel]};
function blocks(){var box=el('relBlocks');if(!box)return;var g={};Object.keys(R).forEach(function(k){var r=R[k];(g[r[0]]||(g[r[0]]=[])).push([k,r])});box.innerHTML=Object.keys(g).map(function(t){return '<div class="relBlock"><h3>'+h(t)+'</h3><div class="relBtns">'+g[t].map(function(x){return '<button onclick="runReportCore(\''+x[0]+'\')"><b>'+h(x[1][1])+'</b><br><small>'+(x[1][2]?'usa período':'posição atual')+'</small></button>'}).join('')+'</div></div>'}).join('')}
function bind(){if(el('relPreset')&&!el('relPreset').dataset.b){el('relPreset').dataset.b='1';el('relPreset').onchange=function(){preset(true)}}}
function f(){return {q:nrm(el('relQ')&&el('relQ').value),start:el('relStart')?el('relStart').value:'',end:el('relEnd')?el('relEnd').value:'',tec:el('relTec')?el('relTec').value:'',status:el('relStatus')?el('relStatus').value:'',period:period()}}
function period(){var a=el('relStart')&&el('relStart').value,b=el('relEnd')&&el('relEnd').value;if(!a&&!b)return 'Todos';return (a?brd(a):'início')+' até '+(b?brd(b):'hoje')}
function inDate(v,F){var d=iso(v);if(!F.start&&!F.end)return true;if(!d)return false;if(F.start&&d<F.start)return false;if(F.end&&d>F.end)return false;return true}
function movs(F){return MOVS.filter(function(m){return inDate(md(m),F)}).filter(function(m){return !F.q||nrm(mt(m)).indexOf(F.q)>=0}).filter(function(m){return !F.tec||m.tecnico===F.tec})}
function feq(list,F){return list.filter(function(e){return !F.q||nrm([e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tec(e),cli(e),os(e)].join(' ')).indexOf(F.q)>=0}).filter(function(e){return !F.tec||tec(e)===F.tec}).filter(function(e){return !F.status||e.status===F.status})}
function row(a){return '<tr>'+a.map(function(c){return '<td>'+h(c)+'</td>'}).join('')+'</tr>'}
function tbl(cols,rows){return '<div class="tbl"><table><thead><tr>'+cols.map(function(c){return '<th>'+h(c)+'</th>'}).join('')+'</tr></thead><tbody>'+(rows.length?rows.map(row).join(''):'<tr><td colspan="'+cols.length+'">Sem registros para os filtros aplicados.</td></tr>')+'</tbody></table></div>'}
function kp(items){return '<div class="relKpis">'+items.map(function(i){return '<div><small>'+h(i[0])+'</small><b>'+h(i[1])+'</b></div>'}).join('')+'</div>'}
function out(rep,F){var o=el('relOut');if(!o)return;if(el('relPrintInfo'))el('relPrintInfo').textContent=rep.title+' • Período: '+F.period+' • Gerado em '+new Date().toLocaleString('pt-BR');window.__relCore=rep;o.className='';o.innerHTML='<h2>'+h(rep.title)+'</h2><p class="small"><b>Período:</b> '+h(F.period)+'</p><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button><button class="warn" onclick="relCsvCore()">Exportar CSV</button>'+(rep.whats?'<button class="ok" onclick="relWhatsCore()">Copiar WhatsApp</button>':'')+'</div>'+(rep.kpis?kp(rep.kpis):'')+tbl(rep.cols,rep.raw);try{if(window.paginarTabelas)window.paginarTabelas()}catch(e){}}
window.runReportCore=async function(id){try{page();await loadExtra();filtersFill();var F=f(),r=R[id];if(!r)throw Error('Relatório não encontrado');out(await r[3](F),F)}catch(e){if(el('relOut')){el('relOut').className='msg bad';el('relOut').textContent='Erro ao gerar relatório: '+e.message}}}
window.relCsvCore=function(){var r=window.__relCore;if(!r)return alert('Gere um relatório primeiro.');var csv=[r.cols.join(';')].concat(r.raw.map(function(a){return a.map(function(x){return String(x==null?'':x).replace(/;/g,',')}).join(';')})).join('\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.title||'relatorio').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.csv';a.click();URL.revokeObjectURL(a.href)}
window.relWhatsCore=function(){var r=window.__relCore;if(!r||!r.whats)return alert('Este relatório não tem mensagem pronta.');navigator.clipboard.writeText(r.whats).then(function(){alert('Mensagem copiada.')})}
function repDaily(F){var m=movs(F),c=function(re){return m.filter(function(x){return re.test(nrm([x.tipo,x.motivo,x.statusFinal,x.status_final].join(' ')))}).length};var raw=[['Entradas',c(/entrada/)],['Saídas',c(/saida|saída/)],['Instalações',c(/instala/)],['Retornos',c(/retorno|devolu/)],['Baixas',c(/baixa|descarte|inutil|perdido/)],['Manutenção',c(/manut|teste/)],['Movimentos',m.length]];return {title:'Resumo operacional',cols:['Indicador','Quantidade'],raw:raw,kpis:raw}}
function repMov(F){var raw=movs(F).map(function(m){return [brd(md(m)),m.tipo||'',m.codigo||m.mac||m.serial||'',m.tecnico||'',m.destino||'',m.cliente||'',m.os||'',m.obs||m.motivo||'']});return {title:'Movimentações',cols:['Data','Tipo','Item','Técnico','Destino','Cliente','OS','Obs'],raw:raw}}
function repHist(F){if(!F.q)return {title:'Histórico do item',cols:['Aviso'],raw:[['Digite MAC, SN, código ou patrimônio na busca antes de gerar.']]};var raw=MOVS.filter(function(m){return inDate(md(m),F)&&nrm([m.codigo,m.mac,m.serial,m.obs,m.motivo].join(' ')).indexOf(F.q)>=0}).map(function(m){return [brd(md(m)),m.tipo||'',m.codigo||'',m.mac||m.serial||'',m.tecnico||'',m.destino||'',m.statusFinal||m.status_final||'',m.obs||m.motivo||'']});return {title:'Histórico do item',cols:['Data','Tipo','Código','MAC/SN','Técnico','Destino','Status','Obs'],raw:raw}}
function repClose(F){var r=repDaily(F),o={};r.raw.forEach(function(x){o[x[0]]=x[1]});r.title='Fechamento WhatsApp';r.whats='📦 FECHAMENTO DO ESTOQUE\nPeríodo: '+F.period+'\n\nEntradas: '+(o.Entradas||0)+'\nSaídas para técnico: '+(o.Saídas||0)+'\nInstalações: '+(o.Instalações||0)+'\nRetornos/devoluções: '+(o.Retornos||0)+'\nBaixas/descarte: '+(o.Baixas||0)+'\nManutenção/teste: '+(o.Manutenção||0)+'\nMovimentações totais: '+(o.Movimentos||0);return r}
function repTech(F){var list=feq(eqs().filter(function(e){return tec(e)&&!/estoque|cliente|instalado|perdido|inutil/i.test(e.status||'')}),F);var raw=list.map(function(e){return [tec(e),e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'',e.local||'',money(e.custo)]});return {title:'Estoque por técnico',cols:['Técnico','Código','Equipamento','MAC/SN','Status','Local','Valor'],raw:raw,kpis:[['Equipamentos',list.length],['Valor',money(list.reduce(function(s,e){return s+Number(e.custo||0)},0))]]}}
function repCharge(F){var name=F.tec||Array.from(new Set(eqs().map(tec).filter(Boolean)))[0]||'';var eq=eqs().filter(function(e){return tec(e)===name});var mats=MATS.filter(function(m){return m.tecnico===name&&Number(m.quantidade||0)>0});var raw=eq.map(function(e){return ['Equipamento',e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'']}).concat(mats.map(function(m){return ['Material','',(m.tipo||'')+' '+(m.modelo||''),String(m.quantidade||0)+' '+(m.unidade_saida||''),m.local||'']}));var msg='📋 CONFERÊNCIA DE ESTOQUE\nTécnico: '+(name||'Não informado')+'\n\nEQUIPAMENTOS:\n'+(eq.map(function(e){return '- '+(e.codigo||'')+' | '+nm(e)+' | MAC/SN: '+(e.mac||e.serial||'-')}).join('\n')||'Sem equipamentos em posse.')+'\n\nMATERIAIS:\n'+(mats.map(function(m){return '- '+(m.tipo||'')+' '+(m.modelo||'')+': '+m.quantidade+' '+(m.unidade_saida||'')}).join('\n')||'Sem materiais em posse.')+'\n\nFavor conferir e confirmar.';return {title:'Cobrança WhatsApp',cols:['Tipo','Código','Item','Identificação/Qtd','Status/Local'],raw:raw,whats:msg}}
function repMat(F){var raw=MATS.filter(function(m){return !F.q||nrm([m.tipo,m.marca,m.modelo,m.categoria,m.tecnico,m.local].join(' ')).indexOf(F.q)>=0}).filter(function(m){return !F.tec||m.tecnico===F.tec}).map(function(m){return [m.categoria||'',(m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||''),m.local||'',m.tecnico||'-',m.quantidade||0,m.unidade_saida||'']});return {title:'Saldo de materiais',cols:['Categoria','Material','Local','Técnico','Qtd','Unidade'],raw:raw}}
function repMin(F){var raw=mods().map(function(m){var saldo=MATS.filter(function(s){return s.tipo===m.tipo&&s.modelo===m.modelo&&!s.tecnico}).reduce(function(a,b){return a+Number(b.quantidade||0)},0);var min=Number(m.minimo||m.estoque_minimo||0),ideal=Number(m.ideal||m.estoque_ideal||0);return [(m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||''),saldo,min,ideal,Math.max(ideal-saldo,0),saldo<min?'Crítico':'OK']});return {title:'Estoque mínimo',cols:['Item','Atual','Mínimo','Ideal','Comprar','Status'],raw:raw}}
function repInst(F){var list=feq(eqs().filter(function(e){return /cliente|instalado/i.test(e.status||'')}),F);var raw=list.map(function(e){return [cli(e)||'-',nm(e),e.mac||'',e.serial||'',e.codigo||'',tec(e)||'-',os(e)||'']});return {title:'Instalados',cols:['Cliente','Equipamento','MAC','SN','Código','Técnico','OS'],raw:raw,kpis:[['Instalados',list.length]]}}
function repRet(F){var raw=movs(F).filter(function(m){return /retorno|devolu/i.test(nrm([m.tipo,m.motivo].join(' ')))}).map(function(m){return [brd(md(m)),m.cliente||'',m.codigo||'',m.mac||m.serial||'',m.destino||'',m.tecnico||'',m.obs||'']});return {title:'Retornos',cols:['Data','Cliente','Código','MAC/SN','Destino','Técnico','Obs'],raw:raw}}
function repLoss(F){var list=feq(eqs().filter(function(e){return /baixa|descarte|perdido|inutil|quebrado/i.test([e.status,e.motivoAtual,e.motivo_atual,e.local].join(' '))}),F);var raw=list.map(function(e){return [e.codigo||'',nm(e),e.mac||e.serial||'',e.status||'',tec(e)||'-',cli(e)||'-',money(e.custo)]});return {title:'Baixas/descarte',cols:['Código','Equipamento','MAC/SN','Status','Técnico','Cliente','Valor'],raw:raw}}
function repIntel(F){var comTec=eqs().filter(function(e){return tec(e)}).length,perdas=eqs().filter(function(e){return /perdido|inutil|descarte/i.test(e.status||'')}),crit=MATS.filter(function(m){return !m.tecnico&&Number(m.quantidade||0)<=0});var raw=crit.map(function(m){return ['Ruptura',(m.tipo||'')+' '+(m.modelo||'')+' sem saldo central']}).concat(perdas.slice(0,20).map(function(e){return ['Perda',(e.codigo||'')+' '+nm(e)+' '+(e.status||'')]}));return {title:'Inteligência',cols:['Risco','Descrição'],raw:raw,kpis:[['Eqp com técnico',comTec],['Perdas/baixas',perdas.length],['Materiais críticos',crit.length]]}}
function boot(){page();loadExtra().then(function(){filtersFill();blocks()});nav()}
document.addEventListener('DOMContentLoaded',function(){[300,1200,3000,7000,12000,18000].forEach(function(t){setTimeout(boot,t)})});
window.relatoriosCoreBoot=boot;
})();