(function(){
function E(id){return document.getElementById(id)}
function X(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function brMoney(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function today(){return new Date().toISOString().slice(0,10)}
function dval(x){return x?String(x).slice(0,10):''}
function dataMov(m){return dval(m.data||m.created_at||m.createdAt||m.dt||m.date)}
function parseDate(v){var s=dval(v);if(!s)return null;var d=new Date(s+'T00:00:00');return isNaN(d)?null:d}
function inRangeDate(v){var ini=E('relDataInicio')&&E('relDataInicio').value;var fim=E('relDataFim')&&E('relDataFim').value;var d=parseDate(v);if(!ini&&!fim)return true;if(!d)return false;if(ini&&d<parseDate(ini))return false;if(fim&&d>parseDate(fim))return false;return true}
function periodoTxt(){var ini=E('relDataInicio')&&E('relDataInicio').value;var fim=E('relDataFim')&&E('relDataFim').value;if(ini||fim)return (ini||'início')+' até '+(fim||'hoje');var p=E('relPeriodo')&&E('relPeriodo').value;if(p==='hoje')return 'Hoje';if(p==='7')return 'Últimos 7 dias';if(p==='30')return 'Últimos 30 dias';return 'Todos'}
function applyPreset(){var p=E('relPeriodo')&&E('relPeriodo').value;if(!E('relDataInicio')||!E('relDataFim'))return;if(p==='todos'){E('relDataInicio').value='';E('relDataFim').value='';return}var end=new Date();var start=new Date();if(p==='hoje'){/* same day */}else{start.setDate(start.getDate()-Number(p||0))}E('relDataInicio').value=start.toISOString().slice(0,10);E('relDataFim').value=end.toISOString().slice(0,10)}
function ensureDateParams(){
 var top=E('relBusca')&&E('relBusca').parentElement;if(!top)return;
 if(!E('relDataInicio')){
  var html='<input id="relDataInicio" type="date" title="Data inicial"><input id="relDataFim" type="date" title="Data final"><div id="relPeriodoInfo" class="msg" style="margin-top:0">Período: '+X(periodoTxt())+'</div>';
  if(E('relPeriodo'))E('relPeriodo').insertAdjacentHTML('afterend',html);else top.insertAdjacentHTML('beforeend',html);
 }
 if(E('relPeriodo')&&!E('relPeriodo').dataset.dtBound){E('relPeriodo').dataset.dtBound=1;E('relPeriodo').onchange=function(){applyPreset();updatePeriodoInfo()}}
 ['relDataInicio','relDataFim'].forEach(function(id){if(E(id)&&!E(id).dataset.dtBound){E(id).dataset.dtBound=1;E(id).onchange=updatePeriodoInfo;E(id).oninput=updatePeriodoInfo}});
 updatePeriodoInfo();
}
function updatePeriodoInfo(){if(E('relPeriodoInfo'))E('relPeriodoInfo').textContent='Período aplicado: '+periodoTxt()}
async function loadMovs(){try{if(typeof loadTable==='function')return await loadTable('movimentos','data',false)}catch(e){}return (D&& (D.movimentos||D.movs))||[]}
async function loadMats(){try{if(typeof loadTable==='function')return await loadTable('materiais_saldos','tipo',true)}catch(e){}return []}
function bySearch(arr,fn){var q=norm(E('relBusca')&&E('relBusca').value);if(!q)return arr;return arr.filter(function(x){return norm(fn(x)).includes(q)})}
function dateFilterMovs(movs){return bySearch(movs.filter(function(m){return inRangeDate(dataMov(m))}),function(m){return [m.tipo,m.codigo,m.mac,m.serial,m.tecnico,m.destino,m.cliente,m.os,m.motivo,m.obs,m.statusFinal,m.status_final].join(' ')})}
function setOut(titulo,html,zap){ensureDateParams();var out=E('relOut');if(!out)return;var dt=new Date().toLocaleString('pt-BR');if(E('relPrintInfo'))E('relPrintInfo').textContent=titulo+' • Período: '+periodoTxt()+' • Gerado em '+dt;out.className='';out.innerHTML='<h2>'+X(titulo)+'</h2><p class="small"><b>Período:</b> '+X(periodoTxt())+'</p><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button>'+(zap?'<button class="warn" onclick="relCopyMsg()">Copiar mensagem</button>':'')+'</div>'+html;window.__relMsg=zap||'';try{if(window.paginarTabelas)window.paginarTabelas()}catch(e){}}
function tbl(head,rows){return '<div class="tbl"><table><thead><tr>'+head.map(function(h){return '<th>'+X(h)+'</th>'}).join('')+'</tr></thead><tbody>'+(rows.length?rows.join(''):'<tr><td colspan="'+head.length+'">Sem registros no período informado.</td></tr>')+'</tbody></table></div>'}
function copyMsg(){var txt=window.__relMsg||'';if(!txt){alert('Este relatório não tem mensagem pronta.');return}navigator.clipboard.writeText(txt).then(function(){alert('Mensagem copiada.')})}
window.relCopyMsg=copyMsg;
window.relResumoDia=function(){loadMovs().then(function(all){ensureDateParams();var mov=dateFilterMovs(all);var c=function(re){return mov.filter(function(m){return re.test(norm([m.tipo,m.motivo,m.statusFinal,m.status_final].join(' ')))}).length};var cards=[['Entradas',c(/entrada/)],['Saídas',c(/saida|saída/)],['Instalações',c(/instala/)],['Retornos',c(/retorno|devolu/)],['Baixas',c(/baixa|descarte|inutil|perdido/)],['Manutenção',c(/manut|teste/)],['Movimentos',mov.length]];setOut('Resumo do período','<div class="relKpis">'+cards.map(function(x){return '<div><small>'+X(x[0])+'</small><b>'+x[1]+'</b></div>'}).join('')+'</div>')})};
window.relMovimentacoes=function(){loadMovs().then(function(all){var rows=dateFilterMovs(all).map(function(m){return '<tr><td>'+X(dataMov(m))+'</td><td>'+X(m.tipo||'')+'</td><td>'+X(m.codigo||m.mac||m.serial||'')+'</td><td>'+X(m.tecnico||'-')+'</td><td>'+X(m.destino||'-')+'</td><td>'+X(m.cliente||'-')+'</td><td>'+X(m.os||'-')+'</td><td>'+X(m.obs||m.motivo||'')+'</td></tr>'});setOut('Movimentações do período',tbl(['Data','Tipo','Item','Técnico','Destino','Cliente','OS','Obs'],rows))})};
window.relHistoricoItem=function(){loadMovs().then(function(all){var q=norm(E('relBusca')&&E('relBusca').value);if(!q){setOut('Histórico completo do item','<div class="msg bad">Digite MAC, SN, código ou patrimônio no campo de busca.</div>');return}var rows=all.filter(function(m){return inRangeDate(dataMov(m))&&norm([m.codigo,m.mac,m.serial,m.obs,m.motivo].join(' ')).includes(q)}).map(function(m){return '<tr><td>'+X(dataMov(m))+'</td><td>'+X(m.tipo||'')+'</td><td>'+X(m.codigo||'')+'</td><td>'+X(m.mac||m.serial||'')+'</td><td>'+X(m.tecnico||'')+'</td><td>'+X(m.destino||'')+'</td><td>'+X(m.statusFinal||m.status_final||'')+'</td><td>'+X(m.obs||m.motivo||'')+'</td></tr>'});setOut('Histórico completo do item',tbl(['Data','Tipo','Código','MAC/SN','Técnico','Destino','Status','Obs'],rows))})};
window.relFechamentoZap=function(){loadMovs().then(function(all){var mov=dateFilterMovs(all);var c=function(re){return mov.filter(function(m){return re.test(norm([m.tipo,m.motivo,m.statusFinal,m.status_final].join(' ')))}).length};var msg='📦 FECHAMENTO DO ESTOQUE\nPeríodo: '+periodoTxt()+'\n\nEntradas: '+c(/entrada/)+'\nSaídas para técnico: '+c(/saida|saída/)+'\nInstalações: '+c(/instala/)+'\nRetornos/devoluções: '+c(/retorno|devolu/)+'\nBaixas/descarte: '+c(/baixa|descarte|inutil|perdido/)+'\nManutenção/teste: '+c(/manut|teste/)+'\nMovimentações totais: '+mov.length+'\n\nObservação: conferir pendências por técnico e materiais consumidos.';setOut('Fechamento do período para WhatsApp','<pre style="white-space:pre-wrap">'+X(msg)+'</pre>',msg)})};
window.relMateriaisConsumidos=function(){loadMovs().then(function(all){var rows=dateFilterMovs(all).filter(function(m){return /material|consum|uso|baixa/i.test([m.tipo,m.motivo,m.obs].join(' '))}).map(function(m){return '<tr><td>'+X(dataMov(m))+'</td><td>'+X(m.tecnico||'')+'</td><td>'+X(m.codigo||m.motivo||'Material')+'</td><td>'+X(m.obs||'')+'</td></tr>'});setOut('Materiais consumidos',tbl(['Data','Técnico','Material','Observação'],rows))})};
window.relRetornosCliente=function(){loadMovs().then(function(all){var rows=dateFilterMovs(all).filter(function(m){return /retorno|devolu/i.test(norm([m.tipo,m.motivo].join(' ')))}).map(function(m){return '<tr><td>'+X(dataMov(m))+'</td><td>'+X(m.cliente||'')+'</td><td>'+X(m.codigo||'')+'</td><td>'+X(m.mac||m.serial||'')+'</td><td>'+X(m.destino||'')+'</td><td>'+X(m.tecnico||'')+'</td><td>'+X(m.obs||'')+'</td></tr>'});setOut('Retornos do cliente',tbl(['Data','Cliente','Código','MAC/SN','Destino','Técnico','Obs'],rows))})};
window.relEntradaNF=function(){loadMovs().then(function(all){var rows=dateFilterMovs(all).filter(function(m){return /entrada/i.test([m.tipo,m.motivo].join(' '))}).map(function(m){return '<tr><td>'+X(dataMov(m))+'</td><td>'+X(m.codigo||'')+'</td><td>'+X(m.mac||m.serial||'')+'</td><td>'+X(m.destino||'')+'</td><td>'+X(m.obs||'')+'</td></tr>'});setOut('Entrada por fornecedor / NF',tbl(['Data','Código','MAC/SN','Destino','Obs/NF/Fornecedor'],rows))})};
window.relSaldoMateriais=function(){loadMats().then(function(mat){var rows=bySearch(mat,function(m){return [m.tipo,m.marca,m.modelo,m.categoria,m.tecnico,m.local].join(' ')}).map(function(m){return '<tr><td>'+X(m.categoria)+'</td><td>'+X((m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||''))+'</td><td>'+X(m.local||'')+'</td><td>'+X(m.tecnico||'-')+'</td><td><b>'+X(m.quantidade||0)+'</b></td><td>'+X(m.unidade_saida||'')+'</td></tr>'});setOut('Saldo atual de materiais',tbl(['Categoria','Material','Local','Técnico','Qtd','Unidade'],rows))})};
function boot(){ensureDateParams();updatePeriodoInfo()}
document.addEventListener('DOMContentLoaded',function(){[500,1800,4500,9000,14000,20000].forEach(function(t){setTimeout(boot,t)})});
window.ensureRelatorioDatas=boot;
})();