(function(){
let matRel=[], movRel=[];
function E(id){return document.getElementById(id)}
function X(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function money(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function hojeISO(){return new Date().toISOString().slice(0,10)}
function dataBR(d){try{return new Date(d).toLocaleString('pt-BR')}catch(e){return String(d||'')}}
function tecEq(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function cliEq(e){return e.clienteAtual||e.cliente_atual||''}
function osEq(e){return e.osAtual||e.os_atual||''}
function nomeEq(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function isToday(v){let s=String(v||'');return s.slice(0,10)===hojeISO()||s.includes(new Date().toLocaleDateString('pt-BR'))}
async function loadRel(){try{matRel=await loadTable('materiais_saldos','tipo',true)}catch(e){matRel=[]}try{movRel=await loadTable('movimentos','data',false)}catch(e){movRel=D.movs||[]}}
function css(){if(E('relCss'))return;let s=document.createElement('style');s.id='relCss';s.textContent='.relHero{background:linear-gradient(135deg,#0d1b2e,#0f4c81);color:white;border-radius:22px;padding:20px;margin-bottom:14px}.relTop{display:grid;grid-template-columns:1.2fr .8fr .8fr;gap:10px}.relBlocks{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.relBlock{border:1px solid #e5e7eb;border-radius:18px;padding:16px;background:#fff;box-shadow:0 10px 28px #0f172a12}.relBlock h3{margin-top:0}.relBtns{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.relBtns button{text-align:left;min-height:44px}.relKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:10px 0}.relKpis div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:10px}.relPrintHead{display:none}.relActions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}@media(max-width:950px){.relTop,.relBlocks,.relKpis,.relBtns{grid-template-columns:1fr}}@media print{body *{visibility:hidden!important}#relResultado,#relResultado *{visibility:visible!important}#relResultado{position:absolute;left:0;top:0;width:100%;padding:20px;background:#fff}.relActions,.pgTblCtl{display:none!important}.relPrintHead{display:block!important}.tbl table tbody tr{display:table-row!important}}';document.head.appendChild(s)}
function ensurePage(){css();let side=document.querySelector('.side');if(side&&!document.querySelector('[data-p="relatorios"]')){let ref=document.querySelector('[data-p="historico"]')||side.lastElementChild;ref.insertAdjacentHTML('beforebegin','<button class="nav" data-p="relatorios">Relatórios</button>')}let main=document.querySelector('.main');if(main&&!E('p-relatorios')){let ref=E('p-historico')||E('p-dash');let html='<section id="p-relatorios" class="page"><div class="relHero"><h2>Relatórios</h2><p>Central em 5 blocos: operacional, gerencial e inteligência.</p></div><div class="card"><div class="relTop"><input id="relBusca" placeholder="Buscar em relatórios: MAC, SN, técnico, cliente, material"><select id="relPeriodo"><option value="hoje">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="todos">Todos</option></select><button id="relLimpar" class="warn">Limpar resultado</button></div></div><div class="relBlocks" id="relBlocks"></div><div class="card" id="relResultado"><div class="relPrintHead"><h2>LIKE internet - Relatório de Estoque</h2><p id="relPrintInfo"></p></div><h2>Resultado</h2><div id="relOut" class="msg">Selecione um relatório acima.</div></div></section>';if(ref)ref.insertAdjacentHTML('beforebegin',html);else main.insertAdjacentHTML('beforeend',html)}bindNav();renderBlocks();}
function bindNav(){document.querySelectorAll('.nav').forEach(b=>{if(b.dataset.p==='relatorios')b.onclick=()=>pg('relatorios')});if(E('relLimpar')&&!E('relLimpar').dataset.b){E('relLimpar').dataset.b=1;E('relLimpar').onclick=()=>{E('relOut').innerHTML='Selecione um relatório acima.';E('relOut').className='msg'}}}
function renderBlocks(){let box=E('relBlocks');if(!box||box.dataset.done)return;box.dataset.done=1;let blocks=[['1. Operação diária','Operacional','Resumo do dia, movimentações, histórico do item e fechamento.',[['Resumo do dia','relResumoDia()'],['Movimentações','relMovimentacoes()'],['Histórico do item','relHistoricoItem()'],['Fechamento WhatsApp','relFechamentoZap()']]],['2. Técnicos','Operacional + Gerencial','Posse, pendências, ranking e cobrança dos técnicos.',[['Estoque por técnico','relEstoqueTecnico()'],['Pendências','relPendenciasTecnico()'],['Ranking de posse','relRankingTecnico()'],['Cobrança WhatsApp','relCobrancaTecnico()']]],['3. Materiais','Operacional + Gerencial','Saldo, consumo, materiais por técnico e sugestão de compra.',[['Saldo de materiais','relSaldoMateriais()'],['Materiais consumidos','relMateriaisConsumidos()'],['Por técnico','relMateriaisTecnico()'],['Estoque mínimo','relEstoqueMinimo()']]],['4. Clientes / campo','Operacional + Gerencial','Equipamentos instalados, retornos e patrimônio em campo.',[['Instalados','relInstalados()'],['Por cliente','relPorCliente()'],['Retornos','relRetornosCliente()'],['Patrimônio em campo','relPatrimonioCampo()']]],['5. Auditoria, compras e inteligência','Auditoria + Gerencial + Inteligência','Baixas, manutenção, perdas, compras e riscos.',[['Baixas/descarte','relBaixas()'],['Manutenção/parados','relManutParados()'],['Entrada por NF','relEntradaNF()'],['Inteligência','relInteligencia()']]]];box.innerHTML=blocks.map(b=>'<div class="relBlock"><h3>'+b[0]+'</h3><p><span class="status ok">'+b[1]+'</span></p><p class="small">'+b[2]+'</p><div class="relBtns">'+b[3].map(x=>'<button onclick="'+x[1]+'">'+x[0]+'</button>').join('')+'</div></div>').join('')}
function filtroPeriodo(arr, campo){let p=(E('relPeriodo')&&E('relPeriodo').value)||'hoje';if(p==='todos')return arr;let dias=p==='hoje'?0:Number(p);let lim=new Date();lim.setDate(lim.getDate()-dias);return arr.filter(x=>{let d=x[campo]||x.data||x.created_at;if(!d)return p==='todos';if(p==='hoje')return isToday(d);return new Date(d)>=lim})}
function filtroBusca(arr, fn){let q=norm(E('relBusca')&&E('relBusca').value);if(!q)return arr;return arr.filter(x=>norm(fn(x)).includes(q))}
function setOut(titulo, html, zap){let out=E('relOut');if(!out)return;let dt=new Date().toLocaleString('pt-BR');E('relPrintInfo').textContent=titulo+' • Gerado em '+dt;out.className='';out.innerHTML='<h2>'+X(titulo)+'</h2><div class="relActions"><button class="pri" onclick="window.print()">Imprimir / PDF</button>'+(zap?'<button class="warn" onclick="relCopyMsg()">Copiar mensagem</button>':'')+'</div>'+html;window.__relMsg=zap||'';try{if(window.paginarTabelas)window.paginarTabelas()}catch(e){}}
window.relCopyMsg=function(){let txt=window.__relMsg||'';if(!txt){alert('Este relatório não tem mensagem pronta.');return}navigator.clipboard.writeText(txt).then(()=>alert('Mensagem copiada.'))}
function tbl(head, rows){return '<div class="tbl"><table><thead><tr>'+head.map(h=>'<th>'+X(h)+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.join(''):'<tr><td colspan="'+head.length+'">Sem registros.</td></tr>')+'</tbody></table></div>'}
function movimentos(){return filtroBusca(filtroPeriodo(movRel.length?movRel:(D.movs||[]),'data'),m=>[m.tipo,m.codigo,m.mac,m.serial,m.tecnico,m.destino,m.cliente,m.os,m.motivo,m.obs,m.statusFinal,m.status_final].join(' '))}
window.relResumoDia=function(){loadRel().then(()=>{let mov=movimentos();let c=re=>mov.filter(m=>re.test(norm([m.tipo,m.motivo,m.statusFinal,m.status_final].join(' ')))).length;let cards=[['Entradas',c(/entrada/)],['Saídas',c(/saida|saída/)],['Instalações',c(/instala/)],['Retornos',c(/retorno|devolu/)],['Baixas',c(/baixa|descarte|inutil|perdido/)],['Manutenção',c(/manut|teste/)],['Movimentos',mov.length],['Materiais c/ técnico',matRel.filter(m=>m.tecnico&&Number(m.quantidade||0)>0).length]];setOut('Resumo do dia','<div class="relKpis">'+cards.map(x=>'<div><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('')+'</div>')})}
window.relMovimentacoes=function(){loadRel().then(()=>{let rows=movimentos().map(m=>'<tr><td>'+X(dataBR(m.data||m.created_at))+'</td><td>'+X(m.tipo||'')+'</td><td>'+X(m.codigo||m.mac||m.serial||'')+'</td><td>'+X(m.tecnico||'-')+'</td><td>'+X(m.destino||'-')+'</td><td>'+X(m.cliente||'-')+'</td><td>'+X(m.os||'-')+'</td><td>'+X(m.obs||m.motivo||'')+'</td></tr>');setOut('Movimentações do período',tbl(['Data','Tipo','Item','Técnico','Destino','Cliente','OS','Obs'],rows))})}
window.relHistoricoItem=function(){loadRel().then(()=>{let q=norm(E('relBusca')&&E('relBusca').value);if(!q){setOut('Histórico completo do item','<div class="msg bad">Digite MAC, SN, código ou patrimônio no campo de busca.</div>');return}let rows=(movRel.length?movRel:(D.movs||[])).filter(m=>norm([m.codigo,m.mac,m.serial,m.obs,m.motivo].join(' ')).includes(q)).map(m=>'<tr><td>'+X(dataBR(m.data||m.created_at))+'</td><td>'+X(m.tipo||'')+'</td><td>'+X(m.codigo||'')+'</td><td>'+X(m.mac||m.serial||'')+'</td><td>'+X(m.tecnico||'')+'</td><td>'+X(m.destino||'')+'</td><td>'+X(m.statusFinal||m.status_final||'')+'</td><td>'+X(m.obs||m.motivo||'')+'</td></tr>');setOut('Histórico completo do item',tbl(['Data','Tipo','Código','MAC/SN','Técnico','Destino','Status','Obs'],rows))})}
window.relFechamentoZap=function(){loadRel().then(()=>{let mov=movimentos();let c=re=>mov.filter(m=>re.test(norm([m.tipo,m.motivo,m.statusFinal,m.status_final].join(' ')))).length;let msg='📦 FECHAMENTO DO ESTOQUE\nData: '+new Date().toLocaleDateString('pt-BR')+'\n\nEntradas: '+c(/entrada/)+'\nSaídas para técnico: '+c(/saida|saída/)+'\nInstalações: '+c(/instala/)+'\nRetornos/devoluções: '+c(/retorno|devolu/)+'\nBaixas/descarte: '+c(/baixa|descarte|inutil|perdido/)+'\nManutenção/teste: '+c(/manut|teste/)+'\n\nObservação: conferir pendências por técnico e materiais consumidos.';setOut('Fechamento diário para WhatsApp','<pre style="white-space:pre-wrap">'+X(msg)+'</pre>',msg)})}
window.relEstoqueTecnico=function(){loadRel().then(()=>{let nomes=[...new Set([...(D.tecnicos||[]).map(t=>t.nome),...(D.equipamentos||[]).map(tecEq),...matRel.map(m=>m.tecnico)].filter(Boolean))].sort();let rows=[];nomes.forEach(n=>{let eq=(D.equipamentos||[]).filter(e=>tecEq(e)===n&&!/estoque|cliente|instalado|perdido|inutil/i.test(e.status||''));let mats=matRel.filter(m=>m.tecnico===n&&Number(m.quantidade||0)>0);rows.push('<tr><td><b>'+X(n)+'</b></td><td>'+eq.length+'</td><td>'+mats.length+'</td><td>'+money(eq.reduce((s,e)=>s+Number(e.custo||0),0))+'</td><td>'+X(mats.map(m=>(m.tipo||'')+' '+(m.modelo||'')+': '+m.quantidade+' '+(m.unidade_saida||'')).join(' | '))+'</td></tr>')});setOut('Estoque por técnico completo',tbl(['Técnico','Equipamentos','Materiais','Valor patrimônio','Materiais em posse'],rows))})}
window.relPendenciasTecnico=function(){loadRel().then(()=>{let rows=(D.equipamentos||[]).filter(e=>tecEq(e)&&!/instalado|cliente|perdido|inutil/i.test(e.status||'')).map(e=>'<tr><td>'+X(tecEq(e))+'</td><td>'+X(e.codigo)+'</td><td>'+X(nomeEq(e))+'</td><td>'+X(e.mac||e.serial||'')+'</td><td>'+X(e.status||'')+'</td><td>Conferir tempo em posse</td></tr>');setOut('Pendências por técnico',tbl(['Técnico','Código','Item','MAC/SN','Status','Pendência'],rows))})}
window.relRankingTecnico=function(){loadRel().then(()=>{let nomes=[...new Set([...(D.equipamentos||[]).map(tecEq),...matRel.map(m=>m.tecnico)].filter(Boolean))];let rows=nomes.map(n=>{let eq=(D.equipamentos||[]).filter(e=>tecEq(e)===n);let mats=matRel.filter(m=>m.tecnico===n&&Number(m.quantidade||0)>0);return {n,eq:eq.length,mat:mats.length,val:eq.reduce((s,e)=>s+Number(e.custo||0),0)}}).sort((a,b)=>(b.eq+b.mat)-(a.eq+a.mat)).map((x,i)=>'<tr><td>'+(i+1)+'</td><td>'+X(x.n)+'</td><td>'+x.eq+'</td><td>'+x.mat+'</td><td>'+money(x.val)+'</td></tr>');setOut('Ranking de posse por técnico',tbl(['#','Técnico','Equipamentos','Materiais','Valor'],rows))})}
window.relCobrancaTecnico=function(){loadRel().then(()=>{let q=norm(E('relBusca')&&E('relBusca').value);let nomes=[...new Set([...(D.equipamentos||[]).map(tecEq),...matRel.map(m=>m.tecnico)].filter(Boolean))].filter(n=>!q||norm(n).includes(q));if(!nomes.length){setOut('Cobrança para WhatsApp','<div class="msg bad">Digite o nome do técnico no campo de busca.</div>');return}let n=nomes[0];let eq=(D.equipamentos||[]).filter(e=>tecEq(e)===n);let mats=matRel.filter(m=>m.tecnico===n&&Number(m.quantidade||0)>0);let msg='📋 CONFERÊNCIA DE ESTOQUE\nTécnico: '+n+'\n\nEQUIPAMENTOS:\n'+(eq.map(e=>'- '+(e.codigo||'')+' | '+nomeEq(e)+' | MAC/SN: '+(e.mac||e.serial||'-')).join('\n')||'Sem equipamentos em posse.')+'\n\nMATERIAIS:\n'+(mats.map(m=>'- '+(m.tipo||'')+' '+(m.modelo||'')+': '+m.quantidade+' '+(m.unidade_saida||'')).join('\n')||'Sem materiais em posse.')+'\n\nFavor conferir e confirmar.';setOut('Cobrança para WhatsApp','<pre style="white-space:pre-wrap">'+X(msg)+'</pre>',msg)})}
window.relSaldoMateriais=function(){loadRel().then(()=>{let rows=filtroBusca(matRel,m=>[m.tipo,m.marca,m.modelo,m.categoria,m.tecnico,m.local].join(' ')).map(m=>'<tr><td>'+X(m.categoria)+'</td><td>'+X((m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||''))+'</td><td>'+X(m.local||'')+'</td><td>'+X(m.tecnico||'-')+'</td><td><b>'+X(m.quantidade||0)+'</b></td><td>'+X(m.unidade_saida||'')+'</td></tr>');setOut('Saldo de materiais',tbl(['Categoria','Material','Local','Técnico','Qtd','Unidade'],rows))})}
window.relMateriaisConsumidos=function(){loadRel().then(()=>{let rows=movimentos().filter(m=>/material|consum|uso|baixa/i.test([m.tipo,m.motivo,m.obs].join(' '))).map(m=>'<tr><td>'+X(dataBR(m.data||m.created_at))+'</td><td>'+X(m.tecnico||'')+'</td><td>'+X(m.codigo||m.motivo||'Material')+'</td><td>'+X(m.obs||'')+'</td></tr>');setOut('Materiais consumidos',tbl(['Data','Técnico','Material','Observação'],rows))})}
window.relMateriaisTecnico=function(){window.relSaldoMateriais()}
window.relEstoqueMinimo=function(){loadRel().then(()=>{let rows=(D.modelos||[]).map(m=>{let saldo=matRel.filter(s=>s.tipo===m.tipo&&s.modelo===m.modelo&&!s.tecnico).reduce((a,b)=>a+Number(b.quantidade||0),0);let min=Number(m.minimo||m.estoque_minimo||0),ideal=Number(m.ideal||m.estoque_ideal||0);let compra=Math.max(ideal-saldo,0);return '<tr><td>'+X(m.tipo+' '+(m.marca||'')+' '+m.modelo)+'</td><td>'+saldo+'</td><td>'+min+'</td><td>'+ideal+'</td><td><b>'+compra+'</b></td></tr>'}).join('');setOut('Estoque mínimo / sugestão de compra',tbl(['Item','Atual','Mínimo','Ideal','Comprar sugerido'],[rows]))})}
window.relInstalados=function(){let rows=filtroBusca((D.equipamentos||[]).filter(e=>/cliente|instalado/i.test(e.status||'')),e=>[cliEq(e),tecEq(e),nomeEq(e),e.mac,e.serial].join(' ')).map(e=>'<tr><td>'+X(cliEq(e)||'-')+'</td><td>'+X(nomeEq(e))+'</td><td>'+X(e.mac||'')+'</td><td>'+X(e.serial||'')+'</td><td>'+X(e.codigo||'')+'</td><td>'+X(tecEq(e)||'-')+'</td></tr>');setOut('Equipamentos instalados em cliente',tbl(['Cliente','Equipamento','MAC','SN','Código','Técnico'],rows))}
window.relPorCliente=function(){window.relInstalados()}
window.relRetornosCliente=function(){loadRel().then(()=>{let rows=movimentos().filter(m=>/retorno|devolu/i.test(norm([m.tipo,m.motivo].join(' ')))).map(m=>'<tr><td>'+X(dataBR(m.data||m.created_at))+'</td><td>'+X(m.cliente||'')+'</td><td>'+X(m.codigo||'')+'</td><td>'+X(m.mac||m.serial||'')+'</td><td>'+X(m.destino||'')+'</td><td>'+X(m.tecnico||'')+'</td><td>'+X(m.obs||'')+'</td></tr>');setOut('Retornos do cliente',tbl(['Data','Cliente','Código','MAC/SN','Destino','Técnico','Obs'],rows))})}
window.relPatrimonioCampo=function(){let inst=(D.equipamentos||[]).filter(e=>/cliente|instalado/i.test(e.status||''));setOut('Patrimônio em campo','<div class="relKpis"><div><small>Instalados</small><b>'+inst.length+'</b></div><div><small>Valor estimado</small><b>'+money(inst.reduce((s,e)=>s+Number(e.custo||0),0))+'</b></div><div><small>Clientes</small><b>'+new Set(inst.map(cliEq).filter(Boolean)).size+'</b></div><div><small>Modelos</small><b>'+new Set(inst.map(e=>e.modelo).filter(Boolean)).size+'</b></div></div>')}
window.relBaixas=function(){loadRel().then(()=>{let rows=(D.equipamentos||[]).filter(e=>/baixa|descarte|perdido|inutil|quebrado/i.test([e.status,e.motivoAtual,e.motivo_atual,e.local].join(' '))).map(e=>'<tr><td>'+X(e.codigo)+'</td><td>'+X(nomeEq(e))+'</td><td>'+X(e.mac||e.serial||'')+'</td><td>'+X(e.status||'')+'</td><td>'+X(tecEq(e)||'-')+'</td><td>'+X(cliEq(e)||'-')+'</td><td>'+money(e.custo||0)+'</td></tr>');setOut('Baixas / descarte',tbl(['Código','Equipamento','MAC/SN','Status','Técnico','Cliente','Valor'],rows))})}
window.relManutParados=function(){let rows=(D.equipamentos||[]).filter(e=>/manut|teste|aguardando/i.test([e.status,e.local].join(' '))).map(e=>'<tr><td>'+X(e.codigo)+'</td><td>'+X(nomeEq(e))+'</td><td>'+X(e.mac||e.serial||'')+'</td><td>'+X(e.status||'')+'</td><td>'+X(e.local||'')+'</td><td>'+X(tecEq(e)||'-')+'</td></tr>');setOut('Manutenção / equipamentos parados',tbl(['Código','Equipamento','MAC/SN','Status','Local','Técnico'],rows))}
window.relEntradaNF=function(){loadRel().then(()=>{let rows=movimentos().filter(m=>/entrada/i.test(m.tipo||m.motivo||'')).map(m=>'<tr><td>'+X(dataBR(m.data||m.created_at))+'</td><td>'+X(m.codigo||'')+'</td><td>'+X(m.mac||m.serial||'')+'</td><td>'+X(m.destino||'')+'</td><td>'+X(m.obs||'')+'</td></tr>');setOut('Entrada por fornecedor / NF',tbl(['Data','Código','MAC/SN','Destino','Obs/NF/Fornecedor'],rows))})}
window.relInteligencia=function(){loadRel().then(()=>{let comTec=(D.equipamentos||[]).filter(e=>tecEq(e));let perdas=(D.equipamentos||[]).filter(e=>/perdido|inutil|descarte/i.test(e.status||''));let crit=matRel.filter(m=>!m.tecnico&&Number(m.quantidade||0)<=0);let html='<div class="relKpis"><div><small>Eqp com técnico</small><b>'+comTec.length+'</b></div><div><small>Perdas/baixas</small><b>'+perdas.length+'</b></div><div><small>Materiais críticos</small><b>'+crit.length+'</b></div><div><small>Valor perdas</small><b>'+money(perdas.reduce((s,e)=>s+Number(e.custo||0),0))+'</b></div></div>'+tbl(['Risco','Descrição'],crit.slice(0,30).map(m=>'<tr><td>Ruptura</td><td>'+X((m.tipo||'')+' '+(m.modelo||'')+' sem saldo no estoque central')+'</td></tr>'));setOut('Inteligência operacional',html)})}
function boot(){ensurePage();loadRel()}
const pgBase=window.pg;window.pg=function(p){ensurePage();pgBase(p);if(p==='relatorios')setTimeout(()=>{loadRel();renderBlocks()},150)};
document.addEventListener('DOMContentLoaded',()=>{setTimeout(boot,1000);setTimeout(boot,4000);setTimeout(boot,9000)});
})();