(function(){
let saidaCart=[];
function E(id){return document.getElementById(id)}
function H(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function K(v){try{return N(v)}catch(e){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}}
function eqs(){return (D&&D.equipamentos)||[]}
function tecEq(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function nomeEq(e){return [e.tipo,e.marca,e.modelo].filter(Boolean).join(' ')}
function disponivel(e){let s=String(e.status||'');return /estoque|reservado/i.test(s)&&!/cliente|instalado|tecnico|técnico|manut|perdido|inutil|descarte/i.test(s)}
function css(){if(E('saidaCartCss'))return;let s=document.createElement('style');s.id='saidaCartCss';s.textContent='.saidaCartBox{border:2px solid #0f4c81}.saidaCartGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.saidaCartSearch{font-size:17px;padding:14px;border:2px solid #0f4c81}.saidaCartItem{border:1px solid #e5e7eb;border-radius:12px;padding:10px;margin:8px 0;background:#f8fafc}.saidaCartBtns{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}@media(max-width:950px){.saidaCartGrid,.saidaCartBtns{grid-template-columns:1fr}}';document.head.appendChild(s)}
function boot(){css();let sec=E('p-saida');if(!sec)return;if(!E('saidaCarrinhoBox'))sec.insertAdjacentHTML('afterbegin','<div class="card saidaCartBox" id="saidaCarrinhoBox"><h2>Saída em carrinho</h2><p class="small">Bipe vários equipamentos em estoque e use o botão para preencher a saída individual com o primeiro item. O registro final usa o fluxo seguro já existente abaixo.</p><div class="saidaCartGrid"><div><input id="saidaCartBusca" class="saidaCartSearch" placeholder="Bipe ou digite MAC, SN, código ou patrimônio"><div id="saidaCartBuscaMsg" class="msg">Digite para pesquisar.</div><div id="saidaCartResultados"></div></div><div><select id="saidaCartTec"></select><input id="saidaCartObs" placeholder="OS/observação opcional"><div id="saidaCartLista"></div><div class="saidaCartBtns"><button class="pri" id="saidaCartUsar">Usar primeiro item</button><button class="warn" id="saidaCartCopiar">Copiar WhatsApp</button><button class="bad" id="saidaCartLimpar">Limpar</button></div><div id="saidaCartMsg" class="msg">Carrinho vazio.</div></div></div></div>');bind();fillTec();renderCart()}
function fillTec(){let s=E('saidaCartTec');if(!s)return;let old=s.value;let arr=[...new Set((D.tecnicos||[]).map(t=>t.nome).concat(eqs().map(tecEq)).filter(Boolean))].sort();s.innerHTML='<option value="">Selecione o técnico</option>'+arr.map(n=>'<option>'+H(n)+'</option>').join('');if(arr.includes(old))s.value=old}
function bind(){if(E('saidaCartBusca')&&!E('saidaCartBusca').dataset.b){E('saidaCartBusca').dataset.b=1;E('saidaCartBusca').oninput=pesquisar;E('saidaCartBusca').onkeyup=e=>{if(e.key==='Enter')autoAdd()}}if(E('saidaCartUsar'))E('saidaCartUsar').onclick=usarPrimeiro;if(E('saidaCartCopiar'))E('saidaCartCopiar').onclick=copiar;if(E('saidaCartLimpar'))E('saidaCartLimpar').onclick=()=>{saidaCart=[];renderCart();msg('Carrinho limpo.','warn')}}
function msg(t,c){let x=E('saidaCartMsg');if(x){x.textContent=t;x.className='msg '+(c||'')}}
function text(e){return [e.codigo,e.patrimonio,e.tipo,e.marca,e.modelo,e.mac,e.serial,e.status,e.local,tecEq(e)].join(' ')}
function add(id){let e=eqs().find(x=>x.id===id);if(!e)return;if(!disponivel(e))return msg('Bloqueado: '+(e.codigo||'')+' está com status '+(e.status||'-')+'.','bad');if(saidaCart.includes(id))return msg('Item já está no carrinho.','warn');saidaCart.push(id);renderCart();msg('Adicionado ao carrinho.','ok')}
function rem(id){saidaCart=saidaCart.filter(x=>x!==id);renderCart()}
function pesquisar(){let q=(E('saidaCartBusca')&&E('saidaCartBusca').value||'').trim(),out=E('saidaCartResultados'),m=E('saidaCartBuscaMsg');if(!out)return;if(!q){out.innerHTML='';if(m)m.textContent='Digite para pesquisar.';return}let arr=eqs().filter(e=>K(text(e)).includes(K(q))).slice(0,15);if(m){m.textContent='Encontrado(s): '+arr.length;m.className='msg '+(arr.length?'ok':'bad')}out.innerHTML=arr.map(e=>'<div class="saidaCartItem"><b>'+H(e.codigo)+'</b> • '+H(nomeEq(e))+'<br><small>'+H(e.mac||e.serial||'')+' • '+H(e.status||'')+'</small><br><button class="pri" onclick="saidaCartAdd(\''+e.id+'\')" '+(!disponivel(e)?'disabled':'')+'>Adicionar ao carrinho</button></div>').join('')||'<div class="msg bad">Nenhum equipamento encontrado.</div>'}
function autoAdd(){let q=K(E('saidaCartBusca').value);let e=eqs().find(x=>K(x.mac)===q||K(x.serial)===q||K(x.codigo)===q||K(x.patrimonio)===q);if(e){add(e.id);E('saidaCartBusca').value='';pesquisar()}}
function renderCart(){let b=E('saidaCartLista');if(!b)return;b.innerHTML=saidaCart.map(id=>{let e=eqs().find(x=>x.id===id);return e?'<div class="saidaCartItem"><b>'+H(e.codigo)+'</b> • '+H(nomeEq(e))+'<br><small>'+H(e.mac||e.serial||'')+'</small><button class="bad" onclick="saidaCartRem(\''+id+'\')">Remover</button></div>':''}).join('')||'<div class="msg">Nenhum equipamento no carrinho.</div>'}
function usarPrimeiro(){let id=saidaCart[0],e=eqs().find(x=>x.id===id),tec=E('saidaCartTec')&&E('saidaCartTec').value;if(!e)return msg('Carrinho vazio.','bad');if(!tec)return msg('Selecione o técnico.','bad');if(E('q'))E('q').value=e.mac||e.serial||e.codigo;if(typeof choose==='function')choose(id);if(E('movTipo'))E('movTipo').value='Saída para técnico';if(E('movTec'))E('movTec').value=tec;if(E('movDest'))E('movDest').value='Técnico';if(E('movObs'))E('movObs').value=E('saidaCartObs').value||'Saída pelo carrinho';msg('Primeiro item enviado para o formulário. Clique em Registrar saída.','ok')}
function buildMsg(){let tec=E('saidaCartTec')&&E('saidaCartTec').value||'-',obs=E('saidaCartObs')&&E('saidaCartObs').value||'',l=['📦 SAÍDA DE ESTOQUE','Técnico: '+tec,'Data: '+new Date().toLocaleDateString('pt-BR')];if(obs)l.push('Obs/OS: '+obs);l.push('','EQUIPAMENTOS:');l.push(saidaCart.map((id,i)=>{let e=eqs().find(x=>x.id===id);return e?(i+1)+'. '+(e.codigo||'')+' | '+nomeEq(e)+' | MAC/SN: '+(e.mac||e.serial||'-'):''}).filter(Boolean).join('\n')||'Sem equipamentos.');l.push('','Favor conferir e confirmar.');return l.join('\n')}
function copiar(){navigator.clipboard.writeText(buildMsg()).then(()=>msg('Mensagem copiada.','ok'))}
window.saidaCartAdd=add;window.saidaCartRem=rem;
const oldPg=window.pg;if(!window.__saidaCartPg&&typeof oldPg==='function'){window.__saidaCartPg=1;window.pg=function(p){oldPg(p);if(p==='saida')setTimeout(boot,100)}}
const oldRender=window.render;if(!window.__saidaCartRender&&typeof oldRender==='function'){window.__saidaCartRender=1;window.render=function(){oldRender();if(E('p-saida')&&E('p-saida').classList.contains('on'))setTimeout(boot,120)}}
document.addEventListener('DOMContentLoaded',()=>{[1000,3000,7000,12000].forEach(t=>setTimeout(boot,t))});
window.saidaCarrinhoBoot=boot;
})();