(function(){
let tecSel='';
let matSaldosMain=[];
let movsTec=[];
function T(id){return document.getElementById(id)}
function V(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function real(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function dataBR(v){if(!v)return '-';try{return new Date(v).toLocaleString('pt-BR')}catch(e){return String(v)}}
function loadExtraScript(id,src){if(document.getElementById(id))return;var s=document.createElement('script');s.id=id;s.src=src;document.body.appendChild(s)}
async function rpcTec(name,params){if(typeof rpcOne==='function')return await rpcOne(name,params);const r=await db().rpc(name,params);if(r.error)throw r.error;return Array.isArray(r.data)?r.data[0]:r.data}
async function carregarMateriaisTecnico(){try{matSaldosMain=await loadTable('materiais_saldos','tipo',true)}catch(e){matSaldosMain=[]}try{movsTec=await loadTable('movimentos','created_at',false)}catch(e){movsTec=(D&&D.movimentos)||[]}}
function tecnicoAtivo(t){return !t||t.ativo!==false}
function tecEqNome(e){return (e.tecnicoAtual||e.tecnico_atual||e.tecnico||'').trim()}
function nomeEq(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function nomeMat(m){return ((m.tipo||'')+' '+(m.marca||'')+' '+(m.modelo||'')).trim()}
function qtd(v){let n=Number(v||0);return Number.isInteger(n)?String(n):String(n).replace('.',',')}
function nomesTecnicos(){return [...new Set([...(D.tecnicos||[]).filter(tecnicoAtivo).map(t=>t.nome),...(D.equipamentos||[]).map(tecEqNome),...matSaldosMain.map(m=>m.tecnico)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function eqsTec(nome){return (D.equipamentos||[]).filter(e=>tecEqNome(e)===nome&&!['Em estoque','Inutilizado','Perdido','Descarte autorizado','Instalado no cliente','Instalado cliente'].includes(e.status||''))}
function matsTec(nome){return matSaldosMain.filter(m=>(m.tecnico||'')===nome&&Number(m.quantidade||0)>0)}
function movsDoTec(nome){return (movsTec||[]).filter(m=>(m.tecnico||'')===nome).slice(0,12)}
function valorTec(nome){return eqsTec(nome).reduce((s,e)=>s+Number(e.custo||0),0)}
function ultimaMov(nome){let m=movsDoTec(nome)[0];return m?dataBR(m.created_at||m.data):'-'}
function pendenciasTec(nome){let arr=[];let eqs=eqsTec(nome),mats=matsTec(nome);if(eqs.length)arr.push(eqs.length+' equipamento(s) sob responsabilidade');if(mats.length)arr.push(mats.length+' material(is) sob responsabilidade');let semMac=eqs.filter(e=>!e.mac&&!e.serial).length;if(semMac)arr.push(semMac+' equipamento(s) sem MAC/SN');return arr}
function kpiHtml(nome){let eqs=eqsTec(nome),mats=matsTec(nome),pend=pendenciasTec(nome);return '<div><small>Equipamentos</small><b>'+eqs.length+'</b></div><div><small>Materiais</small><b>'+mats.length+'</b></div><div><small>Valor patrimônio</small><b>'+real(valorTec(nome))+'</b></div><div><small>Pendências</small><b>'+pend.length+'</b></div>';}
function tabelaTec(){let eqs=eqsTec(tecSel),mats=matsTec(tecSel),movs=movsDoTec(tecSel),pend=pendenciasTec(tecSel);return '<div id="tecMainAreaConteudo"><h3>Resumo</h3><div class="techKpis">'+kpiHtml(tecSel)+'</div><h3>Equipamentos patrimoniais</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Valor</th></tr></thead><tbody>'+(eqs.map(e=>'<tr><td>'+V(e.codigo)+'</td><td>'+V(nomeEq(e))+'</td><td>'+V(e.mac||e.serial||'-')+'</td><td>'+V(e.status||'-')+'</td><td>'+V(e.local||'-')+'</td><td>'+real(e.custo||0)+'</td></tr>').join('')||'<tr><td colspan="6">Sem equipamento patrimonial em posse.</td></tr>')+'</tbody></table></div><h3>Materiais em posse</h3><div class="tbl"><table><thead><tr><th>Categoria</th><th>Material</th><th>Quantidade</th><th>Unidade</th><th>Local</th></tr></thead><tbody>'+(mats.map(m=>'<tr><td>'+V(m.categoria)+'</td><td>'+V(nomeMat(m))+'</td><td><b>'+V(qtd(m.quantidade))+'</b></td><td>'+V(m.unidade_saida)+'</td><td>'+V(m.local||'Técnico')+'</td></tr>').join('')||'<tr><td colspan="5">Sem material em posse.</td></tr>')+'</tbody></table></div><h3>Pendências</h3>'+(pend.length?'<div class="msg warn">'+pend.map(V).join('<br>')+'</div>':'<div class="msg ok">Sem pendência crítica aparente.</div>')+'<h3>Últimas movimentações</h3><div class="tbl"><table><thead><tr><th>Data</th><th>Tipo</th><th>Item</th><th>Destino</th><th>Cliente/OS</th><th>Obs</th></tr></thead><tbody>'+(movs.map(m=>'<tr><td>'+V(dataBR(m.created_at||m.data))+'</td><td>'+V(m.tipo||'-')+'</td><td>'+V(m.codigo||m.mac||m.serial||'-')+'</td><td>'+V(m.destino||'-')+'</td><td>'+V((m.cliente||'-')+' / '+(m.os||'-'))+'</td><td>'+V(m.obs||m.motivo||'-')+'</td></tr>').join('')||'<tr><td colspan="6">Sem movimentação recente.</td></tr>')+'</tbody></table></div></div>'}
function renderListaTecnicosMain(){let box=T('tecMainLista');if(!box)return;let f=(T('tecMainBusca')&&T('tecMainBusca').value||'').toLowerCase();let arr=nomesTecnicos().filter(n=>!f||n.toLowerCase().includes(f));box.innerHTML=arr.map(n=>{let rec=(D.tecnicos||[]).find(t=>t.nome===n&&tecnicoAtivo(t));let eq=eqsTec(n).length,mt=matsTec(n).length;return '<div class="item"><div data-tec-main="'+V(n)+'" style="flex:1;cursor:pointer"><b>'+V(n)+'</b><br><small>'+eq+' equipamento(s) • '+mt+' material(is) • '+real(valorTec(n))+'</small></div><button class="bad" data-del-tec-main="'+V(n)+'" data-id="'+V(rec?rec.id:'')+'">Desativar</button></div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>';box.querySelectorAll('[data-tec-main]').forEach(x=>x.onclick=function(){tecSel=this.dataset.tecMain;renderTecnicoSelecionado(true)});box.querySelectorAll('[data-del-tec-main]').forEach(x=>x.onclick=function(ev){ev.stopPropagation();desativarTecMain(this.dataset.id,this.dataset.delTecMain)})}
function renderTecnicoSelecionado(show){if(!T('tecMainTitulo'))return;if(!tecSel){T('tecMainTitulo').textContent='Selecione um técnico';T('tecMainKpis').innerHTML='';T('tecMainArea').innerHTML='';return}T('tecMainTitulo').textContent='Técnico: '+tecSel+' • última movimentação: '+ultimaMov(tecSel);T('tecMainKpis').innerHTML=kpiHtml(tecSel);if(show)T('tecMainArea').innerHTML=tabelaTec()}
async function atualizarTecnicosMain(show=true){await carregarMateriaisTecnico();renderListaTecnicosMain();renderTecnicoSelecionado(show)}
async function addTecMain(){try{let nome=(T('tecMainNome').value||'').trim();if(!nome){msg('tecMainMsg','Informe o nome do técnico.','bad');return}if((D.tecnicos||[]).some(t=>tecnicoAtivo(t)&&String(t.nome).toLowerCase()===nome.toLowerCase())){msg('tecMainMsg','Técnico já existe.','bad');return}await rpcTec('rpc_criar_tecnico',{p_nome:nome});T('tecMainNome').value='';tecSel=nome;if(typeof loadAll==='function')await loadAll();await atualizarTecnicosMain(true);msg('tecMainMsg','Técnico salvo com segurança.','ok')}catch(e){msg('tecMainMsg','Erro: '+e.message,'bad')}}
async function desativarTecMain(id,nome){try{if(eqsTec(nome).length||matsTec(nome).length){msg('tecMainMsg','Não é possível desativar técnico com equipamento/material em posse. Devolva ou transfira antes.','bad');return}if(!id){msg('tecMainMsg','Este técnico aparece por movimentação antiga, mas não tem cadastro ativo para desativar.','warn');return}let motivo=prompt('Motivo para desativar técnico '+nome+':','Desativado pelo administrador');if(motivo===null)return;if(!motivo.trim()){msg('tecMainMsg','Informe o motivo da desativação.','bad');return}await rpcTec('rpc_desativar_tecnico',{p_tecnico_id:id,p_motivo:motivo.trim()});if(typeof loadAll==='function')await loadAll();tecSel='';await atualizarTecnicosMain(false);msg('tecMainMsg','Técnico desativado. Histórico preservado.','ok')}catch(e){msg('tecMainMsg','Erro ao desativar: '+e.message,'bad')}}
function removerBotoesAntigos(){let a=T('tecMainActions');if(a)a.remove();['tecMainVer','tecMainCopiar','tecMainPrint'].forEach(id=>{let b=T(id);if(b)b.remove()})}
function css(){if(T('tecMainCss'))return;let s=document.createElement('style');s.id='tecMainCss';s.textContent='#tecMainActions,#tecMainVer,#tecMainCopiar,#tecMainPrint{display:none!important}';document.head.appendChild(s)}
function bindTecMain(){css();removerBotoesAntigos();if(T('tecMainBusca'))T('tecMainBusca').oninput=renderListaTecnicosMain;if(T('tecMainAdd'))T('tecMainAdd').onclick=addTecMain;if(T('tecMainReload'))T('tecMainReload').onclick=()=>atualizarTecnicosMain(true).then(()=>msg('tecMainMsg','Lista atualizada.','ok'))}
function carregarShellOficial(){loadExtraScript('uiShellDirectFromTec','ui_shell.js?v=3');loadExtraScript('relCoreDirectFromTec','relatorios_core.js?v=4');loadExtraScript('opRapidaCoreFromTec','operacao_rapida_core.js?v=1');loadExtraScript('saidaCartFromTec','saida_carrinho.js?v=3');loadExtraScript('entradaPatFromTec','entrada_patrimonial_guard.js?v=2');setTimeout(function(){if(window.uiShellRun)window.uiShellRun();if(window.relatoriosCoreBoot)window.relatoriosCoreBoot();if(window.operacaoRapidaCoreBoot)window.operacaoRapidaCoreBoot();if(window.saidaCarrinhoBoot)window.saidaCarrinhoBoot();if(window.entradaPatrimonialGuardRun)window.entradaPatrimonialGuardRun()},1200)}
const pgOriginal=window.pg;window.pg=function(p){pgOriginal(p);if(p==='tecnicosMain')setTimeout(()=>atualizarTecnicosMain(true),100);setTimeout(carregarShellOficial,150)};
const renderOriginal=window.render;window.render=function(){renderOriginal();bindTecMain();if(T('p-tecnicosMain')&&T('p-tecnicosMain').classList.contains('on'))atualizarTecnicosMain(false);setTimeout(carregarShellOficial,150)};
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{bindTecMain();atualizarTecnicosMain(false);carregarShellOficial()},1500));
})();