(function(){
let tecSel='';
let matSaldosMain=[];
function T(id){return document.getElementById(id)}
function V(v){try{return esc(v??'')}catch(e){return String(v??'')}}
function real(v){try{return br(Number(v||0))}catch(e){return 'R$ '+Number(v||0).toFixed(2)}}
function loadExtraScript(id,src){if(document.getElementById(id))return;var s=document.createElement('script');s.id=id;s.src=src;document.body.appendChild(s)}
async function carregarMateriaisTecnico(){try{matSaldosMain=await loadTable('materiais_saldos','tipo',true)}catch(e){matSaldosMain=[]}}
function tecEqNome(e){return e.tecnicoAtual||e.tecnico_atual||e.tecnico||''}
function nomeEq(e){return ((e.tipo||'')+' '+(e.marca||'')+' '+(e.modelo||'')).trim()}
function nomesTecnicos(){return [...new Set([...(D.tecnicos||[]).map(t=>t.nome),...(D.equipamentos||[]).map(tecEqNome),...matSaldosMain.map(m=>m.tecnico)].filter(Boolean))].sort()}
function eqsTec(nome){return (D.equipamentos||[]).filter(e=>tecEqNome(e)===nome&&!['Em estoque','Inutilizado','Perdido','Descarte autorizado','Instalado no cliente','Instalado cliente'].includes(e.status||''))}
function matsTec(nome){return matSaldosMain.filter(m=>(m.tecnico||'')===nome&&Number(m.quantidade||0)!==0)}
function tabelaTec(){let eqs=eqsTec(tecSel),mats=matsTec(tecSel);return '<h3>Equipamentos patrimoniais</h3><div class="tbl"><table><thead><tr><th>Código</th><th>Equipamento</th><th>MAC/SN</th><th>Status</th><th>Local</th><th>Valor</th></tr></thead><tbody>'+(eqs.map(e=>'<tr><td>'+V(e.codigo)+'</td><td>'+V(nomeEq(e))+'</td><td>'+V(e.mac||e.serial||'-')+'</td><td>'+V(e.status||'-')+'</td><td>'+V(e.local||'-')+'</td><td>'+real(e.custo||0)+'</td></tr>').join('')||'<tr><td colspan="6">Sem equipamento patrimonial em posse.</td></tr>')+'</tbody></table></div><h3>Materiais em posse</h3><div class="tbl"><table><thead><tr><th>Categoria</th><th>Material</th><th>Quantidade</th><th>Unidade</th><th>Local</th></tr></thead><tbody>'+(mats.map(m=>'<tr><td>'+V(m.categoria)+'</td><td>'+V(m.tipo+' '+(m.marca||'')+' '+m.modelo)+'</td><td><b>'+V(m.quantidade)+'</b></td><td>'+V(m.unidade_saida)+'</td><td>'+V(m.local||'Técnico')+'</td></tr>').join('')||'<tr><td colspan="5">Sem material em posse.</td></tr>')+'</tbody></table></div>'}
function renderListaTecnicosMain(){let box=T('tecMainLista');if(!box)return;let f=(T('tecMainBusca')&&T('tecMainBusca').value||'').toLowerCase();let arr=nomesTecnicos().filter(n=>!f||n.toLowerCase().includes(f));box.innerHTML=arr.map(n=>{let rec=(D.tecnicos||[]).find(t=>t.nome===n);return '<div class="item"><div data-tec-main="'+V(n)+'" style="flex:1;cursor:pointer"><b>'+V(n)+'</b><br><small>'+eqsTec(n).length+' equipamento(s) • '+matsTec(n).length+' material(is)</small></div><button class="bad" data-del-tec-main="'+V(n)+'" data-id="'+V(rec?rec.id:'')+'">Excluir</button></div>'}).join('')||'<div class="msg">Nenhum técnico cadastrado.</div>';box.querySelectorAll('[data-tec-main]').forEach(x=>x.onclick=function(){tecSel=this.dataset.tecMain;renderTecnicoSelecionado(true)});box.querySelectorAll('[data-del-tec-main]').forEach(x=>x.onclick=function(ev){ev.stopPropagation();excluirTecMain(this.dataset.id,this.dataset.delTecMain)})}
function renderTecnicoSelecionado(show){if(!T('tecMainTitulo'))return;if(!tecSel){T('tecMainTitulo').textContent='Selecione um técnico';T('tecMainKpis').innerHTML='';T('tecMainArea').innerHTML='';return}let eqs=eqsTec(tecSel),mats=matsTec(tecSel),valor=eqs.reduce((s,e)=>s+Number(e.custo||0),0);T('tecMainTitulo').textContent='Técnico: '+tecSel;T('tecMainKpis').innerHTML='<div><small>Equipamentos</small><b>'+eqs.length+'</b></div><div><small>Materiais</small><b>'+mats.length+'</b></div><div><small>Valor patrimônio</small><b>'+real(valor)+'</b></div><div><small>Total técnicos</small><b>'+nomesTecnicos().length+'</b></div>';if(show)T('tecMainArea').innerHTML=tabelaTec()}
async function atualizarTecnicosMain(show=true){await carregarMateriaisTecnico();renderListaTecnicosMain();renderTecnicoSelecionado(show)}
async function addTecMain(){try{let nome=(T('tecMainNome').value||'').trim();if(!nome){msg('tecMainMsg','Informe o nome do técnico.','bad');return}if((D.tecnicos||[]).some(t=>String(t.nome).toLowerCase()===nome.toLowerCase())){msg('tecMainMsg','Técnico já existe.','bad');return}let salvo=await ins('tecnicos',{nome,ativo:true});D.tecnicos.push(salvo);T('tecMainNome').value='';tecSel=nome;await atualizarTecnicosMain(true);msg('tecMainMsg','Técnico adicionado.','ok')}catch(e){msg('tecMainMsg','Erro: '+e.message,'bad')}}
async function excluirTecMain(id,nome){try{if(eqsTec(nome).length||matsTec(nome).length){alert('Não exclua técnico com equipamento/material em posse. Devolva ou transfira antes.');return}if(!id){alert('Este técnico aparece por movimentação antiga, mas não tem cadastro direto para excluir.');return}if(!confirm('Excluir técnico '+nome+'?'))return;await del('tecnicos',id);D.tecnicos=D.tecnicos.filter(t=>t.id!==id);if(tecSel===nome)tecSel='';await atualizarTecnicosMain(false);msg('tecMainMsg','Técnico excluído.','ok')}catch(e){msg('tecMainMsg','Erro ao excluir: '+e.message,'bad')}}
function copiarTecMain(){if(!tecSel){msg('tecMainMsg','Selecione um técnico.','bad');return}let txt='RELATÓRIO DO TÉCNICO\nTécnico: '+tecSel+'\nEquipamentos: '+eqsTec(tecSel).length+'\nMateriais: '+matsTec(tecSel).length+'\n\nEQUIPAMENTOS:\n'+(eqsTec(tecSel).map(e=>'- '+(e.codigo||'')+' | '+nomeEq(e)+' | '+(e.mac||e.serial||'-')+' | '+(e.status||'')).join('\n')||'Sem equipamentos.')+'\n\nMATERIAIS:\n'+(matsTec(tecSel).map(m=>'- '+m.tipo+' '+(m.marca||'')+' '+m.modelo+' | '+m.quantidade+' '+m.unidade_saida).join('\n')||'Sem materiais.');navigator.clipboard.writeText(txt).then(()=>msg('tecMainMsg','Copiado.','ok'))}
function bindTecMain(){if(T('tecMainBusca'))T('tecMainBusca').oninput=renderListaTecnicosMain;if(T('tecMainAdd'))T('tecMainAdd').onclick=addTecMain;if(T('tecMainReload'))T('tecMainReload').onclick=()=>atualizarTecnicosMain(true).then(()=>msg('tecMainMsg','Lista atualizada.','ok'));if(T('tecMainVer'))T('tecMainVer').onclick=()=>{if(!tecSel){msg('tecMainMsg','Selecione um técnico.','bad');return}T('tecMainArea').innerHTML=tabelaTec()};if(T('tecMainCopiar'))T('tecMainCopiar').onclick=copiarTecMain;if(T('tecMainPrint'))T('tecMainPrint').onclick=()=>window.print()}
function carregarShellOficial(){loadExtraScript('uiShellDirectFromTec','ui_shell.js?v=3');loadExtraScript('relCoreDirectFromTec','relatorios_core.js?v=3');setTimeout(function(){if(window.uiShellRun)window.uiShellRun();if(window.relatoriosCoreBoot)window.relatoriosCoreBoot()},1200)}
const pgOriginal=window.pg;window.pg=function(p){pgOriginal(p);if(p==='tecnicosMain')setTimeout(()=>atualizarTecnicosMain(true),100);setTimeout(carregarShellOficial,150)};
const renderOriginal=window.render;window.render=function(){renderOriginal();bindTecMain();if(T('p-tecnicosMain')&&T('p-tecnicosMain').classList.contains('on'))atualizarTecnicosMain(false);setTimeout(carregarShellOficial,150)};
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{bindTecMain();atualizarTecnicosMain(false);carregarShellOficial()},1500));
})();