(function(){
const OFFICIAL=[
 {group:'Principal',items:[['operacaoRapida','Operação rápida'],['dash','Dashboard']]},
 {group:'Estoque',items:[['entrada','Entrada'],['estoque','Estoque central'],['equipamentos','Equipamentos'],['materiaisMain','Materiais']]},
 {group:'Técnicos e campo',items:[['saida','Saída / Instalação'],['devolucao','Devolução'],['tecnicosMain','Técnicos'],['tecnico','Estoque por técnico'],['retorno','Retorno sem cadastro']]},
 {group:'Controle',items:[['manut','Manutenção/Teste'],['relatorios','Relatórios'],['historico','Histórico']]},
 {group:'Administração',items:[['cadastros','Produtos e cadastros']]}
];
const TITLE={login:'Conexão',operacaoRapida:'Operação rápida',dash:'Dashboard',entrada:'Entrada de estoque',estoque:'Estoque central',equipamentos:'Equipamentos',materiaisMain:'Materiais',saida:'Saída / Instalação',devolucao:'Devolução',tecnicosMain:'Técnicos',tecnico:'Estoque por técnico',retorno:'Retorno sem cadastro',manut:'Manutenção/Teste',relatorios:'Relatórios',historico:'Histórico',cadastros:'Produtos e cadastros'};
const LEGACY_HIDE=['operacaoEstoque','operacao','bipagem','saidaLote','devolucaoLote','conferenciaTec','inventarioLocal','pendencias'];
function E(id){return document.getElementById(id)}
function css(){if(E('uiShellCss'))return;let s=document.createElement('style');s.id='uiShellCss';s.textContent=`
.side{padding:16px 14px!important}.brand{background:linear-gradient(135deg,#10243c,#0f4c81);border:1px solid #244260;border-radius:18px;padding:14px;margin-bottom:14px}.shellGroup{margin:16px 0 6px;padding:0 10px;color:#8fb3d6;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.nav{position:relative;transition:.15s ease}.nav[data-official="1"]{font-weight:800}.nav.on{background:#0f4c81!important;box-shadow:inset 4px 0 0 #93c5fd}.nav.shellHidden{display:none!important}.shellStatus{margin-top:18px!important}.main{max-width:1600px}.card{transition:.15s ease}.card:hover{box-shadow:0 14px 34px #0f172a18}.shellPageHead{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.shellBadge{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:6px 10px;background:#eef6ff;color:#0f4c81;font-size:12px;font-weight:900}.shellQuick{display:flex;gap:8px;flex-wrap:wrap}.shellQuick button{font-size:12px;padding:8px 10px}.dangerAction,.bad{font-weight:900}.tbl table th{position:sticky;top:0;z-index:1}.msg.bad{background:#fee2e2;color:#991b1b;border-color:#fecaca}.msg.ok{background:#dcfce7;color:#166534;border-color:#bbf7d0}.msg.warn{background:#fef3c7;color:#92400e;border-color:#fde68a}@media(max-width:950px){.side{height:auto!important;max-height:none!important}.nav{display:inline-block;width:auto;margin:3px}.shellGroup{display:block;margin-top:12px}.main{padding:14px}.top h1{font-size:22px}.tbl table{min-width:760px}}`;
document.head.appendChild(s)}
function ensureButton(side,p,label){let b=document.querySelector('.nav[data-p="'+p+'"]');if(!b){b=document.createElement('button');b.className='nav';b.dataset.p=p;side.appendChild(b)}b.textContent=label;b.dataset.official='1';b.classList.remove('shellHidden');return b}
function bindNav(){document.querySelectorAll('.nav').forEach(b=>{b.onclick=function(){if(typeof pg==='function')pg(b.dataset.p)}})}
function rebuildMenu(){let side=document.querySelector('.side');if(!side)return;css();let brand=side.querySelector('.brand');let status=E('conn')?E('conn').closest('.item'):null;let existing={};document.querySelectorAll('.nav').forEach(b=>{let p=b.dataset.p;if(!p)return;if(existing[p]){b.remove();return}existing[p]=b});LEGACY_HIDE.forEach(p=>{let b=document.querySelector('.nav[data-p="'+p+'"]');if(b)b.classList.add('shellHidden')});side.querySelectorAll('.shellGroup').forEach(x=>x.remove());let frag=document.createDocumentFragment();OFFICIAL.forEach(g=>{let h=document.createElement('div');h.className='shellGroup';h.textContent=g.group;frag.appendChild(h);g.items.forEach(it=>frag.appendChild(ensureButton(side,it[0],it[1])))});if(brand)brand.after(frag);else side.prepend(frag);if(status){status.classList.add('shellStatus');side.appendChild(status)}bindNav()}
function normalizeTitles(){document.querySelectorAll('.nav').forEach(b=>{let p=b.dataset.p;if(TITLE[p]&&b.dataset.official==='1')b.textContent=TITLE[p]});let title=E('title');let on=document.querySelector('.page.on');if(title&&on){let p=on.id.replace(/^p-/,'');title.textContent=TITLE[p]||title.textContent}let sub=document.querySelector('.top small');if(sub)sub.textContent='LIKE Estoque • Operação, estoque e rastreabilidade'}
function enhanceTop(){let top=document.querySelector('.top');if(!top||E('shellQuick'))return;let box=document.createElement('div');box.id='shellQuick';box.className='shellQuick';box.innerHTML='<button class="pri" onclick="pg(\'operacaoRapida\')">Operação rápida</button><button onclick="pg(\'entrada\')">Entrada</button><button onclick="pg(\'materiaisMain\')">Materiais</button><button onclick="pg(\'relatorios\')">Relatórios</button>';let right=top.lastElementChild;if(right)right.prepend(box)}
function guardPages(){['p-relatorios','p-materiaisMain','p-tecnicosMain'].forEach(id=>{let all=[...document.querySelectorAll('#'+id)];all.slice(1).forEach(x=>x.remove())});}
function patchPg(){if(window.__uiShellPgPatched||typeof pg!=='function')return;window.__uiShellPgPatched=true;let old=window.pg;window.pg=function(p){old(p);setTimeout(()=>{document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('on',b.dataset.p===p));normalizeTitles();guardPages();},20)}}
function run(){css();rebuildMenu();enhanceTop();guardPages();patchPg();normalizeTitles();}
window.uiShellRun=run;
document.addEventListener('DOMContentLoaded',()=>{[300,1500,4000,9000,15000,22000].forEach(t=>setTimeout(run,t))});
})();